package com.heinika.pokeg.utils

import androidx.compose.ui.graphics.Color
import com.heinika.pokeg.R
import com.heinika.pokeg.ui.theme.*

enum class EvolutionProps(val color: Color, val nameResId: Int, val flavorResId: Int, val imageResId: Int) {
  FireStone(fireColor,R.string.Fire_Stone, R.string.Fire_Stone_flavor, R.drawable.evolution_prop_1),
  ThunderStone(electricColor,R.string.Thunder_Stone, R.string.Thunder_Stone_flavor, R.drawable.evolution_prop_2),
  WaterStone(waterColor,R.string.Water_Stone, R.string.Water_Stone_flavor, R.drawable.evolution_prop_3),
  LeafStone(grassColor,R.string.Leaf_Stone, R.string.Leaf_Stone_flavor, R.drawable.evolution_prop_4),
  MoonStone(normalColor,R.string.Moon_Stone, R.string.Moon_Stone_flavor, R.drawable.evolution_prop_5),
  SunStone(rockColor,R.string.Sun_Stone, R.string.Sun_Stone_flavor, R.drawable.evolution_prop_6),
  ShinyStone(fairyColor,R.string.Shiny_Stone, R.string.Shiny_Stone_flavor, R.drawable.evolution_prop_7),
  DuskStone(darkColor,R.string.Dusk_Stone, R.string.Dusk_Stone_flavor, R.drawable.evolution_prop_8),
  DawnStone(steelColor,R.string.Dawn_Stone, R.string.Dawn_Stone_flavor, R.drawable.evolution_prop_9),
  IceStone(iceColor,R.string.Ice_Stone, R.string.Ice_Stone_flavor, R.drawable.evolution_prop_10),
  SweetApple(Color.Red,R.string.Sweet_Apple, R.string.Sweet_Apple_flavor, R.drawable.evolution_prop_11),
  TartApple(grassColor,R.string.Tart_Apple, R.string.Tart_Apple_flavor, R.drawable.evolution_prop_12),
  CrackedPot(bugColor,R.string.Cracked_Pot, R.string.Cracked_Pot_flavor, R.drawable.evolution_prop_13),
  ChippedPot(dragonColor,R.string.Chipped_Pot, R.string.Chipped_Pot_flavor, R.drawable.evolution_prop_14),
  GalaricaCuff(psychicColor,R.string.Galarica_Cuff, R.string.Galarica_Cuff_flavor, R.drawable.evolution_prop_15),
  GalaricaWreath(grassColor,R.string.Galarica_Wreath, R.string.Galarica_Wreath_flavor, R.drawable.evolution_prop_16)
}

enum class Pokeball(val nameResId: Int, val flavorResId: Int, val imageResId: Int){
  PokeBall(R.string.Poké_Ball,R.string.Poké_Ball_flavor,R.drawable.pokeball_prop_1),
  GreatBall(R.string.Great_Ball,R.string.Great_Ball_flavor,R.drawable.pokeball_prop_2),
  UltraBall(R.string.Ultra_Ball,R.string.Ultra_Ball_flavor,R.drawable.pokeball_prop_3),
  SafariBall(R.string.Safari_Ball,R.string.Safari_Ball_flavor,R.drawable.pokeball_prop_4),
  MasterBall(R.string.Master_Ball,R.string.Master_Ball_flavor,R.drawable.pokeball_prop_5),
  FastBall(R.string.Fast_Ball,R.string.Fast_Ball_flavor,R.drawable.pokeball_prop_6),
  LevelBall(R.string.Level_Ball,R.string.Level_Ball_flavor,R.drawable.pokeball_prop_7),
  LureBall(R.string.Lure_Ball,R.string.Lure_Ball_flavor,R.drawable.pokeball_prop_8),
  HeavyBall(R.string.Heavy_Ball,R.string.Heavy_Ball_flavor,R.drawable.pokeball_prop_9),
  LoveBall(R.string.Love_Ball,R.string.Love_Ball_flavor,R.drawable.pokeball_prop_10),
  FriendBall(R.string.Friend_Ball,R.string.Friend_Ball_flavor,R.drawable.pokeball_prop_11),
  MoonBall(R.string.Moon_Ball,R.string.Moon_Ball_flavor,R.drawable.pokeball_prop_12),
  SportBall(R.string.Sport_Ball,R.string.Sport_Ball_flavor,R.drawable.pokeball_prop_13),
  ParkBall(R.string.Park_Ball,R.string.Park_Ball_flavor,R.drawable.pokeball_prop_14),
  NetBall(R.string.Net_Ball,R.string.Net_Ball_flavor,R.drawable.pokeball_prop_15),
  DiveBall(R.string.Dive_Ball,R.string.Dive_Ball_flavor,R.drawable.pokeball_prop_16),
  NestBall(R.string.Nest_Ball,R.string.Nest_Ball_flavor,R.drawable.pokeball_prop_17),
  RepeatBall(R.string.Repeat_Ball,R.string.Repeat_Ball_flavor,R.drawable.pokeball_prop_18),
  TimerBall(R.string.Timer_Ball,R.string.Timer_Ball_flavor,R.drawable.pokeball_prop_19),
  LuxuryBall(R.string.Luxury_Ball,R.string.Luxury_Ball_flavor,R.drawable.pokeball_prop_20),
  PremierBall(R.string.Premier_Ball,R.string.Premier_Ball_flavor,R.drawable.pokeball_prop_21),
  DuskBall(R.string.Dusk_Ball,R.string.Dusk_Ball_flavor,R.drawable.pokeball_prop_22),
  HealBall(R.string.Heal_Ball,R.string.Heal_Ball_flavor,R.drawable.pokeball_prop_23),
  QuickBall(R.string.Quick_Ball,R.string.Quick_Ball_flavor,R.drawable.pokeball_prop_24),
  CherishBall(R.string.Cherish_Ball,R.string.Cherish_Ball_flavor,R.drawable.pokeball_prop_25),
  DreamBall(R.string.Dream_Ball,R.string.Dream_Ball_flavor,R.drawable.pokeball_prop_26),
  BeastBall(R.string.Beast_Ball,R.string.Beast_Ball_flavor,R.drawable.pokeball_prop_27),
}

enum class Fossil(val nameResId: Int, val flavorResId: Int, val imageResId: Int){
  Helix_Fossil(R.string.Helix_Fossil,R.string.Helix_Fossil_flavor,R.drawable.fossil_prop_1),
  Dome_Fossil(R.string.Dome_Fossil,R.string.Dome_Fossil_flavor,R.drawable.fossil_prop_2),
  Old_Amber(R.string.Old_Amber,R.string.Old_Amber_flavor,R.drawable.fossil_prop_3),
  Root_Fossil(R.string.Root_Fossil,R.string.Root_Fossil_flavor,R.drawable.fossil_prop_4),
  Claw_Fossil(R.string.Claw_Fossil,R.string.Claw_Fossil_flavor,R.drawable.fossil_prop_5),
  Skull_Fossil(R.string.Skull_Fossil,R.string.Skull_Fossil_flavor,R.drawable.fossil_prop_6),
  Armor_Fossil(R.string.Armor_Fossil,R.string.Armor_Fossil_flavor,R.drawable.fossil_prop_7),
  Cover_Fossil(R.string.Cover_Fossil,R.string.Cover_Fossil_flavor,R.drawable.fossil_prop_8),
  Plume_Fossil(R.string.Plume_Fossil,R.string.Plume_Fossil_flavor,R.drawable.fossil_prop_9),
  Jaw_Fossil(R.string.Jaw_Fossil,R.string.Jaw_Fossil_flavor,R.drawable.fossil_prop_10),
  Sail_Fossil(R.string.Sail_Fossil,R.string.Sail_Fossil_flavor,R.drawable.fossil_prop_11),
  Fossilized_Bird(R.string.Fossilized_Bird,R.string.Fossilized_Bird_flavor,R.drawable.fossil_prop_12),
  Fossilized_Fish(R.string.Fossilized_Fish,R.string.Fossilized_Fish_flavor,R.drawable.fossil_prop_13),
  Fossilized_Drake(R.string.Fossilized_Drake,R.string.Fossilized_Drake_flavor,R.drawable.fossil_prop_14),
  Fossilized_Dino(R.string.Fossilized_Dino,R.string.Fossilized_Dino_flavor,R.drawable.fossil_prop_15),
}

enum class SwapProps(val nameResId: Int, val flavorResId: Int, val imageResId: Int){
  Red_Shard(R.string.Red_Shard,R.string.Red_Shard_flavor,R.drawable.swap_prop_1),
  Blue_Shard(R.string.Blue_Shard,R.string.Blue_Shard_flavor,R.drawable.swap_prop_2),
  Yellow_Shard(R.string.Yellow_Shard,R.string.Yellow_Shard_flavor,R.drawable.swap_prop_3),
  Green_Shard(R.string.Green_Shard,R.string.Green_Shard_flavor,R.drawable.swap_prop_4),
  Shoal_Salt(R.string.Shoal_Salt,R.string.Shoal_Salt_flavor,R.drawable.swap_prop_5),
  Shoal_Shell(R.string.Shoal_Shell,R.string.Shoal_Shell_flavor,R.drawable.swap_prop_6),
  Heart_Scale(R.string.Heart_Scale,R.string.Heart_Scale_flavor,R.drawable.swap_prop_7),
  Galarica_Twig(R.string.Galarica_Twig,R.string.Galarica_Twig_flavor,R.drawable.swap_prop_8),
  Armorite_Ore(R.string.Armorite_Ore,R.string.Armorite_Ore_flavor,R.drawable.swap_prop_9),
  Dynite_Ore(R.string.Dynite_Ore,R.string.Dynite_Ore_flavor,R.drawable.swap_prop_10),
  Mysterious_Shard_S(R.string.Mysterious_Shard_S,R.string.Mysterious_Shard_S_flavor,R.drawable.swap_prop_11),
  Mysterious_Shard_L(R.string.Mysterious_Shard_L,R.string.Mysterious_Shard_L_flavor,R.drawable.swap_prop_12),
}

enum class CarryIIProps(val nameResId: Int, val flavorResId: Int, val imageResId: Int){
  Bright_Powder(R.string.Bright_Powder,R.string.Bright_Powder_flavor,R.drawable.carry_ii_prop_1),
  Exp_Share(R.string.Exp_Share,R.string.Exp_Share_flavor,R.drawable.carry_ii_prop_2),
  Quick_Claw(R.string.Quick_Claw,R.string.Quick_Claw_flavor,R.drawable.carry_ii_prop_3),
  Kings_Rock(R.string.Kings_Rock,R.string.Kings_Rock_flavor,R.drawable.carry_ii_prop_4),
  Silver_Powder(R.string.Silver_Powder,R.string.Silver_Powder_flavor,R.drawable.carry_ii_prop_5),
  Amulet_Coin(R.string.Amulet_Coin,R.string.Amulet_Coin_flavor,R.drawable.carry_ii_prop_6),
  Cleanse_Tag(R.string.Cleanse_Tag,R.string.Cleanse_Tag_flavor,R.drawable.carry_ii_prop_7),
  Smoke_Ball(R.string.Smoke_Ball,R.string.Smoke_Ball_flavor,R.drawable.carry_ii_prop_8),
  Everstone(R.string.Everstone,R.string.Everstone_flavor,R.drawable.carry_ii_prop_9),
  Focus_Band(R.string.Focus_Band,R.string.Focus_Band_flavor,R.drawable.carry_ii_prop_10),
  Lucky_Egg(R.string.Lucky_Egg,R.string.Lucky_Egg_flavor,R.drawable.carry_ii_prop_11),
  Scope_Lens(R.string.Scope_Lens,R.string.Scope_Lens_flavor,R.drawable.carry_ii_prop_12),
  Metal_Coat(R.string.Metal_Coat,R.string.Metal_Coat_flavor,R.drawable.carry_ii_prop_13),
  Leftovers(R.string.Leftovers,R.string.Leftovers_flavor,R.drawable.carry_ii_prop_14),
  Dragon_Scale(R.string.Dragon_Scale,R.string.Dragon_Scale_flavor,R.drawable.carry_ii_prop_15),
  Light_Ball(R.string.Light_Ball,R.string.Light_Ball_flavor,R.drawable.carry_ii_prop_16),
  Soft_Sand(R.string.Soft_Sand,R.string.Soft_Sand_flavor,R.drawable.carry_ii_prop_17),
  Hard_Stone(R.string.Hard_Stone,R.string.Hard_Stone_flavor,R.drawable.carry_ii_prop_18),
  Miracle_Seed(R.string.Miracle_Seed,R.string.Miracle_Seed_flavor,R.drawable.carry_ii_prop_19),
  Black_Glasses(R.string.Black_Glasses,R.string.Black_Glasses_flavor,R.drawable.carry_ii_prop_20),
  Black_Belt(R.string.Black_Belt,R.string.Black_Belt_flavor,R.drawable.carry_ii_prop_21),
  Magnet_(R.string.Magnet_,R.string.Magnet__flavor,R.drawable.carry_ii_prop_22),
  Mystic_Water(R.string.Mystic_Water,R.string.Mystic_Water_flavor,R.drawable.carry_ii_prop_23),
  Sharp_Beak(R.string.Sharp_Beak,R.string.Sharp_Beak_flavor,R.drawable.carry_ii_prop_24),
  Poison_Barb(R.string.Poison_Barb,R.string.Poison_Barb_flavor,R.drawable.carry_ii_prop_25),
  NeverMelt_Ice(R.string.NeverMelt_Ice,R.string.NeverMelt_Ice_flavor,R.drawable.carry_ii_prop_26),
  Spell_Tag(R.string.Spell_Tag,R.string.Spell_Tag_flavor,R.drawable.carry_ii_prop_27),
  Twisted_Spoon(R.string.Twisted_Spoon,R.string.Twisted_Spoon_flavor,R.drawable.carry_ii_prop_28),
  Charcoal(R.string.Charcoal,R.string.Charcoal_flavor,R.drawable.carry_ii_prop_29),
  Dragon_Fang(R.string.Dragon_Fang,R.string.Dragon_Fang_flavor,R.drawable.carry_ii_prop_30),
  Pink_Bow(R.string.Pink_Bow,R.string.Pink_Bow_flavor,R.drawable.carry_ii_prop_31),
  Polkadot_Bow(R.string.Polkadot_Bow,R.string.Polkadot_Bow_flavor,R.drawable.carry_ii_prop_32),
  Berserk_Gene(R.string.Berserk_Gene,R.string.Berserk_Gene_flavor,R.drawable.carry_ii_prop_33),
  Up_Grade(R.string.Up_Grade,R.string.Up_Grade_flavor,R.drawable.carry_ii_prop_34),
  Lucky_Punch(R.string.Lucky_Punch,R.string.Lucky_Punch_flavor,R.drawable.carry_ii_prop_35),
  Metal_Powder(R.string.Metal_Powder,R.string.Metal_Powder_flavor,R.drawable.carry_ii_prop_36),
  Thick_Club(R.string.Thick_Club,R.string.Thick_Club_flavor,R.drawable.carry_ii_prop_37),
  Stick(R.string.Stick,R.string.Stick_flavor,R.drawable.carry_ii_prop_38),
  Berry(R.string.Berry,R.string.Berry_flavor,R.drawable.carry_ii_prop_39),
  Gold_Berry(R.string.Gold_Berry,R.string.Gold_Berry_flavor,R.drawable.carry_ii_prop_40),
  PRZCureBerry(R.string.PRZCureBerry,R.string.PRZCureBerry_flavor,R.drawable.carry_ii_prop_41),
  PSNCureBerry(R.string.PSNCureBerry,R.string.PSNCureBerry_flavor,R.drawable.carry_ii_prop_42),
  Bitter_Berry(R.string.Bitter_Berry,R.string.Bitter_Berry_flavor,R.drawable.carry_ii_prop_43),
  Burnt_Berry(R.string.Burnt_Berry,R.string.Burnt_Berry_flavor,R.drawable.carry_ii_prop_44),
  Ice_Berry(R.string.Ice_Berry,R.string.Ice_Berry_flavor,R.drawable.carry_ii_prop_45),
  Mint_Berry(R.string.Mint_Berry,R.string.Mint_Berry_flavor,R.drawable.carry_ii_prop_46),
  MiracleBerry(R.string.MiracleBerry,R.string.MiracleBerry_flavor,R.drawable.carry_ii_prop_47),
  MysteryBerry(R.string.MysteryBerry,R.string.MysteryBerry_flavor,R.drawable.carry_ii_prop_48),
}

enum class CarryIIIProps(val nameResId: Int, val flavorResId: Int, val imageResId: Int){
  White_Herb(R.string.White_Herb,R.string.White_Herb_flavor,R.drawable.carry_iii_prop_1),
  Mental_Herb(R.string.Mental_Herb,R.string.Mental_Herb_flavor,R.drawable.carry_iii_prop_2),
  Macho_Brace(R.string.Macho_Brace,R.string.Macho_Brace_flavor,R.drawable.carry_iii_prop_3),
  Soothe_Bell(R.string.Soothe_Bell,R.string.Soothe_Bell_flavor,R.drawable.carry_iii_prop_4),
  Choice_Band(R.string.Choice_Band,R.string.Choice_Band_flavor,R.drawable.carry_iii_prop_5),
  Soul_Dew(R.string.Soul_Dew,R.string.Soul_Dew_flavor,R.drawable.carry_iii_prop_6),
  Deep_Sea_Tooth(R.string.Deep_Sea_Tooth,R.string.Deep_Sea_Tooth_flavor,R.drawable.carry_iii_prop_7),
  Deep_Sea_Scale(R.string.Deep_Sea_Scale,R.string.Deep_Sea_Scale_flavor,R.drawable.carry_iii_prop_8),
  Silk_Scarf(R.string.Silk_Scarf,R.string.Silk_Scarf_flavor,R.drawable.carry_iii_prop_9),
  Shell_Bell(R.string.Shell_Bell,R.string.Shell_Bell_flavor,R.drawable.carry_iii_prop_10),
  Sea_Incense(R.string.Sea_Incense,R.string.Sea_Incense_flavor,R.drawable.carry_iii_prop_11),
  Lax_Incense(R.string.Lax_Incense,R.string.Lax_Incense_flavor,R.drawable.carry_iii_prop_12),
  Red_Scarf(R.string.Red_Scarf,R.string.Red_Scarf_flavor,R.drawable.carry_iii_prop_13),
  Blue_Scarf(R.string.Blue_Scarf,R.string.Blue_Scarf_flavor,R.drawable.carry_iii_prop_14),
  Pink_Scarf(R.string.Pink_Scarf,R.string.Pink_Scarf_flavor,R.drawable.carry_iii_prop_15),
  Green_Scarf(R.string.Green_Scarf,R.string.Green_Scarf_flavor,R.drawable.carry_iii_prop_16),
  Yellow_Scarf(R.string.Yellow_Scarf,R.string.Yellow_Scarf_flavor,R.drawable.carry_iii_prop_17),
}

enum class CarryIVProps(val nameResId: Int, val flavorResId: Int, val imageResId: Int){
  Flame_Plate(R.string.Flame_Plate,R.string.Flame_Plate_flavor,R.drawable.carry_iv_prop_1),
  Splash_Plate(R.string.Splash_Plate,R.string.Splash_Plate_flavor,R.drawable.carry_iv_prop_2),
  Zap_Plate(R.string.Zap_Plate,R.string.Zap_Plate_flavor,R.drawable.carry_iv_prop_3),
  Meadow_Plate(R.string.Meadow_Plate,R.string.Meadow_Plate_flavor,R.drawable.carry_iv_prop_4),
  Icicle_Plate(R.string.Icicle_Plate,R.string.Icicle_Plate_flavor,R.drawable.carry_iv_prop_5),
  Fist_Plate(R.string.Fist_Plate,R.string.Fist_Plate_flavor,R.drawable.carry_iv_prop_6),
  Toxic_Plate(R.string.Toxic_Plate,R.string.Toxic_Plate_flavor,R.drawable.carry_iv_prop_7),
  Earth_Plate(R.string.Earth_Plate,R.string.Earth_Plate_flavor,R.drawable.carry_iv_prop_8),
  Sky_Plate(R.string.Sky_Plate,R.string.Sky_Plate_flavor,R.drawable.carry_iv_prop_9),
  Mind_Plate(R.string.Mind_Plate,R.string.Mind_Plate_flavor,R.drawable.carry_iv_prop_10),
  Insect_Plate(R.string.Insect_Plate,R.string.Insect_Plate_flavor,R.drawable.carry_iv_prop_11),
  Stone_Plate(R.string.Stone_Plate,R.string.Stone_Plate_flavor,R.drawable.carry_iv_prop_12),
  Spooky_Plate(R.string.Spooky_Plate,R.string.Spooky_Plate_flavor,R.drawable.carry_iv_prop_13),
  Draco_Plate(R.string.Draco_Plate,R.string.Draco_Plate_flavor,R.drawable.carry_iv_prop_14),
  Dread_Plate(R.string.Dread_Plate,R.string.Dread_Plate_flavor,R.drawable.carry_iv_prop_15),
  Iron_Plate(R.string.Iron_Plate,R.string.Iron_Plate_flavor,R.drawable.carry_iv_prop_16),
  Oval_Stone(R.string.Oval_Stone,R.string.Oval_Stone_flavor,R.drawable.carry_iv_prop_17),
  Adamant_Orb(R.string.Adamant_Orb,R.string.Adamant_Orb_flavor,R.drawable.carry_iv_prop_18),
  Lustrous_Orb(R.string.Lustrous_Orb,R.string.Lustrous_Orb_flavor,R.drawable.carry_iv_prop_19),
  Griseous_Orb(R.string.Griseous_Orb,R.string.Griseous_Orb_flavor,R.drawable.carry_iv_prop_20),
  Odd_Incense(R.string.Odd_Incense,R.string.Odd_Incense_flavor,R.drawable.carry_iv_prop_21),
  Rock_Incense(R.string.Rock_Incense,R.string.Rock_Incense_flavor,R.drawable.carry_iv_prop_22),
  Full_Incense(R.string.Full_Incense,R.string.Full_Incense_flavor,R.drawable.carry_iv_prop_23),
  Wave_Incense(R.string.Wave_Incense,R.string.Wave_Incense_flavor,R.drawable.carry_iv_prop_24),
  Rose_Incense(R.string.Rose_Incense,R.string.Rose_Incense_flavor,R.drawable.carry_iv_prop_25),
  Luck_Incense(R.string.Luck_Incense,R.string.Luck_Incense_flavor,R.drawable.carry_iv_prop_26),
  Pure_Incense(R.string.Pure_Incense,R.string.Pure_Incense_flavor,R.drawable.carry_iv_prop_27),
  Protector(R.string.Protector,R.string.Protector_flavor,R.drawable.carry_iv_prop_28),
  Electirizer(R.string.Electirizer,R.string.Electirizer_flavor,R.drawable.carry_iv_prop_29),
  Magmarizer(R.string.Magmarizer,R.string.Magmarizer_flavor,R.drawable.carry_iv_prop_30),
  Dubious_Disc(R.string.Dubious_Disc,R.string.Dubious_Disc_flavor,R.drawable.carry_iv_prop_31),
  Reaper_Cloth(R.string.Reaper_Cloth,R.string.Reaper_Cloth_flavor,R.drawable.carry_iv_prop_32),
  Razor_Claw(R.string.Razor_Claw,R.string.Razor_Claw_flavor,R.drawable.carry_iv_prop_33),
  Razor_Fang(R.string.Razor_Fang,R.string.Razor_Fang_flavor,R.drawable.carry_iv_prop_34),
  Wide_Lens(R.string.Wide_Lens,R.string.Wide_Lens_flavor,R.drawable.carry_iv_prop_35),
  Muscle_Band(R.string.Muscle_Band,R.string.Muscle_Band_flavor,R.drawable.carry_iv_prop_36),
  Wise_Glasses(R.string.Wise_Glasses,R.string.Wise_Glasses_flavor,R.drawable.carry_iv_prop_37),
  Expert_Belt(R.string.Expert_Belt,R.string.Expert_Belt_flavor,R.drawable.carry_iv_prop_38),
  Light_Clay(R.string.Light_Clay,R.string.Light_Clay_flavor,R.drawable.carry_iv_prop_39),
  Life_Orb(R.string.Life_Orb,R.string.Life_Orb_flavor,R.drawable.carry_iv_prop_40),
  Power_Herb(R.string.Power_Herb,R.string.Power_Herb_flavor,R.drawable.carry_iv_prop_41),
  Toxic_Orb(R.string.Toxic_Orb,R.string.Toxic_Orb_flavor,R.drawable.carry_iv_prop_42),
  Flame_Orb(R.string.Flame_Orb,R.string.Flame_Orb_flavor,R.drawable.carry_iv_prop_43),
  Quick_Powder(R.string.Quick_Powder,R.string.Quick_Powder_flavor,R.drawable.carry_iv_prop_44),
  Focus_Sash(R.string.Focus_Sash,R.string.Focus_Sash_flavor,R.drawable.carry_iv_prop_45),
  Zoom_Lens(R.string.Zoom_Lens,R.string.Zoom_Lens_flavor,R.drawable.carry_iv_prop_46),
  Metronome(R.string.Metronome,R.string.Metronome_flavor,R.drawable.carry_iv_prop_47),
  Iron_Ball(R.string.Iron_Ball,R.string.Iron_Ball_flavor,R.drawable.carry_iv_prop_48),
  Lagging_Tail(R.string.Lagging_Tail,R.string.Lagging_Tail_flavor,R.drawable.carry_iv_prop_49),
  Destiny_Knot(R.string.Destiny_Knot,R.string.Destiny_Knot_flavor,R.drawable.carry_iv_prop_50),
  Black_Sludge(R.string.Black_Sludge,R.string.Black_Sludge_flavor,R.drawable.carry_iv_prop_51),
  Icy_Rock(R.string.Icy_Rock,R.string.Icy_Rock_flavor,R.drawable.carry_iv_prop_52),
  Smooth_Rock(R.string.Smooth_Rock,R.string.Smooth_Rock_flavor,R.drawable.carry_iv_prop_53),
  Heat_Rock(R.string.Heat_Rock,R.string.Heat_Rock_flavor,R.drawable.carry_iv_prop_54),
  Damp_Rock(R.string.Damp_Rock,R.string.Damp_Rock_flavor,R.drawable.carry_iv_prop_55),
  Grip_Claw(R.string.Grip_Claw,R.string.Grip_Claw_flavor,R.drawable.carry_iv_prop_56),
  Choice_Scarf(R.string.Choice_Scarf,R.string.Choice_Scarf_flavor,R.drawable.carry_iv_prop_57),
  Sticky_Barb(R.string.Sticky_Barb,R.string.Sticky_Barb_flavor,R.drawable.carry_iv_prop_58),
  Power_Bracer(R.string.Power_Bracer,R.string.Power_Bracer_flavor,R.drawable.carry_iv_prop_59),
  Power_Belt(R.string.Power_Belt,R.string.Power_Belt_flavor,R.drawable.carry_iv_prop_60),  Rusted_Sword(R.string.Rusted_Sword,R.string.Rusted_Sword_flavor,R.drawable.carry_viii_prop_1),
  Power_Lens(R.string.Power_Lens,R.string.Power_Lens_flavor,R.drawable.carry_iv_prop_61),
  Power_Band(R.string.Power_Band,R.string.Power_Band_flavor,R.drawable.carry_iv_prop_62),
  Power_Anklet(R.string.Power_Anklet,R.string.Power_Anklet_flavor,R.drawable.carry_iv_prop_63),
  Power_Weight(R.string.Power_Weight,R.string.Power_Weight_flavor,R.drawable.carry_iv_prop_64),
  Shed_Shell(R.string.Shed_Shell,R.string.Shed_Shell_flavor,R.drawable.carry_iv_prop_65),
  Big_Root(R.string.Big_Root,R.string.Big_Root_flavor,R.drawable.carry_iv_prop_66),
  Choice_Specs(R.string.Choice_Specs,R.string.Choice_Specs_flavor,R.drawable.carry_iv_prop_67),
}

enum class CarryVProps(val nameResId: Int, val flavorResId: Int, val imageResId: Int){
  Douse_Drive(R.string.Douse_Drive, R.string.Douse_Drive_flavor,R.drawable.carry_v_prop_1),
  Shock_Drive(R.string.Shock_Drive,R.string.Shock_Drive_flavor,R.drawable.carry_v_prop_2),
  Burn_Drive(R.string.Burn_Drive, R.string.Burn_Drive_flavor,R.drawable.carry_v_prop_3),
  Chill_Drive(R.string.Chill_Drive,R.string.Chill_Drive_flavor,R.drawable.carry_v_prop_4),
  Prism_Scale(R.string.Prism_Scale,R.string.Prism_Scale_flavor,R.drawable.carry_v_prop_5),
  Eviolite(R.string.Eviolite,R.string.Eviolite_flavor,R.drawable.carry_v_prop_6),
  Float_Stone(R.string.Float_Stone,R.string.Float_Stone_flavor,R.drawable.carry_v_prop_7),
  Rocky_Helmet(R.string.Rocky_Helmet,R.string.Rocky_Helmet_flavor,R.drawable.carry_v_prop_8),
  Air_Balloon(R.string.Air_Balloon,R.string.Air_Balloon_flavor,R.drawable.carry_v_prop_9),
  Red_Card(R.string.Red_Card,R.string.Red_Card_flavor,R.drawable.carry_v_prop_10),
  Ring_Target(R.string.Ring_Target,R.string.Ring_Target_flavor,R.drawable.carry_v_prop_11),
  Binding_Band(R.string.Binding_Band,R.string.Binding_Band_flavor,R.drawable.carry_v_prop_12),
  Absorb_Bulb(R.string.Absorb_Bulb,R.string.Absorb_Bulb_flavor,R.drawable.carry_v_prop_13),
  Cell_Battery(R.string.Cell_Battery,R.string.Cell_Battery_flavor,R.drawable.carry_v_prop_14),
  Eject_Button(R.string.Eject_Button,R.string.Eject_Button_flavor,R.drawable.carry_v_prop_15),
  Fire_Gem(R.string.Fire_Gem,R.string.Fire_Gem_flavor,R.drawable.carry_v_prop_16),
  Water_Gem(R.string.Water_Gem,R.string.Water_Gem_flavor,R.drawable.carry_v_prop_17),
  Electric_Gem(R.string.Electric_Gem,R.string.Electric_Gem_flavor,R.drawable.carry_v_prop_18),
  Grass_Gem(R.string.Grass_Gem,R.string.Grass_Gem_flavor,R.drawable.carry_v_prop_19),
  Ice_Gem(R.string.Ice_Gem,R.string.Ice_Gem_flavor,R.drawable.carry_v_prop_20),
  Fighting_Gem(R.string.Fighting_Gem,R.string.Fighting_Gem_flavor,R.drawable.carry_v_prop_21),
  Poison_Gem(R.string.Poison_Gem,R.string.Poison_Gem_flavor,R.drawable.carry_v_prop_22),
  Ground_Gem(R.string.Ground_Gem,R.string.Ground_Gem_flavor,R.drawable.carry_v_prop_23),
  Flying_Gem(R.string.Flying_Gem,R.string.Flying_Gem_flavor,R.drawable.carry_v_prop_24),
  Psychic_Gem(R.string.Psychic_Gem,R.string.Psychic_Gem_flavor,R.drawable.carry_v_prop_25),
  Bug_Gem(R.string.Bug_Gem,R.string.Bug_Gem_flavor,R.drawable.carry_v_prop_26),
  Rock_Gem(R.string.Rock_Gem,R.string.Rock_Gem_flavor,R.drawable.carry_v_prop_27),
  Ghost_Gem(R.string.Ghost_Gem,R.string.Ghost_Gem_flavor,R.drawable.carry_v_prop_28),
  Dragon_Gem(R.string.Dragon_Gem,R.string.Dragon_Gem_flavor,R.drawable.carry_v_prop_29),
  Dark_Gem(R.string.Dark_Gem,R.string.Dark_Gem_flavor,R.drawable.carry_v_prop_30),
  Steel_Gem(R.string.Steel_Gem,R.string.Steel_Gem_flavor,R.drawable.carry_v_prop_31),
  Normal_Gem(R.string.Normal_Gem,R.string.Normal_Gem_flavor,R.drawable.carry_v_prop_32)
}

enum class CarryVIProps(val nameResId: Int, val flavorResId: Int, val imageResId: Int){
  Weakness_Policy(R.string.Weakness_Policy,R.string.Weakness_Policy_flavor,R.drawable.carry_vi_prop_1),
  Assault_Vest(R.string.Assault_Vest,R.string.Assault_Vest_flavor,R.drawable.carry_vi_prop_2),
  Pixie_Plate(R.string.Pixie_Plate,R.string.Pixie_Plate_flavor,R.drawable.carry_vi_prop_3),
  Fairy_Gem(R.string.Fairy_Gem,R.string.Fairy_Gem_flavor,R.drawable.carry_vi_prop_4),
  Whipped_Dream(R.string.Whipped_Dream,R.string.Whipped_Dream_flavor,R.drawable.carry_vi_prop_5),
  Sachet(R.string.Sachet,R.string.Sachet_flavor,R.drawable.carry_vi_prop_6),
  Luminous_Moss(R.string.Luminous_Moss,R.string.Luminous_Moss_flavor,R.drawable.carry_vi_prop_7),
  Snowball(R.string.Snowball,R.string.Snowball_flavor,R.drawable.carry_vi_prop_8),
  Safety_Goggles(R.string.Safety_Goggles,R.string.Safety_Goggles_flavor,R.drawable.carry_vi_prop_9),
  Venusaurite(R.string.Venusaurite,R.string.Venusaurite_flavor,R.drawable.carry_vi_prop_10),
  Charizardite_X(R.string.Charizardite_X,R.string.Charizardite_X_flavor,R.drawable.carry_vi_prop_11),
  Charizardite_Y(R.string.Charizardite_Y,R.string.Charizardite_Y_flavor,R.drawable.carry_vi_prop_12),
  Blastoisinite(R.string.Blastoisinite,R.string.Blastoisinite_flavor,R.drawable.carry_vi_prop_13),
  Beedrillite(R.string.Beedrillite,R.string.Beedrillite_flavor,R.drawable.carry_vi_prop_14),
  Pidgeotite(R.string.Pidgeotite,R.string.Pidgeotite_flavor,R.drawable.carry_vi_prop_15),
  Alakazite(R.string.Alakazite,R.string.Alakazite_flavor,R.drawable.carry_vi_prop_16),
  Slowbronite(R.string.Slowbronite,R.string.Slowbronite_flavor,R.drawable.carry_vi_prop_17),
  Gengarite(R.string.Gengarite,R.string.Gengarite_flavor,R.drawable.carry_vi_prop_18),
  Kangaskhanite(R.string.Kangaskhanite,R.string.Kangaskhanite_flavor,R.drawable.carry_vi_prop_19),
  Pinsirite(R.string.Pinsirite,R.string.Pinsirite_flavor,R.drawable.carry_vi_prop_20),
  Gyaradosite(R.string.Gyaradosite,R.string.Gyaradosite_flavor,R.drawable.carry_vi_prop_21),
  Aerodactylite(R.string.Aerodactylite,R.string.Aerodactylite_flavor,R.drawable.carry_vi_prop_22),
  Mewtwonite_X(R.string.Mewtwonite_X,R.string.Mewtwonite_X_flavor,R.drawable.carry_vi_prop_23),
  Mewtwonite_Y(R.string.Mewtwonite_Y,R.string.Mewtwonite_Y_flavor,R.drawable.carry_vi_prop_24),
  Ampharosite(R.string.Ampharosite,R.string.Ampharosite_flavor,R.drawable.carry_vi_prop_25),
  Steelixite(R.string.Steelixite,R.string.Steelixite_flavor,R.drawable.carry_vi_prop_26),
  Scizorite(R.string.Scizorite,R.string.Scizorite_flavor,R.drawable.carry_vi_prop_27),
  Heracronite(R.string.Heracronite,R.string.Heracronite_flavor,R.drawable.carry_vi_prop_28),
  Houndoominite(R.string.Houndoominite,R.string.Houndoominite_flavor,R.drawable.carry_vi_prop_29),
  Tyranitarite(R.string.Tyranitarite,R.string.Tyranitarite_flavor,R.drawable.carry_vi_prop_30),
  Sceptilite(R.string.Sceptilite,R.string.Sceptilite_flavor,R.drawable.carry_vi_prop_31),
  Blazikenite(R.string.Blazikenite,R.string.Blazikenite_flavor,R.drawable.carry_vi_prop_32),
  Swampertite(R.string.Swampertite,R.string.Swampertite_flavor,R.drawable.carry_vi_prop_33),
  Gardevoirite(R.string.Gardevoirite,R.string.Gardevoirite_flavor,R.drawable.carry_vi_prop_34),
  Sablenite(R.string.Sablenite,R.string.Sablenite_flavor,R.drawable.carry_vi_prop_35),
  Mawilite(R.string.Mawilite,R.string.Mawilite_flavor,R.drawable.carry_vi_prop_36),
  Aggronite(R.string.Aggronite,R.string.Aggronite_flavor,R.drawable.carry_vi_prop_37),
  Medichamite(R.string.Medichamite,R.string.Medichamite_flavor,R.drawable.carry_vi_prop_38),
  Manectite(R.string.Manectite,R.string.Manectite_flavor,R.drawable.carry_vi_prop_39),
  Sharpedonite(R.string.Sharpedonite,R.string.Sharpedonite_flavor,R.drawable.carry_vi_prop_40),
  Cameruptite(R.string.Cameruptite,R.string.Cameruptite_flavor,R.drawable.carry_vi_prop_41),
  Altarianite(R.string.Altarianite,R.string.Altarianite_flavor,R.drawable.carry_vi_prop_42),
  Banettite(R.string.Banettite,R.string.Banettite_flavor,R.drawable.carry_vi_prop_43),
  Absolite(R.string.Absolite,R.string.Absolite_flavor,R.drawable.carry_vi_prop_44),
  Glalitite(R.string.Glalitite,R.string.Glalitite_flavor,R.drawable.carry_vi_prop_45),
  Salamencite(R.string.Salamencite,R.string.Salamencite_flavor,R.drawable.carry_vi_prop_46),
  Metagrossite(R.string.Metagrossite,R.string.Metagrossite_flavor,R.drawable.carry_vi_prop_47),
  Latiasite(R.string.Latiasite,R.string.Latiasite_flavor,R.drawable.carry_vi_prop_48),
  Latiosite(R.string.Latiosite,R.string.Latiosite_flavor,R.drawable.carry_vi_prop_49),
  Lopunnite(R.string.Lopunnite,R.string.Lopunnite_flavor,R.drawable.carry_vi_prop_50),
  Lucarionite(R.string.Lucarionite,R.string.Lucarionite_flavor,R.drawable.carry_vi_prop_51),
  Garchompite(R.string.Garchompite,R.string.Garchompite_flavor,R.drawable.carry_vi_prop_52),
  Abomasite(R.string.Abomasite,R.string.Abomasite_flavor,R.drawable.carry_vi_prop_53),
  Galladite(R.string.Galladite,R.string.Galladite_flavor,R.drawable.carry_vi_prop_54),
  Audinite(R.string.Audinite,R.string.Audinite_flavor,R.drawable.carry_vi_prop_55),
  Diancite(R.string.Diancite,R.string.Diancite_flavor,R.drawable.carry_vi_prop_56),
  Red_Orb(R.string.Red_Orb,R.string.Red_Orb_flavor,R.drawable.carry_vi_prop_57),
  BlueOrb(R.string.BlueOrb,R.string.BlueOrb_flavor,R.drawable.carry_vi_prop_58),
}

enum class CarryVIIProps(val nameResId: Int, val flavorResId: Int, val imageResId: Int){
  Adrenaline_Orb(R.string.Adrenaline_Orb,R.string.Adrenaline_Orb_flavor,R.drawable.carry_vii_prop_1),
  Terrain_Extender(R.string.Terrain_Extender,R.string.Terrain_Extender_flavor,R.drawable.carry_vii_prop_2),
  Protective_Pads(R.string.Protective_Pads,R.string.Protective_Pads_flavor,R.drawable.carry_vii_prop_3),
  Electric_Seed(R.string.Electric_Seed,R.string.Electric_Seed_flavor,R.drawable.carry_vii_prop_4),
  Psychic_Seed(R.string.Psychic_Seed,R.string.Psychic_Seed_flavor,R.drawable.carry_vii_prop_5),
  Misty_Seed(R.string.Misty_Seed,R.string.Misty_Seed_flavor,R.drawable.carry_vii_prop_6),
  Grassy_Seed(R.string.Grassy_Seed,R.string.Grassy_Seed_flavor,R.drawable.carry_vii_prop_7),
  Fighting_Memory(R.string.Fighting_Memory,R.string.Fighting_Memory_flavor,R.drawable.carry_vii_prop_8),
  Flying_Memory(R.string.Flying_Memory,R.string.Flying_Memory_flavor,R.drawable.carry_vii_prop_9),
  Poison_Memory(R.string.Poison_Memory,R.string.Poison_Memory_flavor,R.drawable.carry_vii_prop_10),
  Ground_Memory(R.string.Ground_Memory,R.string.Ground_Memory_flavor,R.drawable.carry_vii_prop_11),
  Rock_Memory(R.string.Rock_Memory,R.string.Rock_Memory_flavor,R.drawable.carry_vii_prop_12),
  Bug_Memory(R.string.Bug_Memory,R.string.Bug_Memory_flavor,R.drawable.carry_vii_prop_13),
  Ghost_Memory(R.string.Ghost_Memory,R.string.Ghost_Memory_flavor,R.drawable.carry_vii_prop_14),
  Steel_Memory(R.string.Steel_Memory,R.string.Steel_Memory_flavor,R.drawable.carry_vii_prop_15),
  Fire_Memory(R.string.Fire_Memory,R.string.Fire_Memory_flavor,R.drawable.carry_vii_prop_16),
  Water_Memory(R.string.Water_Memory,R.string.Water_Memory_flavor,R.drawable.carry_vii_prop_17),
  Grass_Memory(R.string.Grass_Memory,R.string.Grass_Memory_flavor,R.drawable.carry_vii_prop_18),
  Electric_Memory(R.string.Electric_Memory,R.string.Electric_Memory_flavor,R.drawable.carry_vii_prop_19),
  Psychic_Memory(R.string.Psychic_Memory,R.string.Psychic_Memory_flavor,R.drawable.carry_vii_prop_20),
  Ice_Memory(R.string.Ice_Memory,R.string.Ice_Memory_flavor,R.drawable.carry_vii_prop_21),
  Dragon_Memory(R.string.Dragon_Memory,R.string.Dragon_Memory_flavor,R.drawable.carry_vii_prop_22),
  Dark_Memory(R.string.Dark_Memory,R.string.Dark_Memory_flavor,R.drawable.carry_vii_prop_23),
  Fairy_Memory(R.string.Fairy_Memory,R.string.Fairy_Memory_flavor,R.drawable.carry_vii_prop_24),
}

enum class CarryVIIIProps(val nameResId: Int, val flavorResId: Int, val imageResId: Int){
  Rusted_Sword(R.string.Rusted_Sword,R.string.Rusted_Sword_flavor,R.drawable.carry_viii_prop_1),
  Rusted_Shield(R.string.Rusted_Shield,R.string.Rusted_Shield_flavor,R.drawable.carry_viii_prop_2),
  Strawberry_Sweet(R.string.Strawberry_Sweet,R.string.Strawberry_Sweet_flavor,R.drawable.carry_viii_prop_3),
  Love_Sweet(R.string.Love_Sweet,R.string.Love_Sweet_flavor,R.drawable.carry_viii_prop_4),
  Berry_Sweet(R.string.Berry_Sweet,R.string.Berry_Sweet_flavor,R.drawable.carry_viii_prop_5),
  Clover_Sweet(R.string.Clover_Sweet,R.string.Clover_Sweet_flavor,R.drawable.carry_viii_prop_6),
  Flower_Sweet(R.string.Flower_Sweet,R.string.Flower_Sweet_flavor,R.drawable.carry_viii_prop_7),
  Star_Sweet(R.string.Star_Sweet,R.string.Star_Sweet_flavor,R.drawable.carry_viii_prop_8),
  Ribbon_Sweet(R.string.Ribbon_Sweet,R.string.Ribbon_Sweet_flavor,R.drawable.carry_viii_prop_9),
  Throat_Spray(R.string.Throat_Spray,R.string.Throat_Spray_flavor,R.drawable.carry_viii_prop_10),
  Eject_Pack(R.string.Eject_Pack,R.string.Eject_Pack_flavor,R.drawable.carry_viii_prop_11),
  Heavy_Duty_Boots(R.string.Heavy_Duty_Boots,R.string.Heavy_Duty_Boots_flavor,R.drawable.carry_viii_prop_12),
  Blunder_Policy(R.string.Blunder_Policy,R.string.Blunder_Policy_flavor,R.drawable.carry_viii_prop_13),
  Room_Service(R.string.Room_Service,R.string.Room_Service_flavor,R.drawable.carry_viii_prop_14),
  Utility_Umbrella(R.string.Utility_Umbrella,R.string.Utility_Umbrella_flavor,R.drawable.carry_viii_prop_15),
}

