package com.heinika.pokeg.ui.gameprops

import androidx.compose.ui.graphics.Color
import com.heinika.pokeg.R
import com.heinika.pokeg.ui.theme.*
import com.heinika.pokeg.utils.Generation

sealed class GameProps(val nameResId: Int, val flavorResId: Int, val imageResId: Int)

class EvolutionProp(val color: Color, nameResId: Int, flavorResId: Int, imageResId: Int) :
  GameProps(nameResId, flavorResId, imageResId)

val evolutionPropList = listOf(
  EvolutionProp(
    fireColor,
    R.string.Fire_Stone,
    R.string.Fire_Stone_flavor,
    R.drawable.evolution_prop_1
  ),
  EvolutionProp(
    electricColor,
    R.string.Thunder_Stone,
    R.string.Thunder_Stone_flavor,
    R.drawable.evolution_prop_2
  ),
  EvolutionProp(
    waterColor,
    R.string.Water_Stone,
    R.string.Water_Stone_flavor,
    R.drawable.evolution_prop_3
  ),
  EvolutionProp(
    grassColor,
    R.string.Leaf_Stone,
    R.string.Leaf_Stone_flavor,
    R.drawable.evolution_prop_4
  ),
  EvolutionProp(
    normalColor,
    R.string.Moon_Stone,
    R.string.Moon_Stone_flavor,
    R.drawable.evolution_prop_5
  ),
  EvolutionProp(
    rockColor,
    R.string.Sun_Stone,
    R.string.Sun_Stone_flavor,
    R.drawable.evolution_prop_6
  ),
  EvolutionProp(
    fairyColor,
    R.string.Shiny_Stone,
    R.string.Shiny_Stone_flavor,
    R.drawable.evolution_prop_7
  ),
  EvolutionProp(
    darkColor,
    R.string.Dusk_Stone,
    R.string.Dusk_Stone_flavor,
    R.drawable.evolution_prop_8
  ),
  EvolutionProp(
    steelColor,
    R.string.Dawn_Stone,
    R.string.Dawn_Stone_flavor,
    R.drawable.evolution_prop_9
  ),
  EvolutionProp(
    iceColor,
    R.string.Ice_Stone,
    R.string.Ice_Stone_flavor,
    R.drawable.evolution_prop_10
  ),
  EvolutionProp(
    Color.Red,
    R.string.Sweet_Apple,
    R.string.Sweet_Apple_flavor,
    R.drawable.evolution_prop_11
  ),
  EvolutionProp(
    grassColor,
    R.string.Tart_Apple,
    R.string.Tart_Apple_flavor,
    R.drawable.evolution_prop_12
  ),
  EvolutionProp(
    bugColor,
    R.string.Cracked_Pot,
    R.string.Cracked_Pot_flavor,
    R.drawable.evolution_prop_13
  ),
  EvolutionProp(
    dragonColor,
    R.string.Chipped_Pot,
    R.string.Chipped_Pot_flavor,
    R.drawable.evolution_prop_14
  ),
  EvolutionProp(
    psychicColor,
    R.string.Galarica_Cuff,
    R.string.Galarica_Cuff_flavor,
    R.drawable.evolution_prop_15
  ),
  EvolutionProp(
    grassColor,
    R.string.Galarica_Wreath,
    R.string.Galarica_Wreath_flavor,
    R.drawable.evolution_prop_16
  )
)

class BattleProp(nameResId: Int, flavorResId: Int, imageResId: Int) :
  GameProps(nameResId, flavorResId, imageResId)

val battlePropList = listOf(
  BattleProp(R.string.Guard_Spec, R.string.Guard_Spec_flavor, R.drawable.battle_prop_1),
  BattleProp(R.string.Dire_Hit, R.string.Dire_Hit_flavor, R.drawable.battle_prop_2),
  BattleProp(R.string.X_Attack, R.string.X_Attack_flavor, R.drawable.battle_prop_3),
  BattleProp(R.string.X_Defense, R.string.X_Defense_flavor, R.drawable.battle_prop_4),
  BattleProp(R.string.X_Speed, R.string.X_Speed_flavor, R.drawable.battle_prop_5),
  BattleProp(R.string.X_Accuracy, R.string.X_Accuracy_flavor, R.drawable.battle_prop_6),
  BattleProp(R.string.X_Sp_Atk, R.string.X_Sp_Atk_flavor, R.drawable.battle_prop_7),
  BattleProp(R.string.X_Sp_Def, R.string.X_Sp_Def_flavor, R.drawable.battle_prop_8),
  BattleProp(R.string.Poké_Doll, R.string.Poké_Doll_flavor, R.drawable.battle_prop_9),
  BattleProp(R.string.Fluffy_Tail, R.string.Fluffy_Tail_flavor, R.drawable.battle_prop_10),
  BattleProp(R.string.Poké_Toy, R.string.Poké_Toy_flavor, R.drawable.battle_prop_11),
  BattleProp(R.string.Max_Mushrooms, R.string.Max_Mushrooms_flavor, R.drawable.battle_prop_12),
)

class RoToProp(nameResId: Int, flavorResId: Int, imageResId: Int) :
  GameProps(nameResId, flavorResId, imageResId)

val rotoList = listOf(
  RoToProp(R.string.Roto_Hatch, R.string.Roto_Hatch_flavor, R.drawable.roto_prop_1),
  RoToProp(R.string.Roto_Bargain, R.string.Roto_Bargain_flavor, R.drawable.roto_prop_2),
  RoToProp(R.string.Roto_Prize_Money, R.string.Roto_Prize_Money_flavor, R.drawable.roto_prop_3),
  RoToProp(R.string.Roto_Exp_Points, R.string.Roto_Exp_Points_flavor, R.drawable.roto_prop_4),
  RoToProp(R.string.Roto_Friendship, R.string.Roto_Friendship_flavor, R.drawable.roto_prop_5),
  RoToProp(R.string.Roto_Encounter, R.string.Roto_Encounter_flavor, R.drawable.roto_prop_6),
  RoToProp(R.string.Roto_Stealth, R.string.Roto_Stealth_flavor, R.drawable.roto_prop_7),
  RoToProp(R.string.Roto_HP_Restore, R.string.Roto_HP_Restore_flavor, R.drawable.roto_prop_8),
  RoToProp(R.string.Roto_PP_Restore, R.string.Roto_PP_Restore_flavor, R.drawable.roto_prop_9),
  RoToProp(R.string.Roto_Boost, R.string.Roto_Boost_flavor, R.drawable.roto_prop_10),
  RoToProp(R.string.Roto_Catch, R.string.Roto_Catch_flavor, R.drawable.roto_prop_11),
)


class RecoveryProp(nameResId: Int, flavorResId: Int, imageResId: Int) :
  GameProps(nameResId, flavorResId, imageResId)

val recoveryPropList = listOf(
  RecoveryProp(R.string.Potion, R.string.Potion_flavor, R.drawable.recovery_prop_1),
  RecoveryProp(R.string.Antidote, R.string.Antidote_flavor, R.drawable.recovery_prop_2),
  RecoveryProp(R.string.Burn_Heal, R.string.Burn_Heal_flavor, R.drawable.recovery_prop_3),
  RecoveryProp(R.string.Ice_Heal, R.string.Ice_Heal_flavor, R.drawable.recovery_prop_4),
  RecoveryProp(R.string.Awakening, R.string.Awakening_flavor, R.drawable.recovery_prop_5),
  RecoveryProp(R.string.Paralyze_Heal, R.string.Paralyze_Heal_flavor, R.drawable.recovery_prop_6),
  RecoveryProp(R.string.Full_Restore, R.string.Full_Restore_flavor, R.drawable.recovery_prop_7),
  RecoveryProp(R.string.Max_Potion, R.string.Max_Potion_flavor, R.drawable.recovery_prop_8),
  RecoveryProp(R.string.Hyper_Potion, R.string.Hyper_Potion_flavor, R.drawable.recovery_prop_9),
  RecoveryProp(R.string.Super_Potion, R.string.Super_Potion_flavor, R.drawable.recovery_prop_10),
  RecoveryProp(R.string.Full_Heal, R.string.Full_Heal_flavor, R.drawable.recovery_prop_11),
  RecoveryProp(R.string.Revive, R.string.Revive_flavor, R.drawable.recovery_prop_12),
  RecoveryProp(R.string.Max_Revive, R.string.Max_Revive_flavor, R.drawable.recovery_prop_13),
  RecoveryProp(R.string.Fresh_Water, R.string.Fresh_Water_flavor, R.drawable.recovery_prop_14),
  RecoveryProp(R.string.Soda_Pop, R.string.Soda_Pop_flavor, R.drawable.recovery_prop_15),
  RecoveryProp(R.string.Lemonade, R.string.Lemonade_flavor, R.drawable.recovery_prop_16),
  RecoveryProp(R.string.Moomoo_Milk, R.string.Moomoo_Milk_flavor, R.drawable.recovery_prop_17),
  RecoveryProp(R.string.Energy_Powder, R.string.Energy_Powder_flavor, R.drawable.recovery_prop_18),
  RecoveryProp(R.string.Energy_Root, R.string.Energy_Root_flavor, R.drawable.recovery_prop_19),
  RecoveryProp(R.string.Heal_Powder, R.string.Heal_Powder_flavor, R.drawable.recovery_prop_20),
  RecoveryProp(R.string.Revival_Herb, R.string.Revival_Herb_flavor, R.drawable.recovery_prop_21),
  RecoveryProp(R.string.Ether, R.string.Ether_flavor, R.drawable.recovery_prop_22),
  RecoveryProp(R.string.Max_Ether, R.string.Max_Ether_flavor, R.drawable.recovery_prop_23),
  RecoveryProp(R.string.Elixir, R.string.Elixir_flavor, R.drawable.recovery_prop_24),
  RecoveryProp(R.string.Max_Elixir, R.string.Max_Elixir_flavor, R.drawable.recovery_prop_25),
  RecoveryProp(R.string.Lava_Cookie, R.string.Lava_Cookie_flavor, R.drawable.recovery_prop_26),
  RecoveryProp(R.string.Berry_Juice, R.string.Berry_Juice_flavor, R.drawable.recovery_prop_27),
  RecoveryProp(R.string.Sacred_Ash, R.string.Sacred_Ash_flavor, R.drawable.recovery_prop_28),
  RecoveryProp(R.string.Rage_Candy_Bar, R.string.Rage_Candy_Bar_flavor, R.drawable.recovery_prop_29),
  RecoveryProp(R.string.Old_Gateau, R.string.Old_Gateau_flavor, R.drawable.recovery_prop_30),
  RecoveryProp(R.string.Sweet_Heart, R.string.Sweet_Heart_flavor, R.drawable.recovery_prop_31),
  RecoveryProp(R.string.Casteliacone, R.string.Casteliacone_flavor, R.drawable.recovery_prop_32),
  RecoveryProp(R.string.Lumiose_Galette, R.string.Lumiose_Galette_flavor, R.drawable.recovery_prop_33),
  RecoveryProp(R.string.Shalour_Sable, R.string.Shalour_Sable_flavor, R.drawable.recovery_prop_34),
  RecoveryProp(R.string.Big_Malasada, R.string.Big_Malasada_flavor, R.drawable.recovery_prop_35),
  RecoveryProp(R.string.Pewter_Crunchies, R.string.Pewter_Crunchies_flavor, R.drawable.recovery_prop_36),
  RecoveryProp(R.string.Max_Honey, R.string.Max_Honey_flavor, R.drawable.recovery_prop_37),
)

class Apricorn(nameResId: Int, flavorResId: Int, imageResId: Int) :
  GameProps(nameResId, flavorResId, imageResId)

val apricornList = listOf(
  Apricorn(R.string.Red_Apricorn, R.string.Red_Apricorn_flavor, R.drawable.apricorn_prop_1),
  Apricorn(R.string.Blue_Apricorn, R.string.Blue_Apricorn_flavor, R.drawable.apricorn_prop_2),
  Apricorn(R.string.Yellow_Apricorn, R.string.Yellow_Apricorn_flavor, R.drawable.apricorn_prop_3),
  Apricorn(R.string.Green_Apricorn, R.string.Green_Apricorn_flavor, R.drawable.apricorn_prop_4),
  Apricorn(R.string.Pink_Apricorn, R.string.Pink_Apricorn_flavor, R.drawable.apricorn_prop_5),
  Apricorn(R.string.White_Apricorn, R.string.White_Apricorn_flavor, R.drawable.apricorn_prop_6),
  Apricorn(R.string.Black_Apricorn, R.string.Black_Apricorn_flavor, R.drawable.apricorn_prop_7)
)

class PreciousProp(nameResId: Int, flavorResId: Int, imageResId: Int) :
  GameProps(nameResId, flavorResId, imageResId)

val preciousPropList = listOf(
  PreciousProp(R.string.Tiny_Mushroom, R.string.Tiny_Mushroom_flavor, R.drawable.precious_prop_1),
  PreciousProp(R.string.Big_Mushroom, R.string.Big_Mushroom_flavor, R.drawable.precious_prop_2),
  PreciousProp(R.string.Pearl, R.string.Pearl_flavor, R.drawable.precious_prop_3),
  PreciousProp(R.string.Big_Pearl, R.string.Big_Pearl_flavor, R.drawable.precious_prop_4),
  PreciousProp(R.string.Stardust, R.string.Stardust_flavor, R.drawable.precious_prop_5),
  PreciousProp(R.string.Star_Piece, R.string.Star_Piece_flavor, R.drawable.precious_prop_6),
  PreciousProp(R.string.Gold_Leaf, R.string.Gold_Leaf_flavor, R.drawable.precious_prop_7),
  PreciousProp(R.string.Silver_Leaf, R.string.Silver_Leaf_flavor, R.drawable.precious_prop_8),
  PreciousProp(R.string.Brick_Piece, R.string.Brick_Piece_flavor, R.drawable.precious_prop_9),
  PreciousProp(R.string.Nugget, R.string.Nugget_flavor, R.drawable.precious_prop_10),
  PreciousProp(R.string.Rare_Bone, R.string.Rare_Bone_flavor, R.drawable.precious_prop_11),
  PreciousProp(R.string.Pretty_Wing, R.string.Pretty_Wing_flavor, R.drawable.precious_prop_12),
  PreciousProp(R.string.Balm_Mushroom, R.string.Balm_Mushroom_flavor, R.drawable.precious_prop_13),
  PreciousProp(R.string.Big_Nugget, R.string.Big_Nugget_flavor, R.drawable.precious_prop_14),
  PreciousProp(R.string.Pearl_String, R.string.Pearl_String_flavor, R.drawable.precious_prop_15),
  PreciousProp(R.string.Comet_Shard, R.string.Comet_Shard_flavor, R.drawable.precious_prop_16),
  PreciousProp(R.string.Relic_Copper, R.string.Relic_Copper_flavor, R.drawable.precious_prop_17),
  PreciousProp(R.string.Relic_Silver, R.string.Relic_Silver_flavor, R.drawable.precious_prop_18),
  PreciousProp(R.string.Relic_Gold, R.string.Relic_Gold_flavor, R.drawable.precious_prop_19),
  PreciousProp(R.string.Relic_Vase, R.string.Relic_Vase_flavor, R.drawable.precious_prop_20),
  PreciousProp(R.string.Relic_Band, R.string.Relic_Band_flavor, R.drawable.precious_prop_21),
  PreciousProp(R.string.Relic_Statue, R.string.Relic_Statue_flavor, R.drawable.precious_prop_22),
  PreciousProp(R.string.Relic_Crown, R.string.Relic_Crown_flavor, R.drawable.precious_prop_23),
  PreciousProp(R.string.Strange_Souvenir, R.string.Strange_Souvenir_flavor, R.drawable.precious_prop_24),
  PreciousProp(R.string.Bottle_Cap, R.string.Bottle_Cap_flavor, R.drawable.precious_prop_25),
  PreciousProp(R.string.Gold_Bottle, R.string.Gold_Bottle_flavor, R.drawable.precious_prop_26),
  PreciousProp(R.string.Stretchy_Spring, R.string.Stretchy_Spring_flavor, R.drawable.precious_prop_27),
  PreciousProp(R.string.Chalky_Stone, R.string.Chalky_Stone_flavor, R.drawable.precious_prop_28),
  PreciousProp(R.string.Marble, R.string.Marble_flavor, R.drawable.precious_prop_29),
  PreciousProp(R.string.Lone_Earring, R.string.Lone_Earring_flavor, R.drawable.precious_prop_30),
  PreciousProp(R.string.Beach_Glass, R.string.Beach_Glass_flavor, R.drawable.precious_prop_31),
  PreciousProp(R.string.Polished_Mud, R.string.Polished_Mud_flavor, R.drawable.precious_prop_32),
  PreciousProp(R.string.Tropical_Shell, R.string.Tropical_Shell_flavor, R.drawable.precious_prop_33),

)

class ImportantProp(val gen: Generation, nameResId: Int, flavorResId: Int, imageResId: Int) :
  GameProps(nameResId, flavorResId, imageResId)

val importantIList = listOf(
  ImportantProp(Generation.GenerationI,R.string.Coin_Case1, R.string.Coin_Case1_flavor, R.drawable.important_i_prop_1),
  ImportantProp(Generation.GenerationI,R.string.Coin_Case2, R.string.Coin_Case2_flavor, R.drawable.important_i_prop_2),
  ImportantProp(Generation.GenerationI,R.string.Itemfinder, R.string.Itemfinder_flavor, R.drawable.important_i_prop_3),
  ImportantProp(Generation.GenerationI,R.string.Dowsing_MCHN1, R.string.Dowsing_MCHN1_flavor, R.drawable.important_i_prop_4),
  ImportantProp(Generation.GenerationI,R.string.Dowsing_MCHN2, R.string.Dowsing_MCHN2_flavor, R.drawable.important_i_prop_5),
  ImportantProp(Generation.GenerationI,R.string.Dowsing_Machine1, R.string.Dowsing_Machine1_flavor, R.drawable.important_i_prop_6),
  ImportantProp(Generation.GenerationI,R.string.Dowsing_Machine2, R.string.Dowsing_Machine2_flavor, R.drawable.important_i_prop_7),
  ImportantProp(Generation.GenerationI,R.string.Old_Rod1, R.string.Old_Rod1_flavor, R.drawable.important_i_prop_8),
  ImportantProp(Generation.GenerationI,R.string.Old_Rod2, R.string.Old_Rod2_flavor, R.drawable.important_i_prop_9),
  ImportantProp(Generation.GenerationI,R.string.Good_Rod1, R.string.Good_Rod1_flavor, R.drawable.important_i_prop_10),
  ImportantProp(Generation.GenerationI,R.string.Good_Rod2, R.string.Good_Rod2_flavor, R.drawable.important_i_prop_11),
  ImportantProp(Generation.GenerationI,R.string.Super_Rod1, R.string.Super_Rod1_flavor, R.drawable.important_i_prop_12),
  ImportantProp(Generation.GenerationI,R.string.Super_Rod2, R.string.Super_Rod2_flavor, R.drawable.important_i_prop_13),
  ImportantProp(Generation.GenerationI,R.string.SS_Ticket1, R.string.SS_Ticket1_flavor, R.drawable.important_i_prop_14),
  ImportantProp(Generation.GenerationI,R.string.SS_Ticket2, R.string.SS_Ticket2_flavor, R.drawable.important_i_prop_15),
  ImportantProp(Generation.GenerationI,R.string.SS_Ticket3, R.string.SS_Ticket3_flavor, R.drawable.important_i_prop_16),
  ImportantProp(Generation.GenerationI,R.string.Parcel1, R.string.Parcel1_flavor, R.drawable.important_i_prop_17),
  ImportantProp(Generation.GenerationI,R.string.Parcel2, R.string.Parcel2_flavor, R.drawable.important_i_prop_18),
  ImportantProp(Generation.GenerationI,R.string.Poké_Flute1, R.string.Poké_Flute1_flavor, R.drawable.important_i_prop_19),
  ImportantProp(Generation.GenerationI,R.string.Poké_Flute2, R.string.Poké_Flute2_flavor, R.drawable.important_i_prop_20),
  ImportantProp(Generation.GenerationI,R.string.Secret_Key1, R.string.Secret_Key1_flavor, R.drawable.important_i_prop_21),
  ImportantProp(Generation.GenerationI,R.string.Secret_Key2, R.string.Secret_Key2_flavor, R.drawable.important_i_prop_22),
  ImportantProp(Generation.GenerationI,R.string.Bike_Voucher, R.string.Bike_Voucher_flavor, R.drawable.important_i_prop_23),
  ImportantProp(Generation.GenerationI,R.string.Gold_Teeth1, R.string.Gold_Teeth1_flavor, R.drawable.important_i_prop_24),
  ImportantProp(Generation.GenerationI,R.string.Gold_Teeth2, R.string.Gold_Teeth2_flavor, R.drawable.important_i_prop_25),
  ImportantProp(Generation.GenerationI,R.string.Lift_Key1, R.string.Lift_Key1_flavor, R.drawable.important_i_prop_26),
  ImportantProp(Generation.GenerationI,R.string.Lift_Key2, R.string.Lift_Key2_flavor, R.drawable.important_i_prop_27),
  ImportantProp(Generation.GenerationI,R.string.Bicycle1, R.string.Bicycle1_flavor, R.drawable.important_i_prop_28),
  ImportantProp(Generation.GenerationI,R.string.Bicycle2, R.string.Bicycle2_flavor, R.drawable.important_i_prop_29),
  ImportantProp(Generation.GenerationI,R.string.Bicycle3, R.string.Bicycle3_flavor, R.drawable.important_i_prop_30),
  ImportantProp(Generation.GenerationI,R.string.Bicycle4, R.string.Bicycle4_flavor, R.drawable.important_i_prop_31),
  ImportantProp(Generation.GenerationI,R.string.Bicycle5, R.string.Bicycle5_flavor, R.drawable.important_i_prop_32),
  ImportantProp(Generation.GenerationI,R.string.Town_Map1, R.string.Town_Map1_flavor, R.drawable.important_i_prop_33),
  ImportantProp(Generation.GenerationI,R.string.Town_Map2, R.string.Town_Map2_flavor, R.drawable.important_i_prop_34),
  ImportantProp(Generation.GenerationI,R.string.Town_Map3, R.string.Town_Map3_flavor, R.drawable.important_i_prop_35),
  ImportantProp(Generation.GenerationI,R.string.Silph_Scope1, R.string.Silph_Scope1_flavor, R.drawable.important_i_prop_36),
  ImportantProp(Generation.GenerationI,R.string.Silph_Scope2, R.string.Silph_Scope2_flavor, R.drawable.important_i_prop_37),
  ImportantProp(Generation.GenerationI,R.string.Card_Key1, R.string.Card_Key1_flavor, R.drawable.important_i_prop_38),
  ImportantProp(Generation.GenerationI,R.string.Card_Key2, R.string.Card_Key2_flavor, R.drawable.important_i_prop_39),
)

val importantIIList = listOf(
  ImportantProp(Generation.GenerationII,R.string.GS_Ball, R.string.GS_Ball_flavor, R.drawable.important_ii_prop_1),
  ImportantProp(Generation.GenerationII,R.string.Egg_Ticket, R.string.Egg_Ticket_flavor, R.drawable.important_ii_prop_2),
  ImportantProp(Generation.GenerationII,R.string.Pass2, R.string.Pass2_flavor, R.drawable.important_ii_prop_3),
  ImportantProp(Generation.GenerationII,R.string.Clear_Bell, R.string.Clear_Bell_flavor, R.drawable.important_ii_prop_4),
  ImportantProp(Generation.GenerationII,R.string.Blue_Card, R.string.Blue_Card_flavor, R.drawable.important_ii_prop_5),
  ImportantProp(Generation.GenerationII,R.string.Squirtbottle1, R.string.Squirtbottle1_flavor, R.drawable.important_ii_prop_6),
  ImportantProp(Generation.GenerationII,R.string.Squirtbottle2, R.string.Squirtbottle2_flavor, R.drawable.important_ii_prop_7),
  ImportantProp(Generation.GenerationII,R.string.Red_Scale, R.string.Red_Scale_flavor, R.drawable.important_ii_prop_8),
  ImportantProp(Generation.GenerationII,R.string.Lost_Item1, R.string.Lost_Item1_flavor, R.drawable.important_ii_prop_9),
  ImportantProp(Generation.GenerationII,R.string.Lost_Item2, R.string.Lost_Item2_flavor, R.drawable.important_ii_prop_10),
  ImportantProp(Generation.GenerationII,R.string.Machine_Part, R.string.Machine_Part_flavor, R.drawable.important_ii_prop_11),
  ImportantProp(Generation.GenerationII,R.string.Basement_Key1, R.string.Basement_Key1_flavor, R.drawable.important_ii_prop_12),
  ImportantProp(Generation.GenerationII,R.string.Basement_Key2, R.string.Basement_Key2_flavor, R.drawable.important_ii_prop_13),
  ImportantProp(Generation.GenerationII,R.string.Silver_Wing1, R.string.Silver_Wing1_flavor, R.drawable.important_ii_prop_14),
  ImportantProp(Generation.GenerationII,R.string.Silver_Wing2, R.string.Silver_Wing2_flavor, R.drawable.important_ii_prop_15),
  ImportantProp(Generation.GenerationII,R.string.Rainbow_Wing, R.string.Rainbow_Wing_flavor, R.drawable.important_ii_prop_16),
  ImportantProp(Generation.GenerationII,R.string.Mystery_Egg, R.string.Mystery_Egg_flavor, R.drawable.important_ii_prop_17),
  ImportantProp(Generation.GenerationII,R.string.SecretPotion, R.string.SecretPotion_flavor, R.drawable.important_ii_prop_18),
)

val importantIIIList = listOf(
  ImportantProp(Generation.GenerationIII,R.string.Mach_Bike1, R.string.Mach_Bike1_flavor, R.drawable.important_iii_prop_1),
  ImportantProp(Generation.GenerationIII,R.string.Mach_Bike2, R.string.Mach_Bike2_flavor, R.drawable.important_iii_prop_2),
  ImportantProp(Generation.GenerationIII,R.string.Acro_Bike1, R.string.Acro_Bike1_flavor, R.drawable.important_iii_prop_3),
  ImportantProp(Generation.GenerationIII,R.string.Acro_Bike2, R.string.Acro_Bike2_flavor, R.drawable.important_iii_prop_4),
  ImportantProp(Generation.GenerationIII,R.string.Contest_Pass, R.string.Contest_Pass_flavor, R.drawable.important_iii_prop_5),
  ImportantProp(Generation.GenerationIII,R.string.Wailmer_Pail, R.string.Wailmer_Pail_flavor, R.drawable.important_iii_prop_6),
  ImportantProp(Generation.GenerationIII,R.string.Devon_Goods, R.string.Devon_Goods_flavor, R.drawable.important_iii_prop_7),
  ImportantProp(Generation.GenerationIII,R.string.Soot_Sack, R.string.Soot_Sack_flavor, R.drawable.important_iii_prop_8),
  ImportantProp(Generation.GenerationIII,R.string.Pokéblock_Case, R.string.Pokéblock_Case_flavor, R.drawable.important_iii_prop_9),
  ImportantProp(Generation.GenerationIII,R.string.Letter, R.string.Letter_flavor, R.drawable.important_iii_prop_10),
  ImportantProp(Generation.GenerationIII,R.string.Eon_Ticket1, R.string.Eon_Ticket1_flavor, R.drawable.important_iii_prop_11),
  ImportantProp(Generation.GenerationIII,R.string.Eon_Ticket2, R.string.Eon_Ticket2_flavor, R.drawable.important_iii_prop_12),
  ImportantProp(Generation.GenerationIII,R.string.Scanner1, R.string.Scanner1_flavor, R.drawable.important_iii_prop_13),
  ImportantProp(Generation.GenerationIII,R.string.Scanner2, R.string.Scanner2_flavor, R.drawable.important_iii_prop_14),
  ImportantProp(Generation.GenerationIII,R.string.Go_Goggles1, R.string.Go_Goggles1_flavor, R.drawable.important_iii_prop_15),
  ImportantProp(Generation.GenerationIII,R.string.Go_Goggles2, R.string.Go_Goggles2_flavor, R.drawable.important_iii_prop_16),
  ImportantProp(Generation.GenerationIII,R.string.Meteorite1, R.string.Meteorite1_flavor, R.drawable.important_iii_prop_17),
  ImportantProp(Generation.GenerationIII,R.string.Meteorite2, R.string.Meteorite2_flavor, R.drawable.important_iii_prop_18),
  ImportantProp(Generation.GenerationIII,R.string.Meteorite3, R.string.Meteorite3_flavor, R.drawable.important_iii_prop_19),
  ImportantProp(Generation.GenerationIII,R.string.Meteorite4, R.string.Meteorite4_flavor, R.drawable.important_iii_prop_20),
  ImportantProp(Generation.GenerationIII,R.string.Meteorite5, R.string.Meteorite5_flavor, R.drawable.important_iii_prop_21),
  ImportantProp(Generation.GenerationIII,R.string.Rm_1_Key1, R.string.Rm_1_Key1_flavor, R.drawable.important_iii_prop_22),
  ImportantProp(Generation.GenerationIII,R.string.Rm_1_Key2, R.string.Rm_1_Key2_flavor, R.drawable.important_iii_prop_23),
  ImportantProp(Generation.GenerationIII,R.string.Rm_2_Key1, R.string.Rm_2_Key1_flavor, R.drawable.important_iii_prop_24),
  ImportantProp(Generation.GenerationIII,R.string.Rm_2_Key2, R.string.Rm_2_Key2_flavor, R.drawable.important_iii_prop_25),
  ImportantProp(Generation.GenerationIII,R.string.Rm_4_Key1, R.string.Rm_4_Key1_flavor, R.drawable.important_iii_prop_26),
  ImportantProp(Generation.GenerationIII,R.string.Rm_4_Key2, R.string.Rm_4_Key2_flavor, R.drawable.important_iii_prop_27),
  ImportantProp(Generation.GenerationIII,R.string.Rm_6_Key1, R.string.Rm_6_Key1_flavor, R.drawable.important_iii_prop_28),
  ImportantProp(Generation.GenerationIII,R.string.Rm_6_Key2, R.string.Rm_6_Key2_flavor, R.drawable.important_iii_prop_29),
  ImportantProp(Generation.GenerationIII,R.string.Storage_Key1, R.string.Storage_Key1_flavor, R.drawable.important_iii_prop_30),
  ImportantProp(Generation.GenerationIII,R.string.Storage_Key2, R.string.Storage_Key2_flavor, R.drawable.important_iii_prop_31),
  ImportantProp(Generation.GenerationIII,R.string.Storage_Key3, R.string.Storage_Key3_flavor, R.drawable.important_iii_prop_32),
  ImportantProp(Generation.GenerationIII,R.string.Devon_Scope1, R.string.Devon_Scope1_flavor, R.drawable.important_iii_prop_33),
  ImportantProp(Generation.GenerationIII,R.string.Devon_Scope2, R.string.Devon_Scope2_flavor, R.drawable.important_iii_prop_34),
  ImportantProp(Generation.GenerationIII,R.string.Vs_Seeker, R.string.Vs_Seeker_flavor, R.drawable.important_iii_prop_35),
  ImportantProp(Generation.GenerationIII,R.string.Fame_Checker, R.string.Fame_Checker_flavor, R.drawable.important_iii_prop_36),
  ImportantProp(Generation.GenerationIII,R.string.TM_Case1, R.string.TM_Case1_flavor, R.drawable.important_iii_prop_37),
  ImportantProp(Generation.GenerationIII,R.string.TM_Case2, R.string.TM_Case2_flavor, R.drawable.important_iii_prop_38),
  ImportantProp(Generation.GenerationIII,R.string.Berry_Pouch, R.string.Berry_Pouch_flavor, R.drawable.important_iii_prop_39),
  ImportantProp(Generation.GenerationIII,R.string.Teachy_TV, R.string.Teachy_TV_flavor, R.drawable.important_iii_prop_40),
  ImportantProp(Generation.GenerationIII,R.string.Tri_Pass, R.string.Tri_Pass_flavor, R.drawable.important_iii_prop_41),
  ImportantProp(Generation.GenerationIII,R.string.Rainbow_Pass, R.string.Rainbow_Pass_flavor, R.drawable.important_iii_prop_42),
  ImportantProp(Generation.GenerationIII,R.string.Tea1, R.string.Tea1_flavor, R.drawable.important_iii_prop_43),
  ImportantProp(Generation.GenerationIII,R.string.Tea2, R.string.Tea2_flavor, R.drawable.important_iii_prop_44),
  ImportantProp(Generation.GenerationIII,R.string.MysticTicket, R.string.MysticTicket_flavor, R.drawable.important_iii_prop_45),
  ImportantProp(Generation.GenerationIII,R.string.AuroraTicket, R.string.AuroraTicket_flavor, R.drawable.important_iii_prop_46),
  ImportantProp(Generation.GenerationIII,R.string.Powder_Jar, R.string.Powder_Jar_flavor, R.drawable.important_iii_prop_47),
  ImportantProp(Generation.GenerationIII,R.string.Ruby, R.string.Ruby_flavor, R.drawable.important_iii_prop_48),
  ImportantProp(Generation.GenerationIII,R.string.Sapphire, R.string.Sapphire_flavor, R.drawable.important_iii_prop_49),
  ImportantProp(Generation.GenerationIII,R.string.Magma_Emblem, R.string.Magma_Emblem_flavor, R.drawable.important_iii_prop_50),
  ImportantProp(Generation.GenerationIII,R.string.Old_Sea_Map, R.string.Old_Sea_Map_flavor, R.drawable.important_iii_prop_51),
)

val importantIVList = listOf(
  ImportantProp(Generation.GenerationIV,R.string.Explorer_Kit, R.string.Explorer_Kit_flavor, R.drawable.important_iv_prop_1),
  ImportantProp(Generation.GenerationIV,R.string.Loot_Sack, R.string.Loot_Sack_flavor, R.drawable.important_iv_prop_2),
  ImportantProp(Generation.GenerationIV,R.string.Rule_Book, R.string.Rule_Book_flavor, R.drawable.important_iv_prop_3),
  ImportantProp(Generation.GenerationIV,R.string.Poké_Radar, R.string.Poké_Radar_flavor, R.drawable.important_iv_prop_4),
  ImportantProp(Generation.GenerationIV,R.string.Point_Card, R.string.Point_Card_flavor, R.drawable.important_iv_prop_5),
  ImportantProp(Generation.GenerationIV,R.string.Journal, R.string.Journal_flavor, R.drawable.important_iv_prop_6),
  ImportantProp(Generation.GenerationIV,R.string.Seal_Case, R.string.Seal_Case_flavor, R.drawable.important_iv_prop_7),
  ImportantProp(Generation.GenerationIV,R.string.Fashion_Case, R.string.Fashion_Case_flavor, R.drawable.important_iv_prop_8),
  ImportantProp(Generation.GenerationIV,R.string.Seal_Bag, R.string.Seal_Bag_flavor, R.drawable.important_iv_prop_9),
  ImportantProp(Generation.GenerationIV,R.string.Pal_Pad, R.string.Pal_Pad_flavor, R.drawable.important_iv_prop_10),
  ImportantProp(Generation.GenerationIV,R.string.Works_Key, R.string.Works_Key_flavor, R.drawable.important_iv_prop_11),
  ImportantProp(Generation.GenerationIV,R.string.Old_Charm, R.string.Old_Charm_flavor, R.drawable.important_iv_prop_12),
  ImportantProp(Generation.GenerationIV,R.string.Galactic_Key, R.string.Galactic_Key_flavor, R.drawable.important_iv_prop_13),
  ImportantProp(Generation.GenerationIV,R.string.Red_Chain, R.string.Red_Chain_flavor, R.drawable.important_iv_prop_14),
  ImportantProp(Generation.GenerationIV,R.string.Sprayduck, R.string.Sprayduck_flavor, R.drawable.important_iv_prop_15),
  ImportantProp(Generation.GenerationIV,R.string.Poffin_Case, R.string.Poffin_Case_flavor, R.drawable.important_iv_prop_16),
  ImportantProp(Generation.GenerationIV,R.string.Suite_Key, R.string.Suite_Key_flavor, R.drawable.important_iv_prop_17),
  ImportantProp(Generation.GenerationIV,R.string.Oak_s_Letter, R.string.Oak_s_Letter_flavor, R.drawable.important_iv_prop_18),
  ImportantProp(Generation.GenerationIV,R.string.Lunar_Wing, R.string.Lunar_Wing_flavor, R.drawable.important_iv_prop_19),
  ImportantProp(Generation.GenerationIV,R.string.Member_Card, R.string.Member_Card_flavor, R.drawable.important_iv_prop_20),
  ImportantProp(Generation.GenerationIV,R.string.Azure_Flute, R.string.Azure_Flute_flavor, R.drawable.important_iv_prop_21),
  ImportantProp(Generation.GenerationIV,R.string.Magma_Stone, R.string.Magma_Stone_flavor, R.drawable.important_iv_prop_22),
  ImportantProp(Generation.GenerationIV,R.string.Coupon_1, R.string.Coupon_1_flavor, R.drawable.important_iv_prop_23),
  ImportantProp(Generation.GenerationIV,R.string.Coupon_2, R.string.Coupon_2_flavor, R.drawable.important_iv_prop_24),
  ImportantProp(Generation.GenerationIV,R.string.Coupon_3, R.string.Coupon_3_flavor, R.drawable.important_iv_prop_25),
  ImportantProp(Generation.GenerationIV,R.string.Vs_Recorder, R.string.Vs_Recorder_flavor, R.drawable.important_iv_prop_26),
  ImportantProp(Generation.GenerationIV,R.string.Gracidea, R.string.Gracidea_flavor, R.drawable.important_iv_prop_27),
  ImportantProp(Generation.GenerationIV,R.string.Apricorn_Box, R.string.Apricorn_Box_flavor, R.drawable.important_iv_prop_28),
  ImportantProp(Generation.GenerationIV,R.string.Unown_Report, R.string.Unown_Report_flavor, R.drawable.important_iv_prop_29),
  ImportantProp(Generation.GenerationIV,R.string.Berry_Pots, R.string.Berry_Pots_flavor, R.drawable.important_iv_prop_30),
  ImportantProp(Generation.GenerationIV,R.string.Slowpoke_Tail, R.string.Slowpoke_Tail_flavor, R.drawable.important_iv_prop_31),
  ImportantProp(Generation.GenerationIV,R.string.Pass, R.string.Pass_flavor, R.drawable.important_iv_prop_32),
  ImportantProp(Generation.GenerationIV,R.string.Photo_Album, R.string.Photo_Album_flavor, R.drawable.important_iv_prop_33),
  ImportantProp(Generation.GenerationIV,R.string.GB_Sounds, R.string.GB_Sounds_flavor, R.drawable.important_iv_prop_34),
  ImportantProp(Generation.GenerationIV,R.string.Tidal_Bell, R.string.Tidal_Bell_flavor, R.drawable.important_iv_prop_35),
  ImportantProp(Generation.GenerationIV,R.string.Jade_Orb, R.string.Jade_Orb_flavor, R.drawable.important_iv_prop_36),
  ImportantProp(Generation.GenerationIV,R.string.Lock_Capsule1, R.string.Lock_Capsule1_flavor, R.drawable.important_iv_prop_37),
  ImportantProp(Generation.GenerationIV,R.string.Lock_Capsule2, R.string.Lock_Capsule2_flavor, R.drawable.important_iv_prop_38),
  ImportantProp(Generation.GenerationIV,R.string.Enigma_Stone, R.string.Enigma_Stone_flavor, R.drawable.important_iv_prop_39),
  ImportantProp(Generation.GenerationIV,R.string.Data_Card, R.string.Data_Card_flavor, R.drawable.important_iv_prop_40),
)

val importantVList = listOf(
  ImportantProp(Generation.GenerationV,R.string.Xtransceiver1, R.string.Xtransceiver1_flavor, R.drawable.important_v_prop_1),
  ImportantProp(Generation.GenerationV,R.string.Xtransceiver2, R.string.Xtransceiver2_flavor, R.drawable.important_v_prop_2),
  ImportantProp(Generation.GenerationV,R.string.Xtransceiver3, R.string.Xtransceiver3_flavor, R.drawable.important_v_prop_3),
  ImportantProp(Generation.GenerationV,R.string.Xtransceiver4, R.string.Xtransceiver4_flavor, R.drawable.important_v_prop_4),
  ImportantProp(Generation.GenerationV,R.string.Dragon_Skull, R.string.Dragon_Skull_flavor, R.drawable.important_v_prop_5),
  ImportantProp(Generation.GenerationV,R.string.Prop_Case, R.string.Prop_Case_flavor, R.drawable.important_v_prop_6),
  ImportantProp(Generation.GenerationV,R.string.Liberty_Pass, R.string.Liberty_Pass_flavor, R.drawable.important_v_prop_7),
  ImportantProp(Generation.GenerationV,R.string.Light_Stone, R.string.Light_Stone_flavor, R.drawable.important_v_prop_8),
  ImportantProp(Generation.GenerationV,R.string.Dark_Stone, R.string.Dark_Stone_flavor, R.drawable.important_v_prop_9),
  ImportantProp(Generation.GenerationV,R.string.God_Stone, R.string.God_Stone_flavor, R.drawable.important_v_prop_10),
  ImportantProp(Generation.GenerationV,R.string.Gram_1, R.string.Gram_1_flavor, R.drawable.important_v_prop_11),
  ImportantProp(Generation.GenerationV,R.string.Gram_2, R.string.Gram_2_flavor, R.drawable.important_v_prop_12),
  ImportantProp(Generation.GenerationV,R.string.Gram_3, R.string.Gram_3_flavor, R.drawable.important_v_prop_13),
  ImportantProp(Generation.GenerationV,R.string.Medal_Box, R.string.Medal_Box_flavor, R.drawable.important_v_prop_14),
  ImportantProp(Generation.GenerationV,R.string.DNA_Splicers1, R.string.DNA_Splicers1_flavor, R.drawable.important_v_prop_15),
  ImportantProp(Generation.GenerationV,R.string.DNA_Splicers2, R.string.DNA_Splicers2_flavor, R.drawable.important_v_prop_16),
  ImportantProp(Generation.GenerationV,R.string.Permit, R.string.Permit_flavor, R.drawable.important_v_prop_17),
  ImportantProp(Generation.GenerationV,R.string.Oval_Charm, R.string.Oval_Charm_flavor, R.drawable.important_v_prop_18),
  ImportantProp(Generation.GenerationV,R.string.Shiny_Charm, R.string.Shiny_Charm_flavor, R.drawable.important_v_prop_19),
  ImportantProp(Generation.GenerationV,R.string.Plasma_Card, R.string.Plasma_Card_flavor, R.drawable.important_v_prop_20),
  ImportantProp(Generation.GenerationV,R.string.Grubby_Hanky, R.string.Grubby_Hanky_flavor, R.drawable.important_v_prop_21),
  ImportantProp(Generation.GenerationV,R.string.Colress_Machine, R.string.Colress_Machine_flavor, R.drawable.important_v_prop_22),
  ImportantProp(Generation.GenerationV,R.string.Dropped_Item1, R.string.Dropped_Item1_flavor, R.drawable.important_v_prop_23),
  ImportantProp(Generation.GenerationV,R.string.Dropped_Item2, R.string.Dropped_Item2_flavor, R.drawable.important_v_prop_24),
  ImportantProp(Generation.GenerationV,R.string.Reveal_Glass, R.string.Reveal_Glass_flavor, R.drawable.important_v_prop_25),
)

val importantVIList = listOf(
  ImportantProp(Generation.GenerationVI,R.string.Holo_Caster1, R.string.Holo_Caster1_flavor, R.drawable.important_vi_prop_1),
  ImportantProp(Generation.GenerationVI,R.string.Holo_Caster2, R.string.Holo_Caster2_flavor, R.drawable.important_vi_prop_2),
  ImportantProp(Generation.GenerationVI,R.string.Prof_s_Letter, R.string.Prof_s_Letter_flavor, R.drawable.important_vi_prop_3),
  ImportantProp(Generation.GenerationVI,R.string.Roller_Skates, R.string.Roller_Skates_flavor, R.drawable.important_vi_prop_4),
  ImportantProp(Generation.GenerationVI,R.string.Exp_Share, R.string.Exp_Share_flavor, R.drawable.important_vi_prop_5),
  ImportantProp(Generation.GenerationVI,R.string.Sprinklotad, R.string.Sprinklotad_flavor, R.drawable.important_vi_prop_6),
  ImportantProp(Generation.GenerationVI,R.string.Power_Plant_Pass, R.string.Power_Plant_Pass_flavor, R.drawable.important_vi_prop_7),
  ImportantProp(Generation.GenerationVI,R.string.Mega_Ring, R.string.Mega_Ring_flavor, R.drawable.important_vi_prop_8),
  ImportantProp(Generation.GenerationVI,R.string.Intriguing_Stone, R.string.Intriguing_Stone_flavor, R.drawable.important_vi_prop_9),
  ImportantProp(Generation.GenerationVI,R.string.Common_Stone, R.string.Common_Stone_flavor, R.drawable.important_vi_prop_10),
  ImportantProp(Generation.GenerationVI,R.string.Elevator_Key, R.string.Elevator_Key_flavor, R.drawable.important_vi_prop_11),
  ImportantProp(Generation.GenerationVI,R.string.TMV_Pass, R.string.TMV_Pass_flavor, R.drawable.important_vi_prop_12),
  ImportantProp(Generation.GenerationVI,R.string.Honor_of_Kalos, R.string.Honor_of_Kalos_flavor, R.drawable.important_vi_prop_13),
  ImportantProp(Generation.GenerationVI,R.string.Adventure_Rules1, R.string.Adventure_Rules1_flavor, R.drawable.important_vi_prop_14),
  ImportantProp(Generation.GenerationVI,R.string.Adventure_Rules2, R.string.Adventure_Rules2_flavor, R.drawable.important_vi_prop_15),
  ImportantProp(Generation.GenerationVI,R.string.Lens_Case, R.string.Lens_Case_flavor, R.drawable.important_vi_prop_16),
  ImportantProp(Generation.GenerationVI,R.string.Travel_Trunk1, R.string.Travel_Trunk1_flavor, R.drawable.important_vi_prop_17),
  ImportantProp(Generation.GenerationVI,R.string.Travel_Trunk2, R.string.Travel_Trunk2_flavor, R.drawable.important_vi_prop_18),
  ImportantProp(Generation.GenerationVI,R.string.Looker_Ticket, R.string.Looker_Ticket_flavor, R.drawable.important_vi_prop_19),
  ImportantProp(Generation.GenerationVI,R.string.Mega_Charm, R.string.Mega_Charm_flavor, R.drawable.important_vi_prop_20),
  ImportantProp(Generation.GenerationVI,R.string.Mega_Glove, R.string.Mega_Glove_flavor, R.drawable.important_vi_prop_21),
  ImportantProp(Generation.GenerationVI,R.string.Pokéblock_Kit, R.string.Pokéblock_Kit_flavor, R.drawable.important_vi_prop_22),
  ImportantProp(Generation.GenerationVI,R.string.Eon_Ticket, R.string.Eon_Ticket_flavor, R.drawable.important_vi_prop_23),
  ImportantProp(Generation.GenerationVI,R.string.Devon_Scuba_Gear, R.string.Devon_Scuba_Gear_flavor, R.drawable.important_vi_prop_24),
  ImportantProp(Generation.GenerationVI,R.string.Contest_Costume1, R.string.Contest_Costume1_flavor, R.drawable.important_vi_prop_25),
  ImportantProp(Generation.GenerationVI,R.string.Contest_Costume2, R.string.Contest_Costume2_flavor, R.drawable.important_vi_prop_26),
  ImportantProp(Generation.GenerationVI,R.string.Magma_Suit, R.string.Magma_Suit_flavor, R.drawable.important_vi_prop_27),
  ImportantProp(Generation.GenerationVI,R.string.Aqua_Suit, R.string.Aqua_Suit_flavor, R.drawable.important_vi_prop_28),
  ImportantProp(Generation.GenerationVI,R.string.Pair_of_Tickets, R.string.Pair_of_Tickets_flavor, R.drawable.important_vi_prop_29),
  ImportantProp(Generation.GenerationVI,R.string.Mega_Bracelet, R.string.Mega_Bracelet_flavor, R.drawable.important_vi_prop_30),
  ImportantProp(Generation.GenerationVI,R.string.Mega_Cuff, R.string.Mega_Cuff_flavor, R.drawable.important_vi_prop_31),
  ImportantProp(Generation.GenerationVI,R.string.Mega_Pendant, R.string.Mega_Pendant_flavor, R.drawable.important_vi_prop_32),
  ImportantProp(Generation.GenerationVI,R.string.Mega_Glasses, R.string.Mega_Glasses_flavor, R.drawable.important_vi_prop_33),
  ImportantProp(Generation.GenerationVI,R.string.Mega_Anchor, R.string.Mega_Anchor_flavor, R.drawable.important_vi_prop_34),
  ImportantProp(Generation.GenerationVI,R.string.Mega_Stickpin, R.string.Mega_Stickpin_flavor, R.drawable.important_vi_prop_35),
  ImportantProp(Generation.GenerationVI,R.string.Mega_Tiara, R.string.Mega_Tiara_flavor, R.drawable.important_vi_prop_36),
  ImportantProp(Generation.GenerationVI,R.string.Mega_Anklet, R.string.Mega_Anklet_flavor, R.drawable.important_vi_prop_37),
  ImportantProp(Generation.GenerationVI,R.string.Key_Stone1, R.string.Key_Stone1_flavor, R.drawable.important_vi_prop_38),
  ImportantProp(Generation.GenerationVI,R.string.Key_Stone2, R.string.Key_Stone2_flavor, R.drawable.important_vi_prop_39),
  ImportantProp(Generation.GenerationVI,R.string.Key_Stone3, R.string.Key_Stone3_flavor, R.drawable.important_vi_prop_40),
  ImportantProp(Generation.GenerationVI,R.string.Meteorite_Shard, R.string.Meteorite_Shard_flavor, R.drawable.important_vi_prop_41),
  ImportantProp(Generation.GenerationVI,R.string.Eon_Flute, R.string.Eon_Flute_flavor, R.drawable.important_vi_prop_42),
  ImportantProp(Generation.GenerationVI,R.string.Prison_Bottle, R.string.Prison_Bottle_flavor, R.drawable.important_vi_prop_43),
)

  val importantVIIList = listOf(
  ImportantProp(Generation.GenerationVII,R.string.Makeup_Bag, R.string.Makeup_Bag_flavor, R.drawable.important_vii_prop_1),
  ImportantProp(Generation.GenerationVII,R.string.Z_Ring, R.string.Z_Ring_flavor, R.drawable.important_vii_prop_2),
  ImportantProp(Generation.GenerationVII,R.string.Forage_Bag, R.string.Forage_Bag_flavor, R.drawable.important_vii_prop_3),
  ImportantProp(Generation.GenerationVII,R.string.Fishing_Rod1, R.string.Fishing_Rod1_flavor, R.drawable.important_vii_prop_4),
  ImportantProp(Generation.GenerationVII,R.string.Fishing_Rod2, R.string.Fishing_Rod2_flavor, R.drawable.important_vii_prop_5),
  ImportantProp(Generation.GenerationVII,R.string.Professor_s_Mask, R.string.Professor_s_Mask_flavor, R.drawable.important_vii_prop_6),
  ImportantProp(Generation.GenerationVII,R.string.Sparkling_Stone1, R.string.Sparkling_Stone1_flavor, R.drawable.important_vii_prop_7),
  ImportantProp(Generation.GenerationVII,R.string.Sparkling_Stone2, R.string.Sparkling_Stone2_flavor, R.drawable.important_vii_prop_8),
  ImportantProp(Generation.GenerationVII,R.string.Zygarde_Cube, R.string.Zygarde_Cube_flavor, R.drawable.important_vii_prop_9),
  ImportantProp(Generation.GenerationVII,R.string.Ride_Pager, R.string.Ride_Pager_flavor, R.drawable.important_vii_prop_10),
  ImportantProp(Generation.GenerationVII,R.string.Sun_Flute, R.string.Sun_Flute_flavor, R.drawable.important_vii_prop_11),
  ImportantProp(Generation.GenerationVII,R.string.Moon_Flute, R.string.Moon_Flute_flavor, R.drawable.important_vii_prop_12),
  ImportantProp(Generation.GenerationVII,R.string.Enigmatic_Card, R.string.Enigmatic_Card_flavor, R.drawable.important_vii_prop_13),
  ImportantProp(Generation.GenerationVII,R.string.Z_Power_Ring, R.string.Z_Power_Ring_flavor, R.drawable.important_vii_prop_14),
  ImportantProp(Generation.GenerationVII,R.string.Pink_Petal, R.string.Pink_Petal_flavor, R.drawable.important_vii_prop_15),
  ImportantProp(Generation.GenerationVII,R.string.Orange_Petal, R.string.Orange_Petal_flavor, R.drawable.important_vii_prop_16),
  ImportantProp(Generation.GenerationVII,R.string.Blue_Petal, R.string.Blue_Petal_flavor, R.drawable.important_vii_prop_17),
  ImportantProp(Generation.GenerationVII,R.string.Red_Petal, R.string.Red_Petal_flavor, R.drawable.important_vii_prop_18),
  ImportantProp(Generation.GenerationVII,R.string.Green_Petal, R.string.Green_Petal_flavor, R.drawable.important_vii_prop_19),
  ImportantProp(Generation.GenerationVII,R.string.Yellow_Petal, R.string.Yellow_Petal_flavor, R.drawable.important_vii_prop_20),
  ImportantProp(Generation.GenerationVII,R.string.Purple_Petal, R.string.Purple_Petal_flavor, R.drawable.important_vii_prop_21),
  ImportantProp(Generation.GenerationVII,R.string.Rainbow_Flower, R.string.Rainbow_Flower_flavor, R.drawable.important_vii_prop_22),
  ImportantProp(Generation.GenerationVII,R.string.Surge_Badge, R.string.Surge_Badge_flavor, R.drawable.important_vii_prop_23),
  ImportantProp(Generation.GenerationVII,R.string.N_Solarizer, R.string.N_Solarizer_flavor, R.drawable.important_vii_prop_24),
  ImportantProp(Generation.GenerationVII,R.string.N_Lunarizer, R.string.N_Lunarizer_flavor, R.drawable.important_vii_prop_25),
  ImportantProp(Generation.GenerationVII,R.string.Ilima_s_Normalium, R.string.Ilima_s_Normalium_flavor, R.drawable.important_vii_prop_26),
  ImportantProp(Generation.GenerationVII,R.string.Left_Poké_Ball, R.string.Left_Poké_Ball_flavor, R.drawable.important_vii_prop_27),
  ImportantProp(Generation.GenerationVII,R.string.Autograph, R.string.Autograph_flavor, R.drawable.important_vii_prop_28),
  ImportantProp(Generation.GenerationVII,R.string.Pokémon_Box1, R.string.Pokémon_Box1_flavor, R.drawable.important_vii_prop_29),
  ImportantProp(Generation.GenerationVII,R.string.Pokémon_Box2, R.string.Pokémon_Box2_flavor, R.drawable.important_vii_prop_30),
  ImportantProp(Generation.GenerationVII,R.string.Medicine_Pocket, R.string.Medicine_Pocket_flavor, R.drawable.important_vii_prop_31),
  ImportantProp(Generation.GenerationVII,R.string.Candy_Jar, R.string.Candy_Jar_flavor, R.drawable.important_vii_prop_32),
  ImportantProp(Generation.GenerationVII,R.string.Power_Up_Pocket, R.string.Power_Up_Pocket_flavor, R.drawable.important_vii_prop_33),
  ImportantProp(Generation.GenerationVII,R.string.Clothing_Trunk, R.string.Clothing_Trunk_flavor, R.drawable.important_vii_prop_34),
  ImportantProp(Generation.GenerationVII,R.string.Catching_Pocket, R.string.Catching_Pocket_flavor, R.drawable.important_vii_prop_35),
  ImportantProp(Generation.GenerationVII,R.string.Battle_Pocket, R.string.Battle_Pocket_flavor, R.drawable.important_vii_prop_36),
)

val importantVIIIList = listOf(
  ImportantProp(Generation.GenerationVIII,R.string.Escape_Rope, R.string.Escape_Rope_flavor, R.drawable.important_viii_prop_1),
  ImportantProp(Generation.GenerationVIII,R.string.Endorsement, R.string.Endorsement_flavor, R.drawable.important_viii_prop_2),
  ImportantProp(Generation.GenerationVIII,R.string.Wishing_Star, R.string.Wishing_Star_flavor, R.drawable.important_viii_prop_3),
  ImportantProp(Generation.GenerationVIII,R.string.Dynamax_Band, R.string.Dynamax_Band_flavor, R.drawable.important_viii_prop_4),
  ImportantProp(Generation.GenerationVIII,R.string.Rotom_Bike1, R.string.Rotom_Bike1_flavor, R.drawable.important_viii_prop_5),
  ImportantProp(Generation.GenerationVIII,R.string.Rotom_Bike2, R.string.Rotom_Bike2_flavor, R.drawable.important_viii_prop_6),
  ImportantProp(Generation.GenerationVIII,R.string.Camping_Gear, R.string.Camping_Gear_flavor, R.drawable.important_viii_prop_7),
  ImportantProp(Generation.GenerationVIII,R.string.Hi_tech_Earbuds, R.string.Hi_tech_Earbuds_flavor, R.drawable.important_viii_prop_8),
  ImportantProp(Generation.GenerationVIII,R.string.Old_Letter, R.string.Old_Letter_flavor, R.drawable.important_viii_prop_9),
  ImportantProp(Generation.GenerationVIII,R.string.Band_Autograph, R.string.Band_Autograph_flavor, R.drawable.important_viii_prop_10),
  ImportantProp(Generation.GenerationVIII,R.string.Sonia_s_Book, R.string.Sonia_s_Book_flavor, R.drawable.important_viii_prop_11),
  ImportantProp(Generation.GenerationVIII,R.string.Rotom_Catalog, R.string.Rotom_Catalog_flavor, R.drawable.important_viii_prop_12),
  ImportantProp(Generation.GenerationVIII,R.string.Catching_Charm, R.string.Catching_Charm_flavor, R.drawable.important_viii_prop_13),
  ImportantProp(Generation.GenerationVIII,R.string.Armor_Pass, R.string.Armor_Pass_flavor, R.drawable.important_viii_prop_14),
  ImportantProp(Generation.GenerationVIII,R.string.Rotom_Bike3, R.string.Rotom_Bike3_flavor, R.drawable.important_viii_prop_15),
  ImportantProp(Generation.GenerationVIII,R.string.Rotom_Bike4, R.string.Rotom_Bike4_flavor, R.drawable.important_viii_prop_16),
  ImportantProp(Generation.GenerationVIII,R.string.Style_Card, R.string.Style_Card_flavor, R.drawable.important_viii_prop_17),
  ImportantProp(Generation.GenerationVIII,R.string.Exp_Charm, R.string.Exp_Charm_flavor, R.drawable.important_viii_prop_18),
  ImportantProp(Generation.GenerationVIII,R.string.Mark_Charm, R.string.Mark_Charm_flavor, R.drawable.important_viii_prop_19),
  ImportantProp(Generation.GenerationVIII,R.string.Crown_Pass, R.string.Crown_Pass_flavor, R.drawable.important_viii_prop_20),
  ImportantProp(Generation.GenerationVIII,R.string.Legendary_Clue_1, R.string.Legendary_Clue_1_flavor, R.drawable.important_viii_prop_21),
  ImportantProp(Generation.GenerationVIII,R.string.Legendary_Clue_2, R.string.Legendary_Clue_2_flavor, R.drawable.important_viii_prop_22),
  ImportantProp(Generation.GenerationVIII,R.string.Legendary_Clue_3, R.string.Legendary_Clue_3_flavor, R.drawable.important_viii_prop_23),
  ImportantProp(Generation.GenerationVIII,R.string.Legendary_Clue, R.string.Legendary_Clue_flavor, R.drawable.important_viii_prop_24),
  ImportantProp(Generation.GenerationVIII,R.string.Carrot_Seeds, R.string.Carrot_Seeds_flavor, R.drawable.important_viii_prop_25),
  ImportantProp(Generation.GenerationVIII,R.string.Iceroot_Carrot, R.string.Iceroot_Carrot_flavor, R.drawable.important_viii_prop_26),
  ImportantProp(Generation.GenerationVIII,R.string.Shaderoot_Carrot, R.string.Shaderoot_Carrot_flavor, R.drawable.important_viii_prop_27),
  ImportantProp(Generation.GenerationVIII,R.string.White_Mane_Hair, R.string.White_Mane_Hair_flavor, R.drawable.important_viii_prop_28),
  ImportantProp(Generation.GenerationVIII,R.string.Black_Mane_Hair, R.string.Black_Mane_Hair_flavor, R.drawable.important_viii_prop_29),
  ImportantProp(Generation.GenerationVIII,R.string.Wooden_Crown, R.string.Wooden_Crown_flavor, R.drawable.important_viii_prop_30),
  ImportantProp(Generation.GenerationVIII,R.string.Radiant_Petal, R.string.Radiant_Petal_flavor, R.drawable.important_viii_prop_31),
  ImportantProp(Generation.GenerationVIII,R.string.Reins_of_Unity, R.string.Reins_of_Unity_flavor, R.drawable.important_viii_prop_32),
  ImportantProp(Generation.GenerationVIII,R.string.DS_Sounds, R.string.DS_Sounds_flavor, R.drawable.important_viii_prop_33),
)

class Mail(val gen: Generation, nameResId: Int, flavorResId: Int, imageResId: Int) :
  GameProps(nameResId, flavorResId, imageResId)

val mailIIList = listOf(
  Mail(Generation.GenerationII,R.string.Bluesky_Mail, R.string.Bluesky_Mail_flavor, R.drawable.mail_ii_prop_1),
  Mail(Generation.GenerationII,R.string.Eon_Mail, R.string.Eon_Mail_flavor, R.drawable.mail_ii_prop_2),
  Mail(Generation.GenerationII,R.string.Flower_Mail, R.string.Flower_Mail_flavor, R.drawable.mail_ii_prop_3),
  Mail(Generation.GenerationII,R.string.Liteblue_mail, R.string.Liteblue_mail_flavor, R.drawable.mail_ii_prop_4),
  Mail(Generation.GenerationII,R.string.Lovely_Mail, R.string.Lovely_Mail_flavor, R.drawable.mail_ii_prop_5),
  Mail(Generation.GenerationII,R.string.Mirage_Mail, R.string.Mirage_Mail_flavor, R.drawable.mail_ii_prop_6),
  Mail(Generation.GenerationII,R.string.Morph_Mail, R.string.Morph_Mail_flavor, R.drawable.mail_ii_prop_7),
  Mail(Generation.GenerationII,R.string.Portrait_mail, R.string.Portrait_mail_flavor, R.drawable.mail_ii_prop_8),
  Mail(Generation.GenerationII,R.string.Music_Mail, R.string.Music_Mail_flavor, R.drawable.mail_ii_prop_9),
  Mail(Generation.GenerationII,R.string.Surf_Mail, R.string.Surf_Mail_flavor, R.drawable.mail_ii_prop_10),
)

val mailIIIList = listOf(
  Mail(Generation.GenerationIII,R.string.Orange_Mail, R.string.Orange_Mail_flavor, R.drawable.mail_iii_prop_1),
  Mail(Generation.GenerationIII,R.string.Harbor_Mail, R.string.Harbor_Mail_flavor, R.drawable.mail_iii_prop_2),
  Mail(Generation.GenerationIII,R.string.Glitter_Mail, R.string.Glitter_Mail_flavor, R.drawable.mail_iii_prop_3),
  Mail(Generation.GenerationIII,R.string.Mech_Mail, R.string.Mech_Mail_flavor, R.drawable.mail_iii_prop_4),
  Mail(Generation.GenerationIII,R.string.Wood_Mail, R.string.Wood_Mail_flavor, R.drawable.mail_iii_prop_5),
  Mail(Generation.GenerationIII,R.string.Wave_Mail, R.string.Wave_Mail_flavor, R.drawable.mail_iii_prop_6),
  Mail(Generation.GenerationIII,R.string.Bead_Mail, R.string.Bead_Mail_flavor, R.drawable.mail_iii_prop_7),
  Mail(Generation.GenerationIII,R.string.Shadow_Mail, R.string.Shadow_Mail_flavor, R.drawable.mail_iii_prop_8),
  Mail(Generation.GenerationIII,R.string.Tropical_Mail, R.string.Tropical_Mail_flavor, R.drawable.mail_iii_prop_9),
  Mail(Generation.GenerationIII,R.string.Dream_Mail, R.string.Dream_Mail_flavor, R.drawable.mail_iii_prop_10),
  Mail(Generation.GenerationIII,R.string.Miracle_Mail, R.string.Miracle_Mail_flavor, R.drawable.mail_iii_prop_11),
  Mail(Generation.GenerationIII,R.string.Retro_Mail, R.string.Retro_Mail_flavor, R.drawable.mail_iii_prop_12),

)

val mailIVList = listOf(
  Mail(Generation.GenerationIV,R.string.Grass_Mail, R.string.Grass_Mail_flavor, R.drawable.mail_iv_prop_1),
  Mail(Generation.GenerationIV,R.string.Flame_Mail, R.string.Flame_Mail_flavor, R.drawable.mail_iv_prop_2),
  Mail(Generation.GenerationIV,R.string.Bubble_Mail, R.string.Bubble_Mail_flavor, R.drawable.mail_iv_prop_3),
  Mail(Generation.GenerationIV,R.string.Bloom_Mail, R.string.Bloom_Mail_flavor, R.drawable.mail_iv_prop_5),
  Mail(Generation.GenerationIV,R.string.Tunnel_Mail, R.string.Tunnel_Mail_flavor, R.drawable.mail_iv_prop_6),
  Mail(Generation.GenerationIV,R.string.Steel_Mail, R.string.Steel_Mail_flavor, R.drawable.mail_iv_prop_7),
  Mail(Generation.GenerationIV,R.string.Heart_Mail, R.string.Heart_Mail_flavor, R.drawable.mail_iv_prop_8),
  Mail(Generation.GenerationIV,R.string.Snow_Mail, R.string.Snow_Mail_flavor, R.drawable.mail_iv_prop_9),
  Mail(Generation.GenerationIV,R.string.Space_Mail, R.string.Space_Mail_flavor, R.drawable.mail_iv_prop_10),
  Mail(Generation.GenerationIV,R.string.Air_Mail, R.string.Air_Mail_flavor, R.drawable.mail_iv_prop_11),
  Mail(Generation.GenerationIV,R.string.Mosaic_Mail, R.string.Mosaic_Mail_flavor, R.drawable.mail_iv_prop_12),
  Mail(Generation.GenerationIV,R.string.Brick_Mail, R.string.Brick_Mail_flavor, R.drawable.mail_iv_prop_12),
)

val mailVList = listOf(
  Mail(Generation.GenerationV,R.string.Greet_Mail, R.string.Greet_Mail_flavor, R.drawable.mail_v_prop_1),
  Mail(Generation.GenerationV,R.string.Favored_Mail, R.string.Favored_Mail_flavor, R.drawable.mail_v_prop_2),
  Mail(Generation.GenerationV,R.string.RSVP_Mail, R.string.RSVP_Mail_flavor, R.drawable.mail_v_prop_3),
  Mail(Generation.GenerationV,R.string.Thanks_Mail, R.string.Thanks_Mail_flavor, R.drawable.mail_v_prop_4),
  Mail(Generation.GenerationV,R.string.Inquiry_Mail, R.string.Inquiry_Mail_flavor, R.drawable.mail_v_prop_5),
  Mail(Generation.GenerationV,R.string.Like_Mail, R.string.Like_Mail_flavor, R.drawable.mail_v_prop_6),
  Mail(Generation.GenerationV,R.string.Reply_Mail, R.string.Reply_Mail_flavor, R.drawable.mail_v_prop_7),
  Mail(Generation.GenerationV,R.string.Bridge_Mail_S, R.string.Bridge_Mail_S_flavor, R.drawable.mail_v_prop_8),
  Mail(Generation.GenerationV,R.string.Bridge_Mail_D, R.string.Bridge_Mail_D_flavor, R.drawable.mail_v_prop_9),
  Mail(Generation.GenerationV,R.string.Bridge_Mail_T, R.string.Bridge_Mail_T_flavor, R.drawable.mail_v_prop_10),
  Mail(Generation.GenerationV,R.string.Bridge_Mail_V, R.string.Bridge_Mail_V_flavor, R.drawable.mail_v_prop_11),
  Mail(Generation.GenerationV,R.string.Bridge_Mail_M, R.string.Bridge_Mail_M_flavor, R.drawable.mail_v_prop_12),
)


class Pokeball(nameResId: Int, flavorResId: Int, imageResId: Int) :
  GameProps(nameResId, flavorResId, imageResId)

val pokeballList = listOf(
  Pokeball(R.string.Poké_Ball, R.string.Poké_Ball_flavor, R.drawable.pokeball_prop_1),
  Pokeball(R.string.Great_Ball, R.string.Great_Ball_flavor, R.drawable.pokeball_prop_2),
  Pokeball(R.string.Ultra_Ball, R.string.Ultra_Ball_flavor, R.drawable.pokeball_prop_3),
  Pokeball(R.string.Safari_Ball, R.string.Safari_Ball_flavor, R.drawable.pokeball_prop_4),
  Pokeball(R.string.Master_Ball, R.string.Master_Ball_flavor, R.drawable.pokeball_prop_5),
  Pokeball(R.string.Fast_Ball, R.string.Fast_Ball_flavor, R.drawable.pokeball_prop_6),
  Pokeball(R.string.Level_Ball, R.string.Level_Ball_flavor, R.drawable.pokeball_prop_7),
  Pokeball(R.string.Lure_Ball, R.string.Lure_Ball_flavor, R.drawable.pokeball_prop_8),
  Pokeball(R.string.Heavy_Ball, R.string.Heavy_Ball_flavor, R.drawable.pokeball_prop_9),
  Pokeball(R.string.Love_Ball, R.string.Love_Ball_flavor, R.drawable.pokeball_prop_10),
  Pokeball(R.string.Friend_Ball, R.string.Friend_Ball_flavor, R.drawable.pokeball_prop_11),
  Pokeball(R.string.Moon_Ball, R.string.Moon_Ball_flavor, R.drawable.pokeball_prop_12),
  Pokeball(R.string.Sport_Ball, R.string.Sport_Ball_flavor, R.drawable.pokeball_prop_13),
  Pokeball(R.string.Park_Ball, R.string.Park_Ball_flavor, R.drawable.pokeball_prop_14),
  Pokeball(R.string.Net_Ball, R.string.Net_Ball_flavor, R.drawable.pokeball_prop_15),
  Pokeball(R.string.Dive_Ball, R.string.Dive_Ball_flavor, R.drawable.pokeball_prop_16),
  Pokeball(R.string.Nest_Ball, R.string.Nest_Ball_flavor, R.drawable.pokeball_prop_17),
  Pokeball(R.string.Repeat_Ball, R.string.Repeat_Ball_flavor, R.drawable.pokeball_prop_18),
  Pokeball(R.string.Timer_Ball, R.string.Timer_Ball_flavor, R.drawable.pokeball_prop_19),
  Pokeball(R.string.Luxury_Ball, R.string.Luxury_Ball_flavor, R.drawable.pokeball_prop_20),
  Pokeball(R.string.Premier_Ball, R.string.Premier_Ball_flavor, R.drawable.pokeball_prop_21),
  Pokeball(R.string.Dusk_Ball, R.string.Dusk_Ball_flavor, R.drawable.pokeball_prop_22),
  Pokeball(R.string.Heal_Ball, R.string.Heal_Ball_flavor, R.drawable.pokeball_prop_23),
  Pokeball(R.string.Quick_Ball, R.string.Quick_Ball_flavor, R.drawable.pokeball_prop_24),
  Pokeball(R.string.Cherish_Ball, R.string.Cherish_Ball_flavor, R.drawable.pokeball_prop_25),
  Pokeball(R.string.Dream_Ball, R.string.Dream_Ball_flavor, R.drawable.pokeball_prop_26),
  Pokeball(R.string.Beast_Ball, R.string.Beast_Ball_flavor, R.drawable.pokeball_prop_27),
)

class Fossil(nameResId: Int, flavorResId: Int, imageResId: Int) :
  GameProps(nameResId, flavorResId, imageResId)

val fossilList = listOf(
  Fossil(R.string.Helix_Fossil, R.string.Helix_Fossil_flavor, R.drawable.fossil_prop_1),
  Fossil(R.string.Dome_Fossil, R.string.Dome_Fossil_flavor, R.drawable.fossil_prop_2),
  Fossil(R.string.Old_Amber, R.string.Old_Amber_flavor, R.drawable.fossil_prop_3),
  Fossil(R.string.Root_Fossil, R.string.Root_Fossil_flavor, R.drawable.fossil_prop_4),
  Fossil(R.string.Claw_Fossil, R.string.Claw_Fossil_flavor, R.drawable.fossil_prop_5),
  Fossil(R.string.Skull_Fossil, R.string.Skull_Fossil_flavor, R.drawable.fossil_prop_6),
  Fossil(R.string.Armor_Fossil, R.string.Armor_Fossil_flavor, R.drawable.fossil_prop_7),
  Fossil(R.string.Cover_Fossil, R.string.Cover_Fossil_flavor, R.drawable.fossil_prop_8),
  Fossil(R.string.Plume_Fossil, R.string.Plume_Fossil_flavor, R.drawable.fossil_prop_9),
  Fossil(R.string.Jaw_Fossil, R.string.Jaw_Fossil_flavor, R.drawable.fossil_prop_10),
  Fossil(R.string.Sail_Fossil, R.string.Sail_Fossil_flavor, R.drawable.fossil_prop_11),
  Fossil(
    R.string.Fossilized_Bird,
    R.string.Fossilized_Bird_flavor,
    R.drawable.fossil_prop_12
  ),
  Fossil(
    R.string.Fossilized_Fish,
    R.string.Fossilized_Fish_flavor,
    R.drawable.fossil_prop_13
  ),
  Fossil(
    R.string.Fossilized_Drake,
    R.string.Fossilized_Drake_flavor,
    R.drawable.fossil_prop_14
  ),
  Fossil(
    R.string.Fossilized_Dino,
    R.string.Fossilized_Dino_flavor,
    R.drawable.fossil_prop_15
  ),
)

class SwapProps(nameResId: Int, flavorResId: Int, imageResId: Int) :
  GameProps(nameResId, flavorResId, imageResId)

val swapPropList = listOf(
  SwapProps(R.string.Red_Shard, R.string.Red_Shard_flavor, R.drawable.swap_prop_1),
  SwapProps(R.string.Blue_Shard, R.string.Blue_Shard_flavor, R.drawable.swap_prop_2),
  SwapProps(R.string.Yellow_Shard, R.string.Yellow_Shard_flavor, R.drawable.swap_prop_3),
  SwapProps(R.string.Green_Shard, R.string.Green_Shard_flavor, R.drawable.swap_prop_4),
  SwapProps(R.string.Shoal_Salt, R.string.Shoal_Salt_flavor, R.drawable.swap_prop_5),
  SwapProps(R.string.Shoal_Shell, R.string.Shoal_Shell_flavor, R.drawable.swap_prop_6),
  SwapProps(R.string.Heart_Scale, R.string.Heart_Scale_flavor, R.drawable.swap_prop_7),
  SwapProps(R.string.Galarica_Twig, R.string.Galarica_Twig_flavor, R.drawable.swap_prop_8),
  SwapProps(R.string.Armorite_Ore, R.string.Armorite_Ore_flavor, R.drawable.swap_prop_9),
  SwapProps(R.string.Dynite_Ore, R.string.Dynite_Ore_flavor, R.drawable.swap_prop_10),
  SwapProps(
    R.string.Mysterious_Shard_S,
    R.string.Mysterious_Shard_S_flavor,
    R.drawable.swap_prop_11
  ),
  SwapProps(
    R.string.Mysterious_Shard_L,
    R.string.Mysterious_Shard_L_flavor,
    R.drawable.swap_prop_12
  ),
)

class CarryProps(val gen: Generation, nameResId: Int, flavorResId: Int, imageResId: Int) :
  GameProps(nameResId, flavorResId, imageResId)

val carryIIPropsList = listOf(
  CarryProps(Generation.GenerationII, R.string.Bright_Powder, R.string.Bright_Powder_flavor, R.drawable.carry_ii_prop_1),
  CarryProps(Generation.GenerationII, R.string.Exp_Share, R.string.Exp_Share_flavor, R.drawable.carry_ii_prop_2),
  CarryProps(Generation.GenerationII, R.string.Quick_Claw, R.string.Quick_Claw_flavor, R.drawable.carry_ii_prop_3),
  CarryProps(Generation.GenerationII, R.string.Kings_Rock, R.string.Kings_Rock_flavor, R.drawable.carry_ii_prop_4),
  CarryProps(Generation.GenerationII, R.string.Silver_Powder, R.string.Silver_Powder_flavor, R.drawable.carry_ii_prop_5),
  CarryProps(Generation.GenerationII, R.string.Amulet_Coin, R.string.Amulet_Coin_flavor, R.drawable.carry_ii_prop_6),
  CarryProps(Generation.GenerationII, R.string.Cleanse_Tag, R.string.Cleanse_Tag_flavor, R.drawable.carry_ii_prop_7),
  CarryProps(Generation.GenerationII, R.string.Smoke_Ball, R.string.Smoke_Ball_flavor, R.drawable.carry_ii_prop_8),
  CarryProps(Generation.GenerationII, R.string.Everstone, R.string.Everstone_flavor, R.drawable.carry_ii_prop_9),
  CarryProps(Generation.GenerationII, R.string.Focus_Band, R.string.Focus_Band_flavor, R.drawable.carry_ii_prop_10),
  CarryProps(Generation.GenerationII, R.string.Lucky_Egg, R.string.Lucky_Egg_flavor, R.drawable.carry_ii_prop_11),
  CarryProps(Generation.GenerationII, R.string.Scope_Lens, R.string.Scope_Lens_flavor, R.drawable.carry_ii_prop_12),
  CarryProps(Generation.GenerationII, R.string.Metal_Coat, R.string.Metal_Coat_flavor, R.drawable.carry_ii_prop_13),
  CarryProps(Generation.GenerationII, R.string.Leftovers, R.string.Leftovers_flavor, R.drawable.carry_ii_prop_14),
  CarryProps(Generation.GenerationII, R.string.Dragon_Scale, R.string.Dragon_Scale_flavor, R.drawable.carry_ii_prop_15),
  CarryProps(Generation.GenerationII, R.string.Light_Ball, R.string.Light_Ball_flavor, R.drawable.carry_ii_prop_16),
  CarryProps(Generation.GenerationII, R.string.Soft_Sand, R.string.Soft_Sand_flavor, R.drawable.carry_ii_prop_17),
  CarryProps(Generation.GenerationII, R.string.Hard_Stone, R.string.Hard_Stone_flavor, R.drawable.carry_ii_prop_18),
  CarryProps(Generation.GenerationII, R.string.Miracle_Seed, R.string.Miracle_Seed_flavor, R.drawable.carry_ii_prop_19),
  CarryProps(Generation.GenerationII, R.string.Black_Glasses, R.string.Black_Glasses_flavor, R.drawable.carry_ii_prop_20),
  CarryProps(Generation.GenerationII, R.string.Black_Belt, R.string.Black_Belt_flavor, R.drawable.carry_ii_prop_21),
  CarryProps(Generation.GenerationII, R.string.Magnet_, R.string.Magnet__flavor, R.drawable.carry_ii_prop_22),
  CarryProps(Generation.GenerationII, R.string.Mystic_Water, R.string.Mystic_Water_flavor, R.drawable.carry_ii_prop_23),
  CarryProps(Generation.GenerationII, R.string.Sharp_Beak, R.string.Sharp_Beak_flavor, R.drawable.carry_ii_prop_24),
  CarryProps(Generation.GenerationII, R.string.Poison_Barb, R.string.Poison_Barb_flavor, R.drawable.carry_ii_prop_25),
  CarryProps(Generation.GenerationII, R.string.NeverMelt_Ice, R.string.NeverMelt_Ice_flavor, R.drawable.carry_ii_prop_26),
  CarryProps(Generation.GenerationII, R.string.Spell_Tag, R.string.Spell_Tag_flavor, R.drawable.carry_ii_prop_27),
  CarryProps(Generation.GenerationII, R.string.Twisted_Spoon, R.string.Twisted_Spoon_flavor, R.drawable.carry_ii_prop_28),
  CarryProps(Generation.GenerationII, R.string.Charcoal, R.string.Charcoal_flavor, R.drawable.carry_ii_prop_29),
  CarryProps(Generation.GenerationII, R.string.Dragon_Fang, R.string.Dragon_Fang_flavor, R.drawable.carry_ii_prop_30),
  CarryProps(Generation.GenerationII, R.string.Pink_Bow, R.string.Pink_Bow_flavor, R.drawable.carry_ii_prop_31),
  CarryProps(Generation.GenerationII, R.string.Polkadot_Bow, R.string.Polkadot_Bow_flavor, R.drawable.carry_ii_prop_32),
  CarryProps(Generation.GenerationII, R.string.Berserk_Gene, R.string.Berserk_Gene_flavor, R.drawable.carry_ii_prop_33),
  CarryProps(Generation.GenerationII, R.string.Up_Grade, R.string.Up_Grade_flavor, R.drawable.carry_ii_prop_34),
  CarryProps(Generation.GenerationII, R.string.Lucky_Punch, R.string.Lucky_Punch_flavor, R.drawable.carry_ii_prop_35),
  CarryProps(Generation.GenerationII, R.string.Metal_Powder, R.string.Metal_Powder_flavor, R.drawable.carry_ii_prop_36),
  CarryProps(Generation.GenerationII, R.string.Thick_Club, R.string.Thick_Club_flavor, R.drawable.carry_ii_prop_37),
  CarryProps(Generation.GenerationII, R.string.Stick, R.string.Stick_flavor, R.drawable.carry_ii_prop_38),
  CarryProps(Generation.GenerationII, R.string.Berry, R.string.Berry_flavor, R.drawable.carry_ii_prop_39),
  CarryProps(Generation.GenerationII, R.string.Gold_Berry, R.string.Gold_Berry_flavor, R.drawable.carry_ii_prop_40),
  CarryProps(Generation.GenerationII, R.string.PRZCureBerry, R.string.PRZCureBerry_flavor, R.drawable.carry_ii_prop_41),
  CarryProps(Generation.GenerationII, R.string.PSNCureBerry, R.string.PSNCureBerry_flavor, R.drawable.carry_ii_prop_42),
  CarryProps(Generation.GenerationII, R.string.Bitter_Berry, R.string.Bitter_Berry_flavor, R.drawable.carry_ii_prop_43),
  CarryProps(Generation.GenerationII, R.string.Burnt_Berry, R.string.Burnt_Berry_flavor, R.drawable.carry_ii_prop_44),
  CarryProps(Generation.GenerationII, R.string.Ice_Berry, R.string.Ice_Berry_flavor, R.drawable.carry_ii_prop_45),
  CarryProps(Generation.GenerationII, R.string.Mint_Berry, R.string.Mint_Berry_flavor, R.drawable.carry_ii_prop_46),
  CarryProps(Generation.GenerationII, R.string.MiracleBerry, R.string.MiracleBerry_flavor, R.drawable.carry_ii_prop_47),
  CarryProps(Generation.GenerationII, R.string.MysteryBerry, R.string.MysteryBerry_flavor, R.drawable.carry_ii_prop_48),
)

val carryIIIPropsList = listOf(
  CarryProps(Generation.GenerationIII, R.string.White_Herb, R.string.White_Herb_flavor, R.drawable.carry_iii_prop_1),
  CarryProps(Generation.GenerationIII, R.string.Mental_Herb, R.string.Mental_Herb_flavor, R.drawable.carry_iii_prop_2),
  CarryProps(Generation.GenerationIII, R.string.Macho_Brace, R.string.Macho_Brace_flavor, R.drawable.carry_iii_prop_3),
  CarryProps(Generation.GenerationIII, R.string.Soothe_Bell, R.string.Soothe_Bell_flavor, R.drawable.carry_iii_prop_4),
  CarryProps(Generation.GenerationIII, R.string.Choice_Band, R.string.Choice_Band_flavor, R.drawable.carry_iii_prop_5),
  CarryProps(Generation.GenerationIII, R.string.Soul_Dew, R.string.Soul_Dew_flavor, R.drawable.carry_iii_prop_6),
  CarryProps(Generation.GenerationIII, R.string.Deep_Sea_Tooth, R.string.Deep_Sea_Tooth_flavor, R.drawable.carry_iii_prop_7),
  CarryProps(Generation.GenerationIII, R.string.Deep_Sea_Scale, R.string.Deep_Sea_Scale_flavor, R.drawable.carry_iii_prop_8),
  CarryProps(Generation.GenerationIII, R.string.Silk_Scarf, R.string.Silk_Scarf_flavor, R.drawable.carry_iii_prop_9),
  CarryProps(Generation.GenerationIII, R.string.Shell_Bell, R.string.Shell_Bell_flavor, R.drawable.carry_iii_prop_10),
  CarryProps(Generation.GenerationIII, R.string.Sea_Incense, R.string.Sea_Incense_flavor, R.drawable.carry_iii_prop_11),
  CarryProps(Generation.GenerationIII, R.string.Lax_Incense, R.string.Lax_Incense_flavor, R.drawable.carry_iii_prop_12),
  CarryProps(Generation.GenerationIII, R.string.Red_Scarf, R.string.Red_Scarf_flavor, R.drawable.carry_iii_prop_13),
  CarryProps(Generation.GenerationIII, R.string.Blue_Scarf, R.string.Blue_Scarf_flavor, R.drawable.carry_iii_prop_14),
  CarryProps(Generation.GenerationIII, R.string.Pink_Scarf, R.string.Pink_Scarf_flavor, R.drawable.carry_iii_prop_15),
  CarryProps(Generation.GenerationIII, R.string.Green_Scarf, R.string.Green_Scarf_flavor, R.drawable.carry_iii_prop_16),
  CarryProps(Generation.GenerationIII, R.string.Yellow_Scarf, R.string.Yellow_Scarf_flavor, R.drawable.carry_iii_prop_17),
)

val carryIVPropsList = listOf(
  CarryProps(Generation.GenerationIV, R.string.Flame_Plate, R.string.Flame_Plate_flavor, R.drawable.carry_iv_prop_1),
  CarryProps(Generation.GenerationIV, R.string.Splash_Plate, R.string.Splash_Plate_flavor, R.drawable.carry_iv_prop_2),
  CarryProps(Generation.GenerationIV, R.string.Zap_Plate, R.string.Zap_Plate_flavor, R.drawable.carry_iv_prop_3),
  CarryProps(Generation.GenerationIV, R.string.Meadow_Plate, R.string.Meadow_Plate_flavor, R.drawable.carry_iv_prop_4),
  CarryProps(Generation.GenerationIV, R.string.Icicle_Plate, R.string.Icicle_Plate_flavor, R.drawable.carry_iv_prop_5),
  CarryProps(Generation.GenerationIV, R.string.Fist_Plate, R.string.Fist_Plate_flavor, R.drawable.carry_iv_prop_6),
  CarryProps(Generation.GenerationIV, R.string.Toxic_Plate, R.string.Toxic_Plate_flavor, R.drawable.carry_iv_prop_7),
  CarryProps(Generation.GenerationIV, R.string.Earth_Plate, R.string.Earth_Plate_flavor, R.drawable.carry_iv_prop_8),
  CarryProps(Generation.GenerationIV, R.string.Sky_Plate, R.string.Sky_Plate_flavor, R.drawable.carry_iv_prop_9),
  CarryProps(Generation.GenerationIV, R.string.Mind_Plate, R.string.Mind_Plate_flavor, R.drawable.carry_iv_prop_10),
  CarryProps(Generation.GenerationIV, R.string.Insect_Plate, R.string.Insect_Plate_flavor, R.drawable.carry_iv_prop_11),
  CarryProps(Generation.GenerationIV, R.string.Stone_Plate, R.string.Stone_Plate_flavor, R.drawable.carry_iv_prop_12),
  CarryProps(Generation.GenerationIV, R.string.Spooky_Plate, R.string.Spooky_Plate_flavor, R.drawable.carry_iv_prop_13),
  CarryProps(Generation.GenerationIV, R.string.Draco_Plate, R.string.Draco_Plate_flavor, R.drawable.carry_iv_prop_14),
  CarryProps(Generation.GenerationIV, R.string.Dread_Plate, R.string.Dread_Plate_flavor, R.drawable.carry_iv_prop_15),
  CarryProps(Generation.GenerationIV, R.string.Iron_Plate, R.string.Iron_Plate_flavor, R.drawable.carry_iv_prop_16),
  CarryProps(Generation.GenerationIV, R.string.Oval_Stone, R.string.Oval_Stone_flavor, R.drawable.carry_iv_prop_17),
  CarryProps(Generation.GenerationIV, R.string.Adamant_Orb, R.string.Adamant_Orb_flavor, R.drawable.carry_iv_prop_18),
  CarryProps(Generation.GenerationIV, R.string.Lustrous_Orb, R.string.Lustrous_Orb_flavor, R.drawable.carry_iv_prop_19),
  CarryProps(Generation.GenerationIV, R.string.Griseous_Orb, R.string.Griseous_Orb_flavor, R.drawable.carry_iv_prop_20),
  CarryProps(Generation.GenerationIV, R.string.Odd_Incense, R.string.Odd_Incense_flavor, R.drawable.carry_iv_prop_21),
  CarryProps(Generation.GenerationIV, R.string.Rock_Incense, R.string.Rock_Incense_flavor, R.drawable.carry_iv_prop_22),
  CarryProps(Generation.GenerationIV, R.string.Full_Incense, R.string.Full_Incense_flavor, R.drawable.carry_iv_prop_23),
  CarryProps(Generation.GenerationIV, R.string.Wave_Incense, R.string.Wave_Incense_flavor, R.drawable.carry_iv_prop_24),
  CarryProps(Generation.GenerationIV, R.string.Rose_Incense, R.string.Rose_Incense_flavor, R.drawable.carry_iv_prop_25),
  CarryProps(Generation.GenerationIV, R.string.Luck_Incense, R.string.Luck_Incense_flavor, R.drawable.carry_iv_prop_26),
  CarryProps(Generation.GenerationIV, R.string.Pure_Incense, R.string.Pure_Incense_flavor, R.drawable.carry_iv_prop_27),
  CarryProps(Generation.GenerationIV, R.string.Protector, R.string.Protector_flavor, R.drawable.carry_iv_prop_28),
  CarryProps(Generation.GenerationIV, R.string.Electirizer, R.string.Electirizer_flavor, R.drawable.carry_iv_prop_29),
  CarryProps(Generation.GenerationIV, R.string.Magmarizer, R.string.Magmarizer_flavor, R.drawable.carry_iv_prop_30),
  CarryProps(Generation.GenerationIV, R.string.Dubious_Disc, R.string.Dubious_Disc_flavor, R.drawable.carry_iv_prop_31),
  CarryProps(Generation.GenerationIV, R.string.Reaper_Cloth, R.string.Reaper_Cloth_flavor, R.drawable.carry_iv_prop_32),
  CarryProps(Generation.GenerationIV, R.string.Razor_Claw, R.string.Razor_Claw_flavor, R.drawable.carry_iv_prop_33),
  CarryProps(Generation.GenerationIV, R.string.Razor_Fang, R.string.Razor_Fang_flavor, R.drawable.carry_iv_prop_34),
  CarryProps(Generation.GenerationIV, R.string.Wide_Lens, R.string.Wide_Lens_flavor, R.drawable.carry_iv_prop_35),
  CarryProps(Generation.GenerationIV, R.string.Muscle_Band, R.string.Muscle_Band_flavor, R.drawable.carry_iv_prop_36),
  CarryProps(Generation.GenerationIV, R.string.Wise_Glasses, R.string.Wise_Glasses_flavor, R.drawable.carry_iv_prop_37),
  CarryProps(Generation.GenerationIV, R.string.Expert_Belt, R.string.Expert_Belt_flavor, R.drawable.carry_iv_prop_38),
  CarryProps(Generation.GenerationIV, R.string.Light_Clay, R.string.Light_Clay_flavor, R.drawable.carry_iv_prop_39),
  CarryProps(Generation.GenerationIV, R.string.Life_Orb, R.string.Life_Orb_flavor, R.drawable.carry_iv_prop_40),
  CarryProps(Generation.GenerationIV, R.string.Power_Herb, R.string.Power_Herb_flavor, R.drawable.carry_iv_prop_41),
  CarryProps(Generation.GenerationIV, R.string.Toxic_Orb, R.string.Toxic_Orb_flavor, R.drawable.carry_iv_prop_42),
  CarryProps(Generation.GenerationIV, R.string.Flame_Orb, R.string.Flame_Orb_flavor, R.drawable.carry_iv_prop_43),
  CarryProps(Generation.GenerationIV, R.string.Quick_Powder, R.string.Quick_Powder_flavor, R.drawable.carry_iv_prop_44),
  CarryProps(Generation.GenerationIV, R.string.Focus_Sash, R.string.Focus_Sash_flavor, R.drawable.carry_iv_prop_45),
  CarryProps(Generation.GenerationIV, R.string.Zoom_Lens, R.string.Zoom_Lens_flavor, R.drawable.carry_iv_prop_46),
  CarryProps(Generation.GenerationIV, R.string.Metronome, R.string.Metronome_flavor, R.drawable.carry_iv_prop_47),
  CarryProps(Generation.GenerationIV, R.string.Iron_Ball, R.string.Iron_Ball_flavor, R.drawable.carry_iv_prop_48),
  CarryProps(Generation.GenerationIV, R.string.Lagging_Tail, R.string.Lagging_Tail_flavor, R.drawable.carry_iv_prop_49),
  CarryProps(Generation.GenerationIV, R.string.Destiny_Knot, R.string.Destiny_Knot_flavor, R.drawable.carry_iv_prop_50),
  CarryProps(Generation.GenerationIV, R.string.Black_Sludge, R.string.Black_Sludge_flavor, R.drawable.carry_iv_prop_51),
  CarryProps(Generation.GenerationIV, R.string.Icy_Rock, R.string.Icy_Rock_flavor, R.drawable.carry_iv_prop_52),
  CarryProps(Generation.GenerationIV, R.string.Smooth_Rock, R.string.Smooth_Rock_flavor, R.drawable.carry_iv_prop_53),
  CarryProps(Generation.GenerationIV, R.string.Heat_Rock, R.string.Heat_Rock_flavor, R.drawable.carry_iv_prop_54),
  CarryProps(Generation.GenerationIV, R.string.Damp_Rock, R.string.Damp_Rock_flavor, R.drawable.carry_iv_prop_55),
  CarryProps(Generation.GenerationIV, R.string.Grip_Claw, R.string.Grip_Claw_flavor, R.drawable.carry_iv_prop_56),
  CarryProps(Generation.GenerationIV, R.string.Choice_Scarf, R.string.Choice_Scarf_flavor, R.drawable.carry_iv_prop_57),
  CarryProps(Generation.GenerationIV, R.string.Sticky_Barb, R.string.Sticky_Barb_flavor, R.drawable.carry_iv_prop_58),
  CarryProps(Generation.GenerationIV, R.string.Power_Bracer, R.string.Power_Bracer_flavor, R.drawable.carry_iv_prop_59),
  CarryProps(Generation.GenerationIV, R.string.Power_Belt, R.string.Power_Belt_flavor, R.drawable.carry_iv_prop_60),
  CarryProps(Generation.GenerationIV, R.string.Rusted_Sword, R.string.Rusted_Sword_flavor, R.drawable.carry_viii_prop_1),
  CarryProps(Generation.GenerationIV, R.string.Power_Lens, R.string.Power_Lens_flavor, R.drawable.carry_iv_prop_61),
  CarryProps(Generation.GenerationIV, R.string.Power_Band, R.string.Power_Band_flavor, R.drawable.carry_iv_prop_62),
  CarryProps(Generation.GenerationIV, R.string.Power_Anklet, R.string.Power_Anklet_flavor, R.drawable.carry_iv_prop_63),
  CarryProps(Generation.GenerationIV, R.string.Power_Weight, R.string.Power_Weight_flavor, R.drawable.carry_iv_prop_64),
  CarryProps(Generation.GenerationIV, R.string.Shed_Shell, R.string.Shed_Shell_flavor, R.drawable.carry_iv_prop_65),
  CarryProps(Generation.GenerationIV, R.string.Big_Root, R.string.Big_Root_flavor, R.drawable.carry_iv_prop_66),
  CarryProps(Generation.GenerationIV, R.string.Choice_Specs, R.string.Choice_Specs_flavor, R.drawable.carry_iv_prop_67),
)

val carryVPropsList = listOf(
  CarryProps(Generation.GenerationV, R.string.Douse_Drive, R.string.Douse_Drive_flavor, R.drawable.carry_v_prop_1),
  CarryProps(Generation.GenerationV, R.string.Shock_Drive, R.string.Shock_Drive_flavor, R.drawable.carry_v_prop_2),
  CarryProps(Generation.GenerationV, R.string.Burn_Drive, R.string.Burn_Drive_flavor, R.drawable.carry_v_prop_3),
  CarryProps(Generation.GenerationV, R.string.Chill_Drive, R.string.Chill_Drive_flavor, R.drawable.carry_v_prop_4),
  CarryProps(Generation.GenerationV, R.string.Prism_Scale, R.string.Prism_Scale_flavor, R.drawable.carry_v_prop_5),
  CarryProps(Generation.GenerationV, R.string.Eviolite, R.string.Eviolite_flavor, R.drawable.carry_v_prop_6),
  CarryProps(Generation.GenerationV, R.string.Float_Stone, R.string.Float_Stone_flavor, R.drawable.carry_v_prop_7),
  CarryProps(Generation.GenerationV, R.string.Rocky_Helmet, R.string.Rocky_Helmet_flavor, R.drawable.carry_v_prop_8),
  CarryProps(Generation.GenerationV, R.string.Air_Balloon, R.string.Air_Balloon_flavor, R.drawable.carry_v_prop_9),
  CarryProps(Generation.GenerationV, R.string.Red_Card, R.string.Red_Card_flavor, R.drawable.carry_v_prop_10),
  CarryProps(Generation.GenerationV, R.string.Ring_Target, R.string.Ring_Target_flavor, R.drawable.carry_v_prop_11),
  CarryProps(Generation.GenerationV, R.string.Binding_Band, R.string.Binding_Band_flavor, R.drawable.carry_v_prop_12),
  CarryProps(Generation.GenerationV, R.string.Absorb_Bulb, R.string.Absorb_Bulb_flavor, R.drawable.carry_v_prop_13),
  CarryProps(Generation.GenerationV, R.string.Cell_Battery, R.string.Cell_Battery_flavor, R.drawable.carry_v_prop_14),
  CarryProps(Generation.GenerationV, R.string.Eject_Button, R.string.Eject_Button_flavor, R.drawable.carry_v_prop_15),
  CarryProps(Generation.GenerationV, R.string.Fire_Gem, R.string.Fire_Gem_flavor, R.drawable.carry_v_prop_16),
  CarryProps(Generation.GenerationV, R.string.Water_Gem, R.string.Water_Gem_flavor, R.drawable.carry_v_prop_17),
  CarryProps(Generation.GenerationV, R.string.Electric_Gem, R.string.Electric_Gem_flavor, R.drawable.carry_v_prop_18),
  CarryProps(Generation.GenerationV, R.string.Grass_Gem, R.string.Grass_Gem_flavor, R.drawable.carry_v_prop_19),
  CarryProps(Generation.GenerationV, R.string.Ice_Gem, R.string.Ice_Gem_flavor, R.drawable.carry_v_prop_20),
  CarryProps(Generation.GenerationV, R.string.Fighting_Gem, R.string.Fighting_Gem_flavor, R.drawable.carry_v_prop_21),
  CarryProps(Generation.GenerationV, R.string.Poison_Gem, R.string.Poison_Gem_flavor, R.drawable.carry_v_prop_22),
  CarryProps(Generation.GenerationV, R.string.Ground_Gem, R.string.Ground_Gem_flavor, R.drawable.carry_v_prop_23),
  CarryProps(Generation.GenerationV, R.string.Flying_Gem, R.string.Flying_Gem_flavor, R.drawable.carry_v_prop_24),
  CarryProps(Generation.GenerationV, R.string.Psychic_Gem, R.string.Psychic_Gem_flavor, R.drawable.carry_v_prop_25),
  CarryProps(Generation.GenerationV, R.string.Bug_Gem, R.string.Bug_Gem_flavor, R.drawable.carry_v_prop_26),
  CarryProps(Generation.GenerationV, R.string.Rock_Gem, R.string.Rock_Gem_flavor, R.drawable.carry_v_prop_27),
  CarryProps(Generation.GenerationV, R.string.Ghost_Gem, R.string.Ghost_Gem_flavor, R.drawable.carry_v_prop_28),
  CarryProps(Generation.GenerationV, R.string.Dragon_Gem, R.string.Dragon_Gem_flavor, R.drawable.carry_v_prop_29),
  CarryProps(Generation.GenerationV, R.string.Dark_Gem, R.string.Dark_Gem_flavor, R.drawable.carry_v_prop_30),
  CarryProps(Generation.GenerationV, R.string.Steel_Gem, R.string.Steel_Gem_flavor, R.drawable.carry_v_prop_31),
  CarryProps(Generation.GenerationV, R.string.Normal_Gem, R.string.Normal_Gem_flavor, R.drawable.carry_v_prop_32)
)

val carryVIPropsList = listOf(
  CarryProps(Generation.GenerationVI, R.string.Weakness_Policy, R.string.Weakness_Policy_flavor, R.drawable.carry_vi_prop_1),
  CarryProps(Generation.GenerationVI, R.string.Assault_Vest, R.string.Assault_Vest_flavor, R.drawable.carry_vi_prop_2),
  CarryProps(Generation.GenerationVI, R.string.Pixie_Plate, R.string.Pixie_Plate_flavor, R.drawable.carry_vi_prop_3),
  CarryProps(Generation.GenerationVI, R.string.Fairy_Gem, R.string.Fairy_Gem_flavor, R.drawable.carry_vi_prop_4),
  CarryProps(Generation.GenerationVI, R.string.Whipped_Dream, R.string.Whipped_Dream_flavor, R.drawable.carry_vi_prop_5),
  CarryProps(Generation.GenerationVI, R.string.Sachet, R.string.Sachet_flavor, R.drawable.carry_vi_prop_6),
  CarryProps(Generation.GenerationVI, R.string.Luminous_Moss, R.string.Luminous_Moss_flavor, R.drawable.carry_vi_prop_7),
  CarryProps(Generation.GenerationVI, R.string.Snowball, R.string.Snowball_flavor, R.drawable.carry_vi_prop_8),
  CarryProps(Generation.GenerationVI, R.string.Safety_Goggles, R.string.Safety_Goggles_flavor, R.drawable.carry_vi_prop_9),
  CarryProps(Generation.GenerationVI, R.string.Venusaurite, R.string.Venusaurite_flavor, R.drawable.carry_vi_prop_10),
  CarryProps(Generation.GenerationVI, R.string.Charizardite_X, R.string.Charizardite_X_flavor, R.drawable.carry_vi_prop_11),
  CarryProps(Generation.GenerationVI, R.string.Charizardite_Y, R.string.Charizardite_Y_flavor, R.drawable.carry_vi_prop_12),
  CarryProps(Generation.GenerationVI, R.string.Blastoisinite, R.string.Blastoisinite_flavor, R.drawable.carry_vi_prop_13),
  CarryProps(Generation.GenerationVI, R.string.Beedrillite, R.string.Beedrillite_flavor, R.drawable.carry_vi_prop_14),
  CarryProps(Generation.GenerationVI, R.string.Pidgeotite, R.string.Pidgeotite_flavor, R.drawable.carry_vi_prop_15),
  CarryProps(Generation.GenerationVI, R.string.Alakazite, R.string.Alakazite_flavor, R.drawable.carry_vi_prop_16),
  CarryProps(Generation.GenerationVI, R.string.Slowbronite, R.string.Slowbronite_flavor, R.drawable.carry_vi_prop_17),
  CarryProps(Generation.GenerationVI, R.string.Gengarite, R.string.Gengarite_flavor, R.drawable.carry_vi_prop_18),
  CarryProps(Generation.GenerationVI, R.string.Kangaskhanite, R.string.Kangaskhanite_flavor, R.drawable.carry_vi_prop_19),
  CarryProps(Generation.GenerationVI, R.string.Pinsirite, R.string.Pinsirite_flavor, R.drawable.carry_vi_prop_20),
  CarryProps(Generation.GenerationVI, R.string.Gyaradosite, R.string.Gyaradosite_flavor, R.drawable.carry_vi_prop_21),
  CarryProps(Generation.GenerationVI, R.string.Aerodactylite, R.string.Aerodactylite_flavor, R.drawable.carry_vi_prop_22),
  CarryProps(Generation.GenerationVI, R.string.Mewtwonite_X, R.string.Mewtwonite_X_flavor, R.drawable.carry_vi_prop_23),
  CarryProps(Generation.GenerationVI, R.string.Mewtwonite_Y, R.string.Mewtwonite_Y_flavor, R.drawable.carry_vi_prop_24),
  CarryProps(Generation.GenerationVI, R.string.Ampharosite, R.string.Ampharosite_flavor, R.drawable.carry_vi_prop_25),
  CarryProps(Generation.GenerationVI, R.string.Steelixite, R.string.Steelixite_flavor, R.drawable.carry_vi_prop_26),
  CarryProps(Generation.GenerationVI, R.string.Scizorite, R.string.Scizorite_flavor, R.drawable.carry_vi_prop_27),
  CarryProps(Generation.GenerationVI, R.string.Heracronite, R.string.Heracronite_flavor, R.drawable.carry_vi_prop_28),
  CarryProps(Generation.GenerationVI, R.string.Houndoominite, R.string.Houndoominite_flavor, R.drawable.carry_vi_prop_29),
  CarryProps(Generation.GenerationVI, R.string.Tyranitarite, R.string.Tyranitarite_flavor, R.drawable.carry_vi_prop_30),
  CarryProps(Generation.GenerationVI, R.string.Sceptilite, R.string.Sceptilite_flavor, R.drawable.carry_vi_prop_31),
  CarryProps(Generation.GenerationVI, R.string.Blazikenite, R.string.Blazikenite_flavor, R.drawable.carry_vi_prop_32),
  CarryProps(Generation.GenerationVI, R.string.Swampertite, R.string.Swampertite_flavor, R.drawable.carry_vi_prop_33),
  CarryProps(Generation.GenerationVI, R.string.Gardevoirite, R.string.Gardevoirite_flavor, R.drawable.carry_vi_prop_34),
  CarryProps(Generation.GenerationVI, R.string.Sablenite, R.string.Sablenite_flavor, R.drawable.carry_vi_prop_35),
  CarryProps(Generation.GenerationVI, R.string.Mawilite, R.string.Mawilite_flavor, R.drawable.carry_vi_prop_36),
  CarryProps(Generation.GenerationVI, R.string.Aggronite, R.string.Aggronite_flavor, R.drawable.carry_vi_prop_37),
  CarryProps(Generation.GenerationVI, R.string.Medichamite, R.string.Medichamite_flavor, R.drawable.carry_vi_prop_38),
  CarryProps(Generation.GenerationVI, R.string.Manectite, R.string.Manectite_flavor, R.drawable.carry_vi_prop_39),
  CarryProps(Generation.GenerationVI, R.string.Sharpedonite, R.string.Sharpedonite_flavor, R.drawable.carry_vi_prop_40),
  CarryProps(Generation.GenerationVI, R.string.Cameruptite, R.string.Cameruptite_flavor, R.drawable.carry_vi_prop_41),
  CarryProps(Generation.GenerationVI, R.string.Altarianite, R.string.Altarianite_flavor, R.drawable.carry_vi_prop_42),
  CarryProps(Generation.GenerationVI, R.string.Banettite, R.string.Banettite_flavor, R.drawable.carry_vi_prop_43),
  CarryProps(Generation.GenerationVI, R.string.Absolite, R.string.Absolite_flavor, R.drawable.carry_vi_prop_44),
  CarryProps(Generation.GenerationVI, R.string.Glalitite, R.string.Glalitite_flavor, R.drawable.carry_vi_prop_45),
  CarryProps(Generation.GenerationVI, R.string.Salamencite, R.string.Salamencite_flavor, R.drawable.carry_vi_prop_46),
  CarryProps(Generation.GenerationVI, R.string.Metagrossite, R.string.Metagrossite_flavor, R.drawable.carry_vi_prop_47),
  CarryProps(Generation.GenerationVI, R.string.Latiasite, R.string.Latiasite_flavor, R.drawable.carry_vi_prop_48),
  CarryProps(Generation.GenerationVI, R.string.Latiosite, R.string.Latiosite_flavor, R.drawable.carry_vi_prop_49),
  CarryProps(Generation.GenerationVI, R.string.Lopunnite, R.string.Lopunnite_flavor, R.drawable.carry_vi_prop_50),
  CarryProps(Generation.GenerationVI, R.string.Lucarionite, R.string.Lucarionite_flavor, R.drawable.carry_vi_prop_51),
  CarryProps(Generation.GenerationVI, R.string.Garchompite, R.string.Garchompite_flavor, R.drawable.carry_vi_prop_52),
  CarryProps(Generation.GenerationVI, R.string.Abomasite, R.string.Abomasite_flavor, R.drawable.carry_vi_prop_53),
  CarryProps(Generation.GenerationVI, R.string.Galladite, R.string.Galladite_flavor, R.drawable.carry_vi_prop_54),
  CarryProps(Generation.GenerationVI, R.string.Audinite, R.string.Audinite_flavor, R.drawable.carry_vi_prop_55),
  CarryProps(Generation.GenerationVI, R.string.Diancite, R.string.Diancite_flavor, R.drawable.carry_vi_prop_56),
  CarryProps(Generation.GenerationVI, R.string.Red_Orb, R.string.Red_Orb_flavor, R.drawable.carry_vi_prop_57),
  CarryProps(Generation.GenerationVI, R.string.BlueOrb, R.string.BlueOrb_flavor, R.drawable.carry_vi_prop_58),
)

val carryVIIPropsList = listOf(
  CarryProps(Generation.GenerationVII, R.string.Adrenaline_Orb, R.string.Adrenaline_Orb_flavor, R.drawable.carry_vii_prop_1),
  CarryProps(Generation.GenerationVII, R.string.Terrain_Extender, R.string.Terrain_Extender_flavor, R.drawable.carry_vii_prop_2),
  CarryProps(Generation.GenerationVII, R.string.Protective_Pads, R.string.Protective_Pads_flavor, R.drawable.carry_vii_prop_3),
  CarryProps(Generation.GenerationVII, R.string.Electric_Seed, R.string.Electric_Seed_flavor, R.drawable.carry_vii_prop_4),
  CarryProps(Generation.GenerationVII, R.string.Psychic_Seed, R.string.Psychic_Seed_flavor, R.drawable.carry_vii_prop_5),
  CarryProps(Generation.GenerationVII, R.string.Misty_Seed, R.string.Misty_Seed_flavor, R.drawable.carry_vii_prop_6),
  CarryProps(Generation.GenerationVII, R.string.Grassy_Seed, R.string.Grassy_Seed_flavor, R.drawable.carry_vii_prop_7),
  CarryProps(Generation.GenerationVII, R.string.Fighting_Memory, R.string.Fighting_Memory_flavor, R.drawable.carry_vii_prop_8),
  CarryProps(Generation.GenerationVII, R.string.Flying_Memory, R.string.Flying_Memory_flavor, R.drawable.carry_vii_prop_9),
  CarryProps(Generation.GenerationVII, R.string.Poison_Memory, R.string.Poison_Memory_flavor, R.drawable.carry_vii_prop_10),
  CarryProps(Generation.GenerationVII, R.string.Ground_Memory, R.string.Ground_Memory_flavor, R.drawable.carry_vii_prop_11),
  CarryProps(Generation.GenerationVII, R.string.Rock_Memory, R.string.Rock_Memory_flavor, R.drawable.carry_vii_prop_12),
  CarryProps(Generation.GenerationVII, R.string.Bug_Memory, R.string.Bug_Memory_flavor, R.drawable.carry_vii_prop_13),
  CarryProps(Generation.GenerationVII, R.string.Ghost_Memory, R.string.Ghost_Memory_flavor, R.drawable.carry_vii_prop_14),
  CarryProps(Generation.GenerationVII, R.string.Steel_Memory, R.string.Steel_Memory_flavor, R.drawable.carry_vii_prop_15),
  CarryProps(Generation.GenerationVII, R.string.Fire_Memory, R.string.Fire_Memory_flavor, R.drawable.carry_vii_prop_16),
  CarryProps(Generation.GenerationVII, R.string.Water_Memory, R.string.Water_Memory_flavor, R.drawable.carry_vii_prop_17),
  CarryProps(Generation.GenerationVII, R.string.Grass_Memory, R.string.Grass_Memory_flavor, R.drawable.carry_vii_prop_18),
  CarryProps(Generation.GenerationVII, R.string.Electric_Memory, R.string.Electric_Memory_flavor, R.drawable.carry_vii_prop_19),
  CarryProps(Generation.GenerationVII, R.string.Psychic_Memory, R.string.Psychic_Memory_flavor, R.drawable.carry_vii_prop_20),
  CarryProps(Generation.GenerationVII, R.string.Ice_Memory, R.string.Ice_Memory_flavor, R.drawable.carry_vii_prop_21),
  CarryProps(Generation.GenerationVII, R.string.Dragon_Memory, R.string.Dragon_Memory_flavor, R.drawable.carry_vii_prop_22),
  CarryProps(Generation.GenerationVII, R.string.Dark_Memory, R.string.Dark_Memory_flavor, R.drawable.carry_vii_prop_23),
  CarryProps(Generation.GenerationVII, R.string.Fairy_Memory, R.string.Fairy_Memory_flavor, R.drawable.carry_vii_prop_24),
)

val carryVIIIPropsList = listOf(
  CarryProps(Generation.GenerationVIII, R.string.Rusted_Sword, R.string.Rusted_Sword_flavor, R.drawable.carry_viii_prop_1),
  CarryProps(Generation.GenerationVIII, R.string.Rusted_Shield, R.string.Rusted_Shield_flavor, R.drawable.carry_viii_prop_2),
  CarryProps(Generation.GenerationVIII, R.string.Strawberry_Sweet, R.string.Strawberry_Sweet_flavor, R.drawable.carry_viii_prop_3),
  CarryProps(Generation.GenerationVIII, R.string.Love_Sweet, R.string.Love_Sweet_flavor, R.drawable.carry_viii_prop_4),
  CarryProps(Generation.GenerationVIII, R.string.Berry_Sweet, R.string.Berry_Sweet_flavor, R.drawable.carry_viii_prop_5),
  CarryProps(Generation.GenerationVIII, R.string.Clover_Sweet, R.string.Clover_Sweet_flavor, R.drawable.carry_viii_prop_6),
  CarryProps(Generation.GenerationVIII, R.string.Flower_Sweet, R.string.Flower_Sweet_flavor, R.drawable.carry_viii_prop_7),
  CarryProps(Generation.GenerationVIII, R.string.Star_Sweet, R.string.Star_Sweet_flavor, R.drawable.carry_viii_prop_8),
  CarryProps(Generation.GenerationVIII, R.string.Ribbon_Sweet, R.string.Ribbon_Sweet_flavor, R.drawable.carry_viii_prop_9),
  CarryProps(Generation.GenerationVIII, R.string.Throat_Spray, R.string.Throat_Spray_flavor, R.drawable.carry_viii_prop_10),
  CarryProps(Generation.GenerationVIII, R.string.Eject_Pack, R.string.Eject_Pack_flavor, R.drawable.carry_viii_prop_11),
  CarryProps(Generation.GenerationVIII, R.string.Heavy_Duty_Boots, R.string.Heavy_Duty_Boots_flavor, R.drawable.carry_viii_prop_12),
  CarryProps(Generation.GenerationVIII, R.string.Blunder_Policy, R.string.Blunder_Policy_flavor, R.drawable.carry_viii_prop_13),
  CarryProps(Generation.GenerationVIII, R.string.Room_Service, R.string.Room_Service_flavor, R.drawable.carry_viii_prop_14),
  CarryProps(Generation.GenerationVIII, R.string.Utility_Umbrella, R.string.Utility_Umbrella_flavor, R.drawable.carry_viii_prop_15),
)

