package com.heinika.pokeg.ui.gameprops.props

import com.heinika.pokeg.R
import com.heinika.pokeg.utils.Generation

val berry3PropList = listOf(
  BerryProp(Generation.GenerationIII, R.string.Cheri_Berry, R.string.Cheri_Berry_flavor, R.drawable.berry_3_prop_1),
  BerryProp(Generation.GenerationIII, R.string.Chesto_Berry, R.string.Chesto_Berry_flavor, R.drawable.berry_3_prop_2),
  BerryProp(Generation.GenerationIII, R.string.Pecha_Berry, R.string.Pecha_Berry_flavor, R.drawable.berry_3_prop_3),
  BerryProp(Generation.GenerationIII, R.string.Rawst_Berry, R.string.Rawst_Berry_flavor, R.drawable.berry_3_prop_4),
  BerryProp(Generation.GenerationIII, R.string.Aspear_Berry, R.string.Aspear_Berry_flavor, R.drawable.berry_3_prop_5),
  BerryProp(Generation.GenerationIII, R.string.Leppa_Berry, R.string.Leppa_Berry_flavor, R.drawable.berry_3_prop_6),
  BerryProp(Generation.GenerationIII, R.string.Oran_Berry, R.string.Oran_Berry_flavor, R.drawable.berry_3_prop_7),
  BerryProp(Generation.GenerationIII, R.string.Persim_Berry, R.string.Persim_Berry_flavor, R.drawable.berry_3_prop_8),
  BerryProp(Generation.GenerationIII, R.string.Lum_Berry, R.string.Lum_Berry_flavor, R.drawable.berry_3_prop_9),
  BerryProp(Generation.GenerationIII, R.string.Sitrus_Berry, R.string.Sitrus_Berry_flavor, R.drawable.berry_3_prop_10),
  BerryProp(Generation.GenerationIII, R.string.Figy_Berry, R.string.Figy_Berry_flavor, R.drawable.berry_3_prop_11),
  BerryProp(Generation.GenerationIII, R.string.Wiki_Berry, R.string.Wiki_Berry_flavor, R.drawable.berry_3_prop_12),
  BerryProp(Generation.GenerationIII, R.string.Mago_Berry, R.string.Mago_Berry_flavor, R.drawable.berry_3_prop_13),
  BerryProp(Generation.GenerationIII, R.string.Aguav_Berry, R.string.Aguav_Berry_flavor, R.drawable.berry_3_prop_14),
  BerryProp(Generation.GenerationIII, R.string.Iapapa_Berry, R.string.Iapapa_Berry_flavor, R.drawable.berry_3_prop_15),
  BerryProp(Generation.GenerationIII, R.string.Razz_Berry1, R.string.Razz_Berry1_flavor, R.drawable.berry_3_prop_16),
  BerryProp(Generation.GenerationIII, R.string.Razz_Berry2, R.string.Razz_Berry2_flavor, R.drawable.berry_3_prop_17),
  BerryProp(Generation.GenerationIII, R.string.Bluk_Berry, R.string.Bluk_Berry_flavor, R.drawable.berry_3_prop_18),
  BerryProp(Generation.GenerationIII, R.string.Nanab_Berry, R.string.Nanab_Berry_flavor, R.drawable.berry_3_prop_19),
  BerryProp(Generation.GenerationIII, R.string.Wepear_Berry, R.string.Wepear_Berry_flavor, R.drawable.berry_3_prop_20),
  BerryProp(Generation.GenerationIII, R.string.Pinap_Berry1, R.string.Pinap_Berry1_flavor, R.drawable.berry_3_prop_21),
  BerryProp(Generation.GenerationIII, R.string.Pinap_Berry2, R.string.Pinap_Berry2_flavor, R.drawable.berry_3_prop_22),
  BerryProp(Generation.GenerationIII, R.string.Pomeg_Berry, R.string.Pomeg_Berry_flavor, R.drawable.berry_3_prop_23),
  BerryProp(Generation.GenerationIII, R.string.Kelpsy_Berry, R.string.Kelpsy_Berry_flavor, R.drawable.berry_3_prop_24),
  BerryProp(Generation.GenerationIII, R.string.Qualot_Berry, R.string.Qualot_Berry_flavor, R.drawable.berry_3_prop_25),
  BerryProp(Generation.GenerationIII, R.string.Hondew_Berry, R.string.Hondew_Berry_flavor, R.drawable.berry_3_prop_26),
  BerryProp(Generation.GenerationIII, R.string.Grepa_Berry, R.string.Grepa_Berry_flavor, R.drawable.berry_3_prop_27),
  BerryProp(Generation.GenerationIII, R.string.Tamato_Berry, R.string.Tamato_Berry_flavor, R.drawable.berry_3_prop_28),
  BerryProp(Generation.GenerationIII, R.string.Cornn_Berry, R.string.Cornn_Berry_flavor, R.drawable.berry_3_prop_29),
  BerryProp(Generation.GenerationIII, R.string.Magost_Berry, R.string.Magost_Berry_flavor, R.drawable.berry_3_prop_30),
  BerryProp(Generation.GenerationIII, R.string.Rabuta_Berry, R.string.Rabuta_Berry_flavor, R.drawable.berry_3_prop_31),
  BerryProp(Generation.GenerationIII, R.string.Nomel_Berry, R.string.Nomel_Berry_flavor, R.drawable.berry_3_prop_32),
  BerryProp(Generation.GenerationIII, R.string.Spelon_Berry, R.string.Spelon_Berry_flavor, R.drawable.berry_3_prop_33),
  BerryProp(Generation.GenerationIII, R.string.Pamtre_Berry, R.string.Pamtre_Berry_flavor, R.drawable.berry_3_prop_34),
  BerryProp(Generation.GenerationIII, R.string.Watmel_Berry, R.string.Watmel_Berry_flavor, R.drawable.berry_3_prop_35),
  BerryProp(Generation.GenerationIII, R.string.Durin_Berry, R.string.Durin_Berry_flavor, R.drawable.berry_3_prop_36),
  BerryProp(Generation.GenerationIII, R.string.Belue_Berry, R.string.Belue_Berry_flavor, R.drawable.berry_3_prop_37),
  BerryProp(Generation.GenerationIII, R.string.Liechi_Berry, R.string.Liechi_Berry_flavor, R.drawable.berry_3_prop_38),
  BerryProp(Generation.GenerationIII, R.string.Ganlon_Berry, R.string.Ganlon_Berry_flavor, R.drawable.berry_3_prop_39),
  BerryProp(Generation.GenerationIII, R.string.Salac_Berry, R.string.Salac_Berry_flavor, R.drawable.berry_3_prop_40),
  BerryProp(Generation.GenerationIII, R.string.Petaya_Berry, R.string.Petaya_Berry_flavor, R.drawable.berry_3_prop_41),
  BerryProp(Generation.GenerationIII, R.string.Apicot_Berry, R.string.Apicot_Berry_flavor, R.drawable.berry_3_prop_42),
  BerryProp(Generation.GenerationIII, R.string.Lansat_Berry, R.string.Lansat_Berry_flavor, R.drawable.berry_3_prop_43),
  BerryProp(Generation.GenerationIII, R.string.Starf_Berry, R.string.Starf_Berry_flavor, R.drawable.berry_3_prop_44),
  BerryProp(Generation.GenerationIII, R.string.Enigma_Berry, R.string.Enigma_Berry_flavor, R.drawable.berry_3_prop_45),
)

val berry3OnlyRedBluePropList = listOf(
  BerryProp(Generation.GenerationIII, R.string.Pumkin_Berry, R.string.Pumkin_Berry_flavor, R.drawable.berry_3_red_blue_prop_1),
  BerryProp(Generation.GenerationIII, R.string.Drash_Berry, R.string.Drash_Berry_flavor, R.drawable.berry_3_red_blue_prop_2),
  BerryProp(Generation.GenerationIII, R.string.Eggant_Berry, R.string.Eggant_Berry_flavor, R.drawable.berry_3_red_blue_prop_3),
  BerryProp(Generation.GenerationIII, R.string.Strib_Berry, R.string.Strib_Berry_flavor, R.drawable.berry_3_red_blue_prop_4),
  BerryProp(Generation.GenerationIII, R.string.Chilan_Berry, R.string.Chilan_Berry_flavor, R.drawable.berry_3_red_blue_prop_5),
  BerryProp(Generation.GenerationIII, R.string.Nutpea_Berry, R.string.Nutpea_Berry_flavor, R.drawable.berry_3_red_blue_prop_6),
  BerryProp(Generation.GenerationIII, R.string.Ginema_Berry, R.string.Ginema_Berry_flavor, R.drawable.berry_3_red_blue_prop_7),
  BerryProp(Generation.GenerationIII, R.string.Kuo_Berry, R.string.Kuo_Berry_flavor, R.drawable.berry_3_red_blue_prop_8),
  BerryProp(Generation.GenerationIII, R.string.Yago_Berry, R.string.Yago_Berry_flavor, R.drawable.berry_3_red_blue_prop_9),
  BerryProp(Generation.GenerationIII, R.string.Touga_Berry, R.string.Touga_Berry_flavor, R.drawable.berry_3_red_blue_prop_10),
  BerryProp(Generation.GenerationIII, R.string.Niniku_Berry, R.string.Niniku_Berry_flavor, R.drawable.berry_3_red_blue_prop_11),
  BerryProp(Generation.GenerationIII, R.string.Topo_Berry, R.string.Topo_Berry_flavor, R.drawable.berry_3_red_blue_prop_12),
)

val berry4PropList = listOf(
  BerryProp(Generation.GenerationIV, R.string.Occa_Berry, R.string.Occa_Berry_flavor, R.drawable.berry_4_prop_1),
  BerryProp(Generation.GenerationIV, R.string.Passho_Berry, R.string.Passho_Berry_flavor, R.drawable.berry_4_prop_2),
  BerryProp(Generation.GenerationIV, R.string.Wacan_Berry, R.string.Wacan_Berry_flavor, R.drawable.berry_4_prop_3),
  BerryProp(Generation.GenerationIV, R.string.Rindo_Berry, R.string.Rindo_Berry_flavor, R.drawable.berry_4_prop_4),
  BerryProp(Generation.GenerationIV, R.string.Yache_Berry, R.string.Yache_Berry_flavor, R.drawable.berry_4_prop_5),
  BerryProp(Generation.GenerationIV, R.string.Chople_Berry, R.string.Chople_Berry_flavor, R.drawable.berry_4_prop_6),
  BerryProp(Generation.GenerationIV, R.string.Kebia_Berry, R.string.Kebia_Berry_flavor, R.drawable.berry_4_prop_7),
  BerryProp(Generation.GenerationIV, R.string.Shuca_Berry, R.string.Shuca_Berry_flavor, R.drawable.berry_4_prop_8),
  BerryProp(Generation.GenerationIV, R.string.Coba_Berry, R.string.Coba_Berry_flavor, R.drawable.berry_4_prop_9),
  BerryProp(Generation.GenerationIV, R.string.Payapa_Berry, R.string.Payapa_Berry_flavor, R.drawable.berry_4_prop_10),
  BerryProp(Generation.GenerationIV, R.string.Tanga_Berry, R.string.Tanga_Berry_flavor, R.drawable.berry_4_prop_11),
  BerryProp(Generation.GenerationIV, R.string.Charti_Berry, R.string.Charti_Berry_flavor, R.drawable.berry_4_prop_12),
  BerryProp(Generation.GenerationIV, R.string.Kasib_Berry, R.string.Kasib_Berry_flavor, R.drawable.berry_4_prop_13),
  BerryProp(Generation.GenerationIV, R.string.Haban_Berry, R.string.Haban_Berry_flavor, R.drawable.berry_4_prop_14),
  BerryProp(Generation.GenerationIV, R.string.Colbur_Berry, R.string.Colbur_Berry_flavor, R.drawable.berry_4_prop_15),
  BerryProp(Generation.GenerationIV, R.string.Babiri_Berry, R.string.Babiri_Berry_flavor, R.drawable.berry_4_prop_16),
  BerryProp(Generation.GenerationIV, R.string.Chilan_Berry2, R.string.Chilan_Berry2_flavor, R.drawable.berry_4_prop_17),
  BerryProp(Generation.GenerationIV, R.string.Micle_Berry, R.string.Micle_Berry_flavor, R.drawable.berry_4_prop_18),
  BerryProp(Generation.GenerationIV, R.string.Custap_Berry, R.string.Custap_Berry_flavor, R.drawable.berry_4_prop_19),
  BerryProp(Generation.GenerationIV, R.string.Jaboca_Berry, R.string.Jaboca_Berry_flavor, R.drawable.berry_4_prop_20),
  BerryProp(Generation.GenerationIV, R.string.Rowap_Berry, R.string.Rowap_Berry_flavor, R.drawable.berry_4_prop_21),
)

val berry6PropList = listOf(
  BerryProp(Generation.GenerationVI, R.string.Roseli_Berry, R.string.Roseli_Berry_flavor, R.drawable.berry_6_prop_1),
  BerryProp(Generation.GenerationVI, R.string.Kee_Berry, R.string.Kee_Berry_flavor, R.drawable.berry_6_prop_2),
  BerryProp(Generation.GenerationVI, R.string.Maranga_Berry, R.string.Maranga_Berry_flavor, R.drawable.berry_6_prop_3),
)

val berry7PropList = listOf(
  BerryProp(Generation.GenerationVII, R.string.Silver_Razz_Berry, R.string.Silver_Razz_Berry_flavor, R.drawable.berry_7_prop_1),
  BerryProp(Generation.GenerationVII, R.string.Golden_Razz_Berry, R.string.Golden_Razz_Berry_flavor, R.drawable.berry_7_prop_2),
  BerryProp(Generation.GenerationVII, R.string.Silver_Nanab_Berry, R.string.Silver_Nanab_Berry_flavor, R.drawable.berry_7_prop_3),
  BerryProp(Generation.GenerationVII, R.string.Golden_Nanab_Berry, R.string.Golden_Nanab_Berry_flavor, R.drawable.berry_7_prop_4),
  BerryProp(Generation.GenerationVII, R.string.Silver_Pinap_Berry, R.string.Silver_Pinap_Berry_flavor, R.drawable.berry_7_prop_5),
  BerryProp(Generation.GenerationVII, R.string.Golden_Pinap_Berry, R.string.Golden_Pinap_Berry_flavor, R.drawable.berry_7_prop_6),
)