package com.heinika.pokeg.ui.gameprops.props

import androidx.compose.ui.graphics.Color
import com.heinika.pokeg.R
import com.heinika.pokeg.ui.theme.*

val apricornList = listOf(
  Apricorn(R.string.Red_Apricorn, R.string.Red_Apricorn_flavor, R.drawable.apricorn_prop_1),
  Apricorn(R.string.Blue_Apricorn, R.string.Blue_Apricorn_flavor, R.drawable.apricorn_prop_2),
  Apricorn(R.string.Yellow_Apricorn, R.string.Yellow_Apricorn_flavor, R.drawable.apricorn_prop_3),
  Apricorn(R.string.Green_Apricorn, R.string.Green_Apricorn_flavor, R.drawable.apricorn_prop_4),
  Apricorn(R.string.Pink_Apricorn, R.string.Pink_Apricorn_flavor, R.drawable.apricorn_prop_5),
  Apricorn(R.string.White_Apricorn, R.string.White_Apricorn_flavor, R.drawable.apricorn_prop_6),
  Apricorn(R.string.Black_Apricorn, R.string.Black_Apricorn_flavor, R.drawable.apricorn_prop_7)
)

val tcgPropList = listOf(
  TCGProp(R.string.TM1, R.string.TM1_flavor, R.drawable.tcg_prop_1),
  TCGProp(R.string.TM2, R.string.TM2_flavor, R.drawable.tcg_prop_2),
  TCGProp(R.string.HM1, R.string.HM1_flavor, R.drawable.tcg_prop_3),
  TCGProp(R.string.HM2, R.string.HM2_flavor, R.drawable.tcg_prop_4),
  TCGProp(R.string.TR, R.string.TR_flavor, R.drawable.tcg_prop_5),
)

val fieldPropList = listOf(
  FieldProp(R.string.Repel, R.string.Repel_flavor, R.drawable.field_prop_1),
  FieldProp(R.string.Super_Repel, R.string.Super_Repel_flavor, R.drawable.field_prop_2),
  FieldProp(R.string.Max_Repel, R.string.Max_Repel_flavor, R.drawable.field_prop_3),
  FieldProp(R.string.Normal_Box, R.string.Normal_Box_flavor, R.drawable.field_prop_4),
  FieldProp(R.string.Gorgeous_Box, R.string.Gorgeous_Box_flavor, R.drawable.field_prop_5),
  FieldProp(R.string.Blue_Flute, R.string.Blue_Flute_flavor, R.drawable.field_prop_6),
  FieldProp(R.string.Yellow_Flute, R.string.Yellow_Flute_flavor, R.drawable.field_prop_7),
  FieldProp(R.string.Red_Flute, R.string.Red_Flute_flavor, R.drawable.field_prop_8),
  FieldProp(R.string.Black_Flute, R.string.Black_Flute_flavor, R.drawable.field_prop_9),
  FieldProp(R.string.White_Flute, R.string.White_Flute_flavor, R.drawable.field_prop_10),
  FieldProp(R.string.Growth_Mulch, R.string.Growth_Mulch_flavor, R.drawable.field_prop_11),
  FieldProp(R.string.Damp_Mulch, R.string.Damp_Mulch_flavor, R.drawable.field_prop_12),
  FieldProp(R.string.Stable_Mulch, R.string.Stable_Mulch_flavor, R.drawable.field_prop_13),
  FieldProp(R.string.Gooey_Mulch, R.string.Gooey_Mulch_flavor, R.drawable.field_prop_14),
  FieldProp(R.string.Rich_Mulch, R.string.Rich_Mulch_flavor, R.drawable.field_prop_15),
  FieldProp(R.string.Surprise_Mulch, R.string.Surprise_Mulch_flavor, R.drawable.field_prop_16),
  FieldProp(R.string.Boost_Mulch, R.string.Boost_Mulch_flavor, R.drawable.field_prop_17),
  FieldProp(R.string.Amaze_Mulch, R.string.Amaze_Mulch_flavor, R.drawable.field_prop_18),
  FieldProp(R.string.Honey, R.string.Honey_flavor, R.drawable.field_prop_19),
  FieldProp(R.string.Odd_Keystone, R.string.Odd_Keystone_flavor, R.drawable.field_prop_20),
  FieldProp(R.string.Pass_Orb, R.string.Pass_Orb_flavor, R.drawable.field_prop_21),
  FieldProp(R.string.Discount_Coupon, R.string.Discount_Coupon_flavor, R.drawable.field_prop_22),
  FieldProp(R.string.Festival_Ticket, R.string.Festival_Ticket_flavor, R.drawable.field_prop_23),
  FieldProp(R.string.Red_Nectar, R.string.Red_Nectar_flavor, R.drawable.field_prop_24),
  FieldProp(R.string.Yellow_Nectar, R.string.Yellow_Nectar_flavor, R.drawable.field_prop_25),
  FieldProp(R.string.Pink_Nectar, R.string.Pink_Nectar_flavor, R.drawable.field_prop_26),
  FieldProp(R.string.Purple_Nectar, R.string.Purple_Nectar_flavor, R.drawable.field_prop_27),
  FieldProp(R.string.Leaf_Letter1, R.string.Leaf_Letter1_flavor, R.drawable.field_prop_28),
  FieldProp(R.string.Leaf_Letter2, R.string.Leaf_Letter2_flavor, R.drawable.field_prop_29),
  FieldProp(R.string.Small_Bouquet, R.string.Small_Bouquet_flavor, R.drawable.field_prop_30),
  FieldProp(R.string.Lure, R.string.Lure_flavor, R.drawable.field_prop_31),
  FieldProp(R.string.Super_Lure, R.string.Super_Lure_flavor, R.drawable.field_prop_32),
  FieldProp(R.string.Max_Lure, R.string.Max_Lure_flavor, R.drawable.field_prop_33),
  FieldProp(R.string.Wishing_Chip, R.string.Wishing_Chip_flavor, R.drawable.field_prop_34),
  FieldProp(R.string.Wishing_Pieces, R.string.Wishing_Pieces_flavor, R.drawable.field_prop_35),
  FieldProp(R.string.HP_Up, R.string.HP_Up_flavor, R.drawable.field_prop_36),
  FieldProp(R.string.Protein, R.string.Protein_flavor, R.drawable.field_prop_37),
  FieldProp(R.string.Iron, R.string.Iron_flavor, R.drawable.field_prop_38),
  FieldProp(R.string.Carbos, R.string.Carbos_flavor, R.drawable.field_prop_39),
  FieldProp(R.string.Calcium, R.string.Calcium_flavor, R.drawable.field_prop_40),
  FieldProp(R.string.PP_Up, R.string.PP_Up_flavor, R.drawable.field_prop_41),
  FieldProp(R.string.Zinc, R.string.Zinc_flavor, R.drawable.field_prop_42),
  FieldProp(R.string.PP_Max, R.string.PP_Max_flavor, R.drawable.field_prop_43),
  FieldProp(R.string.Ability_Capsule, R.string.Ability_Capsule_flavor, R.drawable.field_prop_44),
  FieldProp(R.string.Health_Wing, R.string.Health_Wing_flavor, R.drawable.field_prop_45),
  FieldProp(R.string.Muscle_Wing, R.string.Muscle_Wing_flavor, R.drawable.field_prop_46),
  FieldProp(R.string.Resist_Wing, R.string.Resist_Wing_flavor, R.drawable.field_prop_47),
  FieldProp(R.string.Genius_Wing, R.string.Genius_Wing_flavor, R.drawable.field_prop_48),
  FieldProp(R.string.Clever_Wing, R.string.Clever_Wing_flavor, R.drawable.field_prop_49),
  FieldProp(R.string.Swift_Wing, R.string.Swift_Wing_flavor, R.drawable.field_prop_50),
  FieldProp(R.string.Lonely_Mint, R.string.Lonely_Mint_flavor, R.drawable.field_prop_51),
  FieldProp(R.string.Adamant_Mint, R.string.Adamant_Mint_flavor, R.drawable.field_prop_52),
  FieldProp(R.string.Naughty_Mint, R.string.Naughty_Mint_flavor, R.drawable.field_prop_53),
  FieldProp(R.string.Brave_Mint, R.string.Brave_Mint_flavor, R.drawable.field_prop_54),
  FieldProp(R.string.Bold_Mint, R.string.Bold_Mint_flavor, R.drawable.field_prop_55),
  FieldProp(R.string.Impish_Mint, R.string.Impish_Mint_flavor, R.drawable.field_prop_56),
  FieldProp(R.string.Lax_Mint, R.string.Lax_Mint_flavor, R.drawable.field_prop_57),
  FieldProp(R.string.Relaxed_Mint, R.string.Relaxed_Mint_flavor, R.drawable.field_prop_58),
  FieldProp(R.string.Modest_Mint, R.string.Modest_Mint_flavor, R.drawable.field_prop_59),
  FieldProp(R.string.Mild_Mint, R.string.Mild_Mint_flavor, R.drawable.field_prop_60),
  FieldProp(R.string.Rash_Mint, R.string.Rash_Mint_flavor, R.drawable.field_prop_61),
  FieldProp(R.string.Quiet_Mint, R.string.Quiet_Mint_flavor, R.drawable.field_prop_62),
  FieldProp(R.string.Calm_Mint, R.string.Calm_Mint_flavor, R.drawable.field_prop_63),
  FieldProp(R.string.Gentle_Mint, R.string.Gentle_Mint_flavor, R.drawable.field_prop_64),
  FieldProp(R.string.Careful_Mint, R.string.Careful_Mint_flavor, R.drawable.field_prop_65),
  FieldProp(R.string.Sassy_Mint, R.string.Sassy_Mint_flavor, R.drawable.field_prop_66),
  FieldProp(R.string.Timid_Mint, R.string.Timid_Mint_flavor, R.drawable.field_prop_67),
  FieldProp(R.string.Hasty_Mint, R.string.Hasty_Mint_flavor, R.drawable.field_prop_68),
  FieldProp(R.string.Jolly_Mint, R.string.Jolly_Mint_flavor, R.drawable.field_prop_69),
  FieldProp(R.string.Naive_Mint, R.string.Naive_Mint_flavor, R.drawable.field_prop_70),
  FieldProp(R.string.Serious_Mint, R.string.Serious_Mint_flavor, R.drawable.field_prop_71),
  FieldProp(R.string.Dynamax_Crystal, R.string.Dynamax_Crystal_flavor, R.drawable.field_prop_72),
  FieldProp(R.string.Digger_Drill, R.string.Digger_Drill_flavor, R.drawable.field_prop_73),
  FieldProp(R.string.Kanto_Slate, R.string.Kanto_Slate_flavor, R.drawable.field_prop_74),
  FieldProp(R.string.Johto_Slate, R.string.Johto_Slate_flavor, R.drawable.field_prop_75),
  FieldProp(R.string.Soul_Slate, R.string.Soul_Slate_flavor, R.drawable.field_prop_76),
  FieldProp(R.string.Rainbow_Slate, R.string.Rainbow_Slate_flavor, R.drawable.field_prop_77),
  FieldProp(R.string.Squall_Slate, R.string.Squall_Slate_flavor, R.drawable.field_prop_78),
  FieldProp(R.string.Oceanic_Slate, R.string.Oceanic_Slate_flavor, R.drawable.field_prop_79),
  FieldProp(R.string.Tectonic_Slate, R.string.Tectonic_Slate_flavor, R.drawable.field_prop_80),
  FieldProp(R.string.Stratospheric_Slate, R.string.Stratospheric_Slate_flavor, R.drawable.field_prop_81),
  FieldProp(R.string.Genome_Slate, R.string.Genome_Slate_flavor, R.drawable.field_prop_82),
  FieldProp(R.string.Discovery_Slate, R.string.Discovery_Slate_flavor, R.drawable.field_prop_83),
  FieldProp(R.string.Distortion_Slate, R.string.Distortion_Slate_flavor, R.drawable.field_prop_84),
)

val candyPropList = listOf(
  CandyProp(R.string.Rare_Candy, R.string.Rare_Candy_flavor, R.drawable.candy_prop_1),
  CandyProp(R.string.Health_Candy, R.string.Health_Candy_flavor, R.drawable.candy_prop_2),
  CandyProp(R.string.Mighty_Candy, R.string.Mighty_Candy_flavor, R.drawable.candy_prop_3),
  CandyProp(R.string.Tough_Candy, R.string.Tough_Candy_flavor, R.drawable.candy_prop_4),
  CandyProp(R.string.Smart_Candy, R.string.Smart_Candy_flavor, R.drawable.candy_prop_5),
  CandyProp(R.string.Courage_Candy, R.string.Courage_Candy_flavor, R.drawable.candy_prop_6),
  CandyProp(R.string.Quick_Candy, R.string.Quick_Candy_flavor, R.drawable.candy_prop_7),
  CandyProp(R.string.Health_Candy_L, R.string.Health_Candy_L_flavor, R.drawable.candy_prop_8),
  CandyProp(R.string.Mighty_Candy_L, R.string.Mighty_Candy_L_flavor, R.drawable.candy_prop_9),
  CandyProp(R.string.Tough_Candy_L, R.string.Tough_Candy_L_flavor, R.drawable.candy_prop_10),
  CandyProp(R.string.Smart_Candy_L, R.string.Smart_Candy_L_flavor, R.drawable.candy_prop_11),
  CandyProp(R.string.Courage_Candy_L, R.string.Courage_Candy_L_flavor, R.drawable.candy_prop_12),
  CandyProp(R.string.Quick_Candy_L, R.string.Quick_Candy_L_flavor, R.drawable.candy_prop_13),
  CandyProp(R.string.Health_Candy_XL, R.string.Health_Candy_XL_flavor, R.drawable.candy_prop_14),
  CandyProp(R.string.Mighty_Candy_XL, R.string.Mighty_Candy_XL_flavor, R.drawable.candy_prop_15),
  CandyProp(R.string.Tough_Candy_XL, R.string.Tough_Candy_XL_flavor, R.drawable.candy_prop_16),
  CandyProp(R.string.Smart_Candy_XL, R.string.Smart_Candy_XL_flavor, R.drawable.candy_prop_17),
  CandyProp(R.string.Courage_Candy_XL, R.string.Courage_Candy_XL_flavor, R.drawable.candy_prop_18),
  CandyProp(R.string.Quick_Candy_XL, R.string.Quick_Candy_XL_flavor, R.drawable.candy_prop_19),
  CandyProp(R.string.Bulbasaur_Candy, R.string.Bulbasaur_Candy_flavor, R.drawable.candy_prop_20),
  CandyProp(R.string.Charmander_Candy, R.string.Charmander_Candy_flavor, R.drawable.candy_prop_21),
  CandyProp(R.string.Squirtle_Candy, R.string.Squirtle_Candy_flavor, R.drawable.candy_prop_22),
  CandyProp(R.string.Caterpie_Candy, R.string.Caterpie_Candy_flavor, R.drawable.candy_prop_23),
  CandyProp(R.string.Weedle_Candy, R.string.Weedle_Candy_flavor, R.drawable.candy_prop_24),
  CandyProp(R.string.Pidgey_Candy, R.string.Pidgey_Candy_flavor, R.drawable.candy_prop_25),
  CandyProp(R.string.Rattata_Candy, R.string.Rattata_Candy_flavor, R.drawable.candy_prop_26),
  CandyProp(R.string.Spearow_Candy, R.string.Spearow_Candy_flavor, R.drawable.candy_prop_27),
  CandyProp(R.string.Ekans_Candy, R.string.Ekans_Candy_flavor, R.drawable.candy_prop_28),
  CandyProp(R.string.Pikachu_Candy, R.string.Pikachu_Candy_flavor, R.drawable.candy_prop_29),
  CandyProp(R.string.Sandshrew_Candy, R.string.Sandshrew_Candy_flavor, R.drawable.candy_prop_30),
  CandyProp(R.string.Nidoran1_Candy, R.string.Nidoran1_Candy_flavor, R.drawable.candy_prop_31),
  CandyProp(R.string.Nidoran2_Candy, R.string.Nidoran2_Candy_flavor, R.drawable.candy_prop_32),
  CandyProp(R.string.Clefairy_Candy, R.string.Clefairy_Candy_flavor, R.drawable.candy_prop_33),
  CandyProp(R.string.Vulpix_Candy, R.string.Vulpix_Candy_flavor, R.drawable.candy_prop_34),
  CandyProp(R.string.Jigglypuff_Candy, R.string.Jigglypuff_Candy_flavor, R.drawable.candy_prop_35),
  CandyProp(R.string.Zubat_Candy, R.string.Zubat_Candy_flavor, R.drawable.candy_prop_36),
  CandyProp(R.string.Oddish_Candy, R.string.Oddish_Candy_flavor, R.drawable.candy_prop_37),
  CandyProp(R.string.Paras_Candy, R.string.Paras_Candy_flavor, R.drawable.candy_prop_38),
  CandyProp(R.string.Venonat_Candy, R.string.Venonat_Candy_flavor, R.drawable.candy_prop_39),
  CandyProp(R.string.Diglett_Candy, R.string.Diglett_Candy_flavor, R.drawable.candy_prop_40),
  CandyProp(R.string.Meowth_Candy, R.string.Meowth_Candy_flavor, R.drawable.candy_prop_41),
  CandyProp(R.string.Psyduck_Candy, R.string.Psyduck_Candy_flavor, R.drawable.candy_prop_42),
  CandyProp(R.string.Mankey_Candy, R.string.Mankey_Candy_flavor, R.drawable.candy_prop_43),
  CandyProp(R.string.Growlithe_Candy, R.string.Growlithe_Candy_flavor, R.drawable.candy_prop_44),
  CandyProp(R.string.Poliwag_Candy, R.string.Poliwag_Candy_flavor, R.drawable.candy_prop_45),
  CandyProp(R.string.Abra_Candy, R.string.Abra_Candy_flavor, R.drawable.candy_prop_46),
  CandyProp(R.string.Machop_Candy, R.string.Machop_Candy_flavor, R.drawable.candy_prop_47),
  CandyProp(R.string.Bellsprout_Candy, R.string.Bellsprout_Candy_flavor, R.drawable.candy_prop_48),
  CandyProp(R.string.Tentacool_Candy, R.string.Tentacool_Candy_flavor, R.drawable.candy_prop_49),
  CandyProp(R.string.Geodude_Candy, R.string.Geodude_Candy_flavor, R.drawable.candy_prop_50),
  CandyProp(R.string.Ponyta_Candy, R.string.Ponyta_Candy_flavor, R.drawable.candy_prop_51),
  CandyProp(R.string.Slowpoke_Candy, R.string.Slowpoke_Candy_flavor, R.drawable.candy_prop_52),
  CandyProp(R.string.Magnemite_Candy, R.string.Magnemite_Candy_flavor, R.drawable.candy_prop_53),
  CandyProp(R.string.Farfetch_d_Candy, R.string.Farfetch_d_Candy_flavor, R.drawable.candy_prop_54),
  CandyProp(R.string.Doduo_Candy, R.string.Doduo_Candy_flavor, R.drawable.candy_prop_55),
  CandyProp(R.string.Seel_Candy, R.string.Seel_Candy_flavor, R.drawable.candy_prop_56),
  CandyProp(R.string.Grimer_Candy, R.string.Grimer_Candy_flavor, R.drawable.candy_prop_57),
  CandyProp(R.string.Shellder_Candy, R.string.Shellder_Candy_flavor, R.drawable.candy_prop_58),
  CandyProp(R.string.Gastly_Candy, R.string.Gastly_Candy_flavor, R.drawable.candy_prop_59),
  CandyProp(R.string.Onix_Candy, R.string.Onix_Candy_flavor, R.drawable.candy_prop_60),
  CandyProp(R.string.Drowzee_Candy, R.string.Drowzee_Candy_flavor, R.drawable.candy_prop_61),
  CandyProp(R.string.Krabby_Candy, R.string.Krabby_Candy_flavor, R.drawable.candy_prop_62),
  CandyProp(R.string.Voltorb_Candy, R.string.Voltorb_Candy_flavor, R.drawable.candy_prop_63),
  CandyProp(R.string.Exeggcute_Candy, R.string.Exeggcute_Candy_flavor, R.drawable.candy_prop_64),
  CandyProp(R.string.Cubone_Candy, R.string.Cubone_Candy_flavor, R.drawable.candy_prop_65),
  CandyProp(R.string.Hitmonlee_Candy, R.string.Hitmonlee_Candy_flavor, R.drawable.candy_prop_66),
  CandyProp(R.string.Hitmonchan_Candy, R.string.Hitmonchan_Candy_flavor, R.drawable.candy_prop_67),
  CandyProp(R.string.Lickitung_Candy, R.string.Lickitung_Candy_flavor, R.drawable.candy_prop_68),
  CandyProp(R.string.Koffing_Candy, R.string.Koffing_Candy_flavor, R.drawable.candy_prop_69),
  CandyProp(R.string.Rhyhorn_Candy, R.string.Rhyhorn_Candy_flavor, R.drawable.candy_prop_70),
  CandyProp(R.string.Chansey_Candy, R.string.Chansey_Candy_flavor, R.drawable.candy_prop_71),
  CandyProp(R.string.Tangela_Candy, R.string.Tangela_Candy_flavor, R.drawable.candy_prop_72),
  CandyProp(R.string.Kangaskhan_Candy, R.string.Kangaskhan_Candy_flavor, R.drawable.candy_prop_73),
  CandyProp(R.string.Horsea_Candy, R.string.Horsea_Candy_flavor, R.drawable.candy_prop_74),
  CandyProp(R.string.Goldeen_Candy, R.string.Goldeen_Candy_flavor, R.drawable.candy_prop_75),
  CandyProp(R.string.Staryu_Candy, R.string.Staryu_Candy_flavor, R.drawable.candy_prop_76),
  CandyProp(R.string.Mr_Mime_Candy, R.string.Mr_Mime_Candy_flavor, R.drawable.candy_prop_77),
  CandyProp(R.string.Scyther_Candy, R.string.Scyther_Candy_flavor, R.drawable.candy_prop_78),
  CandyProp(R.string.Jynx_Candy, R.string.Jynx_Candy_flavor, R.drawable.candy_prop_79),
  CandyProp(R.string.Electabuzz_Candy, R.string.Electabuzz_Candy_flavor, R.drawable.candy_prop_80),
  CandyProp(R.string.Magmar_Candy, R.string.Magmar_Candy_flavor, R.drawable.candy_prop_81),
  CandyProp(R.string.Pinsir_Candy, R.string.Pinsir_Candy_flavor, R.drawable.candy_prop_82),
  CandyProp(R.string.Tauros_Candy, R.string.Tauros_Candy_flavor, R.drawable.candy_prop_83),
  CandyProp(R.string.Magikarp_Candy, R.string.Magikarp_Candy_flavor, R.drawable.candy_prop_84),
  CandyProp(R.string.Lapras_Candy, R.string.Lapras_Candy_flavor, R.drawable.candy_prop_85),
  CandyProp(R.string.Ditto_Candy, R.string.Ditto_Candy_flavor, R.drawable.candy_prop_86),
  CandyProp(R.string.Eevee_Candy, R.string.Eevee_Candy_flavor, R.drawable.candy_prop_87),
  CandyProp(R.string.Porygon_Candy, R.string.Porygon_Candy_flavor, R.drawable.candy_prop_88),
  CandyProp(R.string.Omanyte_Candy, R.string.Omanyte_Candy_flavor, R.drawable.candy_prop_89),
  CandyProp(R.string.Kabuto_Candy, R.string.Kabuto_Candy_flavor, R.drawable.candy_prop_90),
  CandyProp(R.string.Aerodactyl_Candy, R.string.Aerodactyl_Candy_flavor, R.drawable.candy_prop_91),
  CandyProp(R.string.Snorlax_Candy, R.string.Snorlax_Candy_flavor, R.drawable.candy_prop_92),
  CandyProp(R.string.Articuno_Candy, R.string.Articuno_Candy_flavor, R.drawable.candy_prop_93),
  CandyProp(R.string.Zapdos_Candy, R.string.Zapdos_Candy_flavor, R.drawable.candy_prop_94),
  CandyProp(R.string.Moltres_Candy, R.string.Moltres_Candy_flavor, R.drawable.candy_prop_95),
  CandyProp(R.string.Dratini_Candy, R.string.Dratini_Candy_flavor, R.drawable.candy_prop_96),
  CandyProp(R.string.Mewtwo_Candy, R.string.Mewtwo_Candy_flavor, R.drawable.candy_prop_97),
  CandyProp(R.string.Mew_Candy, R.string.Mew_Candy_flavor, R.drawable.candy_prop_98),
  CandyProp(R.string.Meltan, R.string.Meltan_flavor, R.drawable.candy_prop_99),
  CandyProp(R.string.Exp_Candy_XS, R.string.Exp_Candy_XS_flavor, R.drawable.candy_prop_100),
  CandyProp(R.string.Exp_Candy_S, R.string.Exp_Candy_S_flavor, R.drawable.candy_prop_101),
  CandyProp(R.string.Exp_Candy_M, R.string.Exp_Candy_M_flavor, R.drawable.candy_prop_102),
  CandyProp(R.string.Exp_Candy_L, R.string.Exp_Candy_L_flavor, R.drawable.candy_prop_103),
  CandyProp(R.string.Exp_Candy_XL, R.string.Exp_Candy_XL_flavor, R.drawable.candy_prop_104),
  CandyProp(R.string.Dynamax_Candy, R.string.Dynamax_Candy_flavor, R.drawable.candy_prop_105),
)

val zMasterList = listOf(
  ZProp(R.string.Normalium_Z_master, R.string.Normalium_Z_master_flavor, R.drawable.z_prop_1),
  ZProp(R.string.Firium_Z_master, R.string.Firium_Z_master_flavor, R.drawable.z_prop_2),
  ZProp(R.string.Waterium_Z_master, R.string.Waterium_Z_master_flavor, R.drawable.z_prop_3),
  ZProp(R.string.Electrium_Z_master, R.string.Electrium_Z_master_flavor, R.drawable.z_prop_4),
  ZProp(R.string.Grassium_Z_master, R.string.Grassium_Z_master_flavor, R.drawable.z_prop_5),
  ZProp(R.string.Icium_Z_master, R.string.Icium_Z_master_flavor, R.drawable.z_prop_6),
  ZProp(R.string.Fightinium_Z_master, R.string.Fightinium_Z_master_flavor, R.drawable.z_prop_7),
  ZProp(R.string.Poisonium_Z_master, R.string.Poisonium_Z_master_flavor, R.drawable.z_prop_8),
  ZProp(R.string.Groundium_Z_master, R.string.Groundium_Z_master_flavor, R.drawable.z_prop_9),
  ZProp(R.string.Flyinium_Z_master, R.string.Flyinium_Z_master_flavor, R.drawable.z_prop_10),
  ZProp(R.string.Psychium_Z_master, R.string.Psychium_Z_master_flavor, R.drawable.z_prop_11),
  ZProp(R.string.Buginium_Z_master, R.string.Buginium_Z_master_flavor, R.drawable.z_prop_12),
  ZProp(R.string.Rockium_Z_master, R.string.Rockium_Z_master_flavor, R.drawable.z_prop_13),
  ZProp(R.string.Ghostium_Z_master, R.string.Ghostium_Z_master_flavor, R.drawable.z_prop_14),
  ZProp(R.string.Dragonium_Z_master, R.string.Dragonium_Z_master_flavor, R.drawable.z_prop_15),
  ZProp(R.string.Darkinium_Z_master, R.string.Darkinium_Z_master_flavor, R.drawable.z_prop_16),
  ZProp(R.string.Steelium_Z_master, R.string.Steelium_Z_master_flavor, R.drawable.z_prop_17),
  ZProp(R.string.Fairium_Z_master, R.string.Fairium_Z_master_flavor, R.drawable.z_prop_18),
  ZProp(R.string.Pikanium_Z_master, R.string.Pikanium_Z_master_flavor, R.drawable.z_prop_19),
  ZProp(R.string.Decidium_Z_master, R.string.Decidium_Z_master_flavor, R.drawable.z_prop_20),
  ZProp(R.string.Incinium_Z_master, R.string.Incinium_Z_master_flavor, R.drawable.z_prop_21),
  ZProp(R.string.Primarium_Z_master, R.string.Primarium_Z_master_flavor, R.drawable.z_prop_22),
  ZProp(R.string.Tapunium_Z_master, R.string.Tapunium_Z_master_flavor, R.drawable.z_prop_23),
  ZProp(R.string.Marshadium_Z_master, R.string.Marshadium_Z_master_flavor, R.drawable.z_prop_24),
  ZProp(R.string.Aloraichium_Z_master, R.string.Aloraichium_Z_master_flavor, R.drawable.z_prop_25),
  ZProp(R.string.Snorlium_Z_master, R.string.Snorlium_Z_master_flavor, R.drawable.z_prop_26),
  ZProp(R.string.Eevium_Z_master, R.string.Eevium_Z_master_flavor, R.drawable.z_prop_27),
  ZProp(R.string.Mewnium_Z_master, R.string.Mewnium_Z_master_flavor, R.drawable.z_prop_28),
  ZProp(R.string.Pikashunium_Z_master, R.string.Pikashunium_Z_master_flavor, R.drawable.z_prop_29),
  ZProp(R.string.Solganium_Z_master, R.string.Solganium_Z_master_flavor, R.drawable.z_prop_30),
  ZProp(R.string.Lunalium_Z_master, R.string.Lunalium_Z_master_flavor, R.drawable.z_prop_31),
  ZProp(R.string.Ultranecrozium_Z_master, R.string.Ultranecrozium_Z_master_flavor, R.drawable.z_prop_32),
  ZProp(R.string.Mimikium_Z_master, R.string.Mimikium_Z_master_flavor, R.drawable.z_prop_33),
  ZProp(R.string.Lycanium_Z_master, R.string.Lycanium_Z_master_flavor, R.drawable.z_prop_34),
  ZProp(R.string.Kommonium_Z_master, R.string.Kommonium_Z_master_flavor, R.drawable.z_prop_35),
)

val zPokemonList = listOf(
  ZProp(R.string.Normalium_Z_pokemon, R.string.Normalium_Z_pokemon_flavor, R.drawable.z_prop_1),
  ZProp(R.string.Firium_Z_pokemon, R.string.Firium_Z_pokemon_flavor, R.drawable.z_prop_2),
  ZProp(R.string.Waterium_Z_pokemon, R.string.Waterium_Z_pokemon_flavor, R.drawable.z_prop_3),
  ZProp(R.string.Electrium_Z_pokemon, R.string.Electrium_Z_pokemon_flavor, R.drawable.z_prop_4),
  ZProp(R.string.Grassium_Z_pokemon, R.string.Grassium_Z_pokemon_flavor, R.drawable.z_prop_5),
  ZProp(R.string.Icium_Z_pokemon, R.string.Icium_Z_pokemon_flavor, R.drawable.z_prop_6),
  ZProp(R.string.Fightinium_Z_pokemon, R.string.Fightinium_Z_pokemon_flavor, R.drawable.z_prop_7),
  ZProp(R.string.Poisonium_Z_pokemon, R.string.Poisonium_Z_pokemon_flavor, R.drawable.z_prop_8),
  ZProp(R.string.Groundium_Z_pokemon, R.string.Groundium_Z_pokemon_flavor, R.drawable.z_prop_9),
  ZProp(R.string.Flyinium_Z_pokemon, R.string.Flyinium_Z_pokemon_flavor, R.drawable.z_prop_10),
  ZProp(R.string.Psychium_Z_pokemon, R.string.Psychium_Z_pokemon_flavor, R.drawable.z_prop_11),
  ZProp(R.string.Buginium_Z_pokemon, R.string.Buginium_Z_pokemon_flavor, R.drawable.z_prop_12),
  ZProp(R.string.Rockium_Z_pokemon, R.string.Rockium_Z_pokemon_flavor, R.drawable.z_prop_13),
  ZProp(R.string.Ghostium_Z_pokemon, R.string.Ghostium_Z_pokemon_flavor, R.drawable.z_prop_14),
  ZProp(R.string.Dragonium_Z_pokemon, R.string.Dragonium_Z_pokemon_flavor, R.drawable.z_prop_15),
  ZProp(R.string.Darkinium_Z_pokemon, R.string.Darkinium_Z_pokemon_flavor, R.drawable.z_prop_16),
  ZProp(R.string.Steelium_Z_pokemon, R.string.Steelium_Z_pokemon_flavor, R.drawable.z_prop_17),
  ZProp(R.string.Fairium_Z_pokemon, R.string.Fairium_Z_pokemon_flavor, R.drawable.z_prop_18),
  ZProp(R.string.Pikanium_Z_pokemon, R.string.Pikanium_Z_pokemon_flavor, R.drawable.z_prop_19),
  ZProp(R.string.Decidium_Z_pokemon, R.string.Decidium_Z_pokemon_flavor, R.drawable.z_prop_20),
  ZProp(R.string.Incinium_Z_pokemon, R.string.Incinium_Z_pokemon_flavor, R.drawable.z_prop_21),
  ZProp(R.string.Primarium_Z_pokemon, R.string.Primarium_Z_pokemon_flavor, R.drawable.z_prop_22),
  ZProp(R.string.Tapunium_Z_pokemon, R.string.Tapunium_Z_pokemon_flavor, R.drawable.z_prop_23),
  ZProp(R.string.Marshadium_Z_pokemon, R.string.Marshadium_Z_pokemon_flavor, R.drawable.z_prop_24),
  ZProp(R.string.Aloraichium_Z_pokemon, R.string.Aloraichium_Z_pokemon_flavor, R.drawable.z_prop_25),
  ZProp(R.string.Snorlium_Z_pokemon, R.string.Snorlium_Z_pokemon_flavor, R.drawable.z_prop_26),
  ZProp(R.string.Eevium_Z_pokemon, R.string.Eevium_Z_pokemon_flavor, R.drawable.z_prop_27),
  ZProp(R.string.Mewnium_Z_pokemon, R.string.Mewnium_Z_pokemon_flavor, R.drawable.z_prop_28),
  ZProp(R.string.Pikashunium_Z_pokemon, R.string.Pikashunium_Z_pokemon_flavor, R.drawable.z_prop_29),
  ZProp(R.string.Solganium_Z_pokemon, R.string.Solganium_Z_pokemon_flavor, R.drawable.z_prop_30),
  ZProp(R.string.Lunalium_Z_pokemon, R.string.Lunalium_Z_pokemon_flavor, R.drawable.z_prop_31),
  ZProp(R.string.Ultranecrozium_Z_pokemon, R.string.Ultranecrozium_Z_pokemon_flavor, R.drawable.z_prop_32),
  ZProp(R.string.Mimikium_Z_pokemon, R.string.Mimikium_Z_pokemon_flavor, R.drawable.z_prop_33),
  ZProp(R.string.Lycanium_Z_pokemon, R.string.Lycanium_Z_pokemon_flavor, R.drawable.z_prop_34),
  ZProp(R.string.Kommonium_Z_pokemon, R.string.Kommonium_Z_pokemon_flavor, R.drawable.z_prop_35),
)


val swapPropList = listOf(
  SwapProps(R.string.Red_Shard, R.string.Red_Shard_flavor, R.drawable.swap_prop_1),
  SwapProps(R.string.Blue_Shard, R.string.Blue_Shard_flavor, R.drawable.swap_prop_2),
  SwapProps(R.string.Yellow_Shard, R.string.Yellow_Shard_flavor, R.drawable.swap_prop_3),
  SwapProps(R.string.Green_Shard, R.string.Green_Shard_flavor, R.drawable.swap_prop_4),
  SwapProps(R.string.Shoal_Salt, R.string.Shoal_Salt_flavor, R.drawable.swap_prop_5),
  SwapProps(R.string.Shoal_Shell, R.string.Shoal_Shell_flavor, R.drawable.swap_prop_6),
  SwapProps(R.string.Heart_Scale, R.string.Heart_Scale_flavor, R.drawable.swap_prop_7),
  SwapProps(R.string.Galarica_Twig, R.string.Galarica_Twig_flavor, R.drawable.swap_prop_8),
  SwapProps(R.string.Armorite_Ore, R.string.Armorite_Ore_flavor, R.drawable.swap_prop_9),
  SwapProps(R.string.Dynite_Ore, R.string.Dynite_Ore_flavor, R.drawable.swap_prop_10),
  SwapProps(
    R.string.Mysterious_Shard_S,
    R.string.Mysterious_Shard_S_flavor,
    R.drawable.swap_prop_11
  ),
  SwapProps(
    R.string.Mysterious_Shard_L,
    R.string.Mysterious_Shard_L_flavor,
    R.drawable.swap_prop_12
  ),
)

val pokeballList = listOf(
  Pokeball(R.string.Poké_Ball, R.string.Poké_Ball_flavor, R.drawable.pokeball_prop_1),
  Pokeball(R.string.Great_Ball, R.string.Great_Ball_flavor, R.drawable.pokeball_prop_2),
  Pokeball(R.string.Ultra_Ball, R.string.Ultra_Ball_flavor, R.drawable.pokeball_prop_3),
  Pokeball(R.string.Safari_Ball, R.string.Safari_Ball_flavor, R.drawable.pokeball_prop_4),
  Pokeball(R.string.Master_Ball, R.string.Master_Ball_flavor, R.drawable.pokeball_prop_5),
  Pokeball(R.string.Fast_Ball, R.string.Fast_Ball_flavor, R.drawable.pokeball_prop_6),
  Pokeball(R.string.Level_Ball, R.string.Level_Ball_flavor, R.drawable.pokeball_prop_7),
  Pokeball(R.string.Lure_Ball, R.string.Lure_Ball_flavor, R.drawable.pokeball_prop_8),
  Pokeball(R.string.Heavy_Ball, R.string.Heavy_Ball_flavor, R.drawable.pokeball_prop_9),
  Pokeball(R.string.Love_Ball, R.string.Love_Ball_flavor, R.drawable.pokeball_prop_10),
  Pokeball(R.string.Friend_Ball, R.string.Friend_Ball_flavor, R.drawable.pokeball_prop_11),
  Pokeball(R.string.Moon_Ball, R.string.Moon_Ball_flavor, R.drawable.pokeball_prop_12),
  Pokeball(R.string.Sport_Ball, R.string.Sport_Ball_flavor, R.drawable.pokeball_prop_13),
  Pokeball(R.string.Park_Ball, R.string.Park_Ball_flavor, R.drawable.pokeball_prop_14),
  Pokeball(R.string.Net_Ball, R.string.Net_Ball_flavor, R.drawable.pokeball_prop_15),
  Pokeball(R.string.Dive_Ball, R.string.Dive_Ball_flavor, R.drawable.pokeball_prop_16),
  Pokeball(R.string.Nest_Ball, R.string.Nest_Ball_flavor, R.drawable.pokeball_prop_17),
  Pokeball(R.string.Repeat_Ball, R.string.Repeat_Ball_flavor, R.drawable.pokeball_prop_18),
  Pokeball(R.string.Timer_Ball, R.string.Timer_Ball_flavor, R.drawable.pokeball_prop_19),
  Pokeball(R.string.Luxury_Ball, R.string.Luxury_Ball_flavor, R.drawable.pokeball_prop_20),
  Pokeball(R.string.Premier_Ball, R.string.Premier_Ball_flavor, R.drawable.pokeball_prop_21),
  Pokeball(R.string.Dusk_Ball, R.string.Dusk_Ball_flavor, R.drawable.pokeball_prop_22),
  Pokeball(R.string.Heal_Ball, R.string.Heal_Ball_flavor, R.drawable.pokeball_prop_23),
  Pokeball(R.string.Quick_Ball, R.string.Quick_Ball_flavor, R.drawable.pokeball_prop_24),
  Pokeball(R.string.Cherish_Ball, R.string.Cherish_Ball_flavor, R.drawable.pokeball_prop_25),
  Pokeball(R.string.Dream_Ball, R.string.Dream_Ball_flavor, R.drawable.pokeball_prop_26),
  Pokeball(R.string.Beast_Ball, R.string.Beast_Ball_flavor, R.drawable.pokeball_prop_27),
)

val preciousPropList = listOf(
  PreciousProp(R.string.Tiny_Mushroom, R.string.Tiny_Mushroom_flavor, R.drawable.precious_prop_1),
  PreciousProp(R.string.Big_Mushroom, R.string.Big_Mushroom_flavor, R.drawable.precious_prop_2),
  PreciousProp(R.string.Pearl, R.string.Pearl_flavor, R.drawable.precious_prop_3),
  PreciousProp(R.string.Big_Pearl, R.string.Big_Pearl_flavor, R.drawable.precious_prop_4),
  PreciousProp(R.string.Stardust, R.string.Stardust_flavor, R.drawable.precious_prop_5),
  PreciousProp(R.string.Star_Piece, R.string.Star_Piece_flavor, R.drawable.precious_prop_6),
  PreciousProp(R.string.Gold_Leaf, R.string.Gold_Leaf_flavor, R.drawable.precious_prop_7),
  PreciousProp(R.string.Silver_Leaf, R.string.Silver_Leaf_flavor, R.drawable.precious_prop_8),
  PreciousProp(R.string.Brick_Piece, R.string.Brick_Piece_flavor, R.drawable.precious_prop_9),
  PreciousProp(R.string.Nugget, R.string.Nugget_flavor, R.drawable.precious_prop_10),
  PreciousProp(R.string.Rare_Bone, R.string.Rare_Bone_flavor, R.drawable.precious_prop_11),
  PreciousProp(R.string.Pretty_Wing, R.string.Pretty_Wing_flavor, R.drawable.precious_prop_12),
  PreciousProp(R.string.Balm_Mushroom, R.string.Balm_Mushroom_flavor, R.drawable.precious_prop_13),
  PreciousProp(R.string.Big_Nugget, R.string.Big_Nugget_flavor, R.drawable.precious_prop_14),
  PreciousProp(R.string.Pearl_String, R.string.Pearl_String_flavor, R.drawable.precious_prop_15),
  PreciousProp(R.string.Comet_Shard, R.string.Comet_Shard_flavor, R.drawable.precious_prop_16),
  PreciousProp(R.string.Relic_Copper, R.string.Relic_Copper_flavor, R.drawable.precious_prop_17),
  PreciousProp(R.string.Relic_Silver, R.string.Relic_Silver_flavor, R.drawable.precious_prop_18),
  PreciousProp(R.string.Relic_Gold, R.string.Relic_Gold_flavor, R.drawable.precious_prop_19),
  PreciousProp(R.string.Relic_Vase, R.string.Relic_Vase_flavor, R.drawable.precious_prop_20),
  PreciousProp(R.string.Relic_Band, R.string.Relic_Band_flavor, R.drawable.precious_prop_21),
  PreciousProp(R.string.Relic_Statue, R.string.Relic_Statue_flavor, R.drawable.precious_prop_22),
  PreciousProp(R.string.Relic_Crown, R.string.Relic_Crown_flavor, R.drawable.precious_prop_23),
  PreciousProp(R.string.Strange_Souvenir, R.string.Strange_Souvenir_flavor, R.drawable.precious_prop_24),
  PreciousProp(R.string.Bottle_Cap, R.string.Bottle_Cap_flavor, R.drawable.precious_prop_25),
  PreciousProp(R.string.Gold_Bottle, R.string.Gold_Bottle_flavor, R.drawable.precious_prop_26),
  PreciousProp(R.string.Stretchy_Spring, R.string.Stretchy_Spring_flavor, R.drawable.precious_prop_27),
  PreciousProp(R.string.Chalky_Stone, R.string.Chalky_Stone_flavor, R.drawable.precious_prop_28),
  PreciousProp(R.string.Marble, R.string.Marble_flavor, R.drawable.precious_prop_29),
  PreciousProp(R.string.Lone_Earring, R.string.Lone_Earring_flavor, R.drawable.precious_prop_30),
  PreciousProp(R.string.Beach_Glass, R.string.Beach_Glass_flavor, R.drawable.precious_prop_31),
  PreciousProp(R.string.Polished_Mud, R.string.Polished_Mud_flavor, R.drawable.precious_prop_32),
  PreciousProp(R.string.Tropical_Shell, R.string.Tropical_Shell_flavor, R.drawable.precious_prop_33),
  )

val fossilList = listOf(
  Fossil(R.string.Helix_Fossil, R.string.Helix_Fossil_flavor, R.drawable.fossil_prop_1),
  Fossil(R.string.Dome_Fossil, R.string.Dome_Fossil_flavor, R.drawable.fossil_prop_2),
  Fossil(R.string.Old_Amber, R.string.Old_Amber_flavor, R.drawable.fossil_prop_3),
  Fossil(R.string.Root_Fossil, R.string.Root_Fossil_flavor, R.drawable.fossil_prop_4),
  Fossil(R.string.Claw_Fossil, R.string.Claw_Fossil_flavor, R.drawable.fossil_prop_5),
  Fossil(R.string.Skull_Fossil, R.string.Skull_Fossil_flavor, R.drawable.fossil_prop_6),
  Fossil(R.string.Armor_Fossil, R.string.Armor_Fossil_flavor, R.drawable.fossil_prop_7),
  Fossil(R.string.Cover_Fossil, R.string.Cover_Fossil_flavor, R.drawable.fossil_prop_8),
  Fossil(R.string.Plume_Fossil, R.string.Plume_Fossil_flavor, R.drawable.fossil_prop_9),
  Fossil(R.string.Jaw_Fossil, R.string.Jaw_Fossil_flavor, R.drawable.fossil_prop_10),
  Fossil(R.string.Sail_Fossil, R.string.Sail_Fossil_flavor, R.drawable.fossil_prop_11),
  Fossil(
    R.string.Fossilized_Bird,
    R.string.Fossilized_Bird_flavor,
    R.drawable.fossil_prop_12
  ),
  Fossil(
    R.string.Fossilized_Fish,
    R.string.Fossilized_Fish_flavor,
    R.drawable.fossil_prop_13
  ),
  Fossil(
    R.string.Fossilized_Drake,
    R.string.Fossilized_Drake_flavor,
    R.drawable.fossil_prop_14
  ),
  Fossil(
    R.string.Fossilized_Dino,
    R.string.Fossilized_Dino_flavor,
    R.drawable.fossil_prop_15
  ),
)

val foodList = listOf(
  FoodProp(R.string.Sausages, R.string.Sausages_flavor, R.drawable.food_prop_1),
  FoodProp(R.string.Bob_s_Food_Tins, R.string.Bob_s_Food_Tins_flavor, R.drawable.food_prop_2),
  FoodProp(R.string.Bach_s_Food_Tins, R.string.Bach_s_Food_Tins_flavor, R.drawable.food_prop_3),
  FoodProp(R.string.Tins_of_Beans, R.string.Tins_of_Beans_flavor, R.drawable.food_prop_4),
  FoodProp(R.string.Bread, R.string.Bread_flavor, R.drawable.food_prop_5),
  FoodProp(R.string.Pasta, R.string.Pasta_flavor, R.drawable.food_prop_6),
  FoodProp(R.string.Mixed_Mushrooms, R.string.Mixed_Mushrooms_flavor, R.drawable.food_prop_7),
  FoodProp(R.string.Smoke_Poke_Tails, R.string.Smoke_Poke_Tails_flavor, R.drawable.food_prop_8),
  FoodProp(R.string.Large_Leeks, R.string.Large_Leeks_flavor, R.drawable.food_prop_9),
  FoodProp(R.string.Fancy_Apples, R.string.Fancy_Apples_flavor, R.drawable.food_prop_10),
  FoodProp(R.string.Brittle_Bones, R.string.Brittle_Bones_flavor, R.drawable.food_prop_11),
  FoodProp(R.string.Packs_of_Potatoes, R.string.Packs_of_Potatoes_flavor, R.drawable.food_prop_12),
  FoodProp(R.string.Pungent_Roots, R.string.Pungent_Roots_flavor, R.drawable.food_prop_13),
  FoodProp(R.string.Salad_Mixes, R.string.Salad_Mixes_flavor, R.drawable.food_prop_14),
  FoodProp(R.string.Fried_Foods, R.string.Fried_Foods_flavor, R.drawable.food_prop_15),
  FoodProp(R.string.Boiled_Eggs, R.string.Boiled_Eggs_flavor, R.drawable.food_prop_16),
  FoodProp(R.string.Fruit_Bunches, R.string.Fruit_Bunches_flavor, R.drawable.food_prop_17),
  FoodProp(R.string.Moomoo_Cheese, R.string.Moomoo_Cheese_flavor, R.drawable.food_prop_18),
  FoodProp(R.string.Spice_Mix, R.string.Spice_Mix_flavor, R.drawable.food_prop_19),
  FoodProp(R.string.Fresh_Cream, R.string.Fresh_Cream_flavor, R.drawable.food_prop_20),
  FoodProp(R.string.Packaged_Curry, R.string.Packaged_Curry_flavor, R.drawable.food_prop_21),
  FoodProp(R.string.Coconut_Milk, R.string.Coconut_Milk_flavor, R.drawable.food_prop_22),
  FoodProp(R.string.Instant_Noodles, R.string.Instant_Noodles_flavor, R.drawable.food_prop_23),
  FoodProp(R.string.Precooked_Burgers, R.string.Precooked_Burgers_flavor, R.drawable.food_prop_24),
  FoodProp(R.string.Gigantamixes, R.string.Gigantamixes_flavor, R.drawable.food_prop_25),
)

val rotoList = listOf(
  RoToProp(R.string.Roto_Hatch, R.string.Roto_Hatch_flavor, R.drawable.roto_prop_1),
  RoToProp(R.string.Roto_Bargain, R.string.Roto_Bargain_flavor, R.drawable.roto_prop_2),
  RoToProp(R.string.Roto_Prize_Money, R.string.Roto_Prize_Money_flavor, R.drawable.roto_prop_3),
  RoToProp(R.string.Roto_Exp_Points, R.string.Roto_Exp_Points_flavor, R.drawable.roto_prop_4),
  RoToProp(R.string.Roto_Friendship, R.string.Roto_Friendship_flavor, R.drawable.roto_prop_5),
  RoToProp(R.string.Roto_Encounter, R.string.Roto_Encounter_flavor, R.drawable.roto_prop_6),
  RoToProp(R.string.Roto_Stealth, R.string.Roto_Stealth_flavor, R.drawable.roto_prop_7),
  RoToProp(R.string.Roto_HP_Restore, R.string.Roto_HP_Restore_flavor, R.drawable.roto_prop_8),
  RoToProp(R.string.Roto_PP_Restore, R.string.Roto_PP_Restore_flavor, R.drawable.roto_prop_9),
  RoToProp(R.string.Roto_Boost, R.string.Roto_Boost_flavor, R.drawable.roto_prop_10),
  RoToProp(R.string.Roto_Catch, R.string.Roto_Catch_flavor, R.drawable.roto_prop_11),
)

val battlePropList = listOf(
  BattleProp(R.string.Guard_Spec, R.string.Guard_Spec_flavor, R.drawable.battle_prop_1),
  BattleProp(R.string.Dire_Hit, R.string.Dire_Hit_flavor, R.drawable.battle_prop_2),
  BattleProp(R.string.X_Attack, R.string.X_Attack_flavor, R.drawable.battle_prop_3),
  BattleProp(R.string.X_Defense, R.string.X_Defense_flavor, R.drawable.battle_prop_4),
  BattleProp(R.string.X_Speed, R.string.X_Speed_flavor, R.drawable.battle_prop_5),
  BattleProp(R.string.X_Accuracy, R.string.X_Accuracy_flavor, R.drawable.battle_prop_6),
  BattleProp(R.string.X_Sp_Atk, R.string.X_Sp_Atk_flavor, R.drawable.battle_prop_7),
  BattleProp(R.string.X_Sp_Def, R.string.X_Sp_Def_flavor, R.drawable.battle_prop_8),
  BattleProp(R.string.Poké_Doll, R.string.Poké_Doll_flavor, R.drawable.battle_prop_9),
  BattleProp(R.string.Fluffy_Tail, R.string.Fluffy_Tail_flavor, R.drawable.battle_prop_10),
  BattleProp(R.string.Poké_Toy, R.string.Poké_Toy_flavor, R.drawable.battle_prop_11),
  BattleProp(R.string.Max_Mushrooms, R.string.Max_Mushrooms_flavor, R.drawable.battle_prop_12),
)

val evolutionPropList = listOf(
  EvolutionProp(
    fireColor,
    R.string.Fire_Stone,
    R.string.Fire_Stone_flavor,
    R.drawable.evolution_prop_1
  ),
  EvolutionProp(
    electricColor,
    R.string.Thunder_Stone,
    R.string.Thunder_Stone_flavor,
    R.drawable.evolution_prop_2
  ),
  EvolutionProp(
    waterColor,
    R.string.Water_Stone,
    R.string.Water_Stone_flavor,
    R.drawable.evolution_prop_3
  ),
  EvolutionProp(
    grassColor,
    R.string.Leaf_Stone,
    R.string.Leaf_Stone_flavor,
    R.drawable.evolution_prop_4
  ),
  EvolutionProp(
    normalColor,
    R.string.Moon_Stone,
    R.string.Moon_Stone_flavor,
    R.drawable.evolution_prop_5
  ),
  EvolutionProp(
    rockColor,
    R.string.Sun_Stone,
    R.string.Sun_Stone_flavor,
    R.drawable.evolution_prop_6
  ),
  EvolutionProp(
    fairyColor,
    R.string.Shiny_Stone,
    R.string.Shiny_Stone_flavor,
    R.drawable.evolution_prop_7
  ),
  EvolutionProp(
    darkColor,
    R.string.Dusk_Stone,
    R.string.Dusk_Stone_flavor,
    R.drawable.evolution_prop_8
  ),
  EvolutionProp(
    steelColor,
    R.string.Dawn_Stone,
    R.string.Dawn_Stone_flavor,
    R.drawable.evolution_prop_9
  ),
  EvolutionProp(
    iceColor,
    R.string.Ice_Stone,
    R.string.Ice_Stone_flavor,
    R.drawable.evolution_prop_10
  ),
  EvolutionProp(
    Color.Red,
    R.string.Sweet_Apple,
    R.string.Sweet_Apple_flavor,
    R.drawable.evolution_prop_11
  ),
  EvolutionProp(
    grassColor,
    R.string.Tart_Apple,
    R.string.Tart_Apple_flavor,
    R.drawable.evolution_prop_12
  ),
  EvolutionProp(
    bugColor,
    R.string.Cracked_Pot,
    R.string.Cracked_Pot_flavor,
    R.drawable.evolution_prop_13
  ),
  EvolutionProp(
    dragonColor,
    R.string.Chipped_Pot,
    R.string.Chipped_Pot_flavor,
    R.drawable.evolution_prop_14
  ),
  EvolutionProp(
    psychicColor,
    R.string.Galarica_Cuff,
    R.string.Galarica_Cuff_flavor,
    R.drawable.evolution_prop_15
  ),
  EvolutionProp(
    grassColor,
    R.string.Galarica_Wreath,
    R.string.Galarica_Wreath_flavor,
    R.drawable.evolution_prop_16
  )
)

val recoveryPropList = listOf(
  RecoveryProp(R.string.Potion, R.string.Potion_flavor, R.drawable.recovery_prop_1),
  RecoveryProp(R.string.Antidote, R.string.Antidote_flavor, R.drawable.recovery_prop_2),
  RecoveryProp(R.string.Burn_Heal, R.string.Burn_Heal_flavor, R.drawable.recovery_prop_3),
  RecoveryProp(R.string.Ice_Heal, R.string.Ice_Heal_flavor, R.drawable.recovery_prop_4),
  RecoveryProp(R.string.Awakening, R.string.Awakening_flavor, R.drawable.recovery_prop_5),
  RecoveryProp(R.string.Paralyze_Heal, R.string.Paralyze_Heal_flavor, R.drawable.recovery_prop_6),
  RecoveryProp(R.string.Full_Restore, R.string.Full_Restore_flavor, R.drawable.recovery_prop_7),
  RecoveryProp(R.string.Max_Potion, R.string.Max_Potion_flavor, R.drawable.recovery_prop_8),
  RecoveryProp(R.string.Hyper_Potion, R.string.Hyper_Potion_flavor, R.drawable.recovery_prop_9),
  RecoveryProp(R.string.Super_Potion, R.string.Super_Potion_flavor, R.drawable.recovery_prop_10),
  RecoveryProp(R.string.Full_Heal, R.string.Full_Heal_flavor, R.drawable.recovery_prop_11),
  RecoveryProp(R.string.Revive, R.string.Revive_flavor, R.drawable.recovery_prop_12),
  RecoveryProp(R.string.Max_Revive, R.string.Max_Revive_flavor, R.drawable.recovery_prop_13),
  RecoveryProp(R.string.Fresh_Water, R.string.Fresh_Water_flavor, R.drawable.recovery_prop_14),
  RecoveryProp(R.string.Soda_Pop, R.string.Soda_Pop_flavor, R.drawable.recovery_prop_15),
  RecoveryProp(R.string.Lemonade, R.string.Lemonade_flavor, R.drawable.recovery_prop_16),
  RecoveryProp(R.string.Moomoo_Milk, R.string.Moomoo_Milk_flavor, R.drawable.recovery_prop_17),
  RecoveryProp(R.string.Energy_Powder, R.string.Energy_Powder_flavor, R.drawable.recovery_prop_18),
  RecoveryProp(R.string.Energy_Root, R.string.Energy_Root_flavor, R.drawable.recovery_prop_19),
  RecoveryProp(R.string.Heal_Powder, R.string.Heal_Powder_flavor, R.drawable.recovery_prop_20),
  RecoveryProp(R.string.Revival_Herb, R.string.Revival_Herb_flavor, R.drawable.recovery_prop_21),
  RecoveryProp(R.string.Ether, R.string.Ether_flavor, R.drawable.recovery_prop_22),
  RecoveryProp(R.string.Max_Ether, R.string.Max_Ether_flavor, R.drawable.recovery_prop_23),
  RecoveryProp(R.string.Elixir, R.string.Elixir_flavor, R.drawable.recovery_prop_24),
  RecoveryProp(R.string.Max_Elixir, R.string.Max_Elixir_flavor, R.drawable.recovery_prop_25),
  RecoveryProp(R.string.Lava_Cookie, R.string.Lava_Cookie_flavor, R.drawable.recovery_prop_26),
  RecoveryProp(R.string.Berry_Juice, R.string.Berry_Juice_flavor, R.drawable.recovery_prop_27),
  RecoveryProp(R.string.Sacred_Ash, R.string.Sacred_Ash_flavor, R.drawable.recovery_prop_28),
  RecoveryProp(R.string.Rage_Candy_Bar, R.string.Rage_Candy_Bar_flavor, R.drawable.recovery_prop_29),
  RecoveryProp(R.string.Old_Gateau, R.string.Old_Gateau_flavor, R.drawable.recovery_prop_30),
  RecoveryProp(R.string.Sweet_Heart, R.string.Sweet_Heart_flavor, R.drawable.recovery_prop_31),
  RecoveryProp(R.string.Casteliacone, R.string.Casteliacone_flavor, R.drawable.recovery_prop_32),
  RecoveryProp(R.string.Lumiose_Galette, R.string.Lumiose_Galette_flavor, R.drawable.recovery_prop_33),
  RecoveryProp(R.string.Shalour_Sable, R.string.Shalour_Sable_flavor, R.drawable.recovery_prop_34),
  RecoveryProp(R.string.Big_Malasada, R.string.Big_Malasada_flavor, R.drawable.recovery_prop_35),
  RecoveryProp(R.string.Pewter_Crunchies, R.string.Pewter_Crunchies_flavor, R.drawable.recovery_prop_36),
  RecoveryProp(R.string.Max_Honey, R.string.Max_Honey_flavor, R.drawable.recovery_prop_37),
)